Improve date parameter validation
hapifhir/hapi-fhir pull request #2355
Opened 2021-02-04 15:53 UTC by michaelabuckley

Some query strings were interpreted as unsupported query prefix segments and discarded.  Changed to raise a DataFormatException instead.

2021-02-04 20:37 UTC, tadgh requested changes
Nice change! Approved pending  a couple tiny things:

1. Needs a changelog entry. 
2. Create a github issue detailing the problem, so that when you link to it in the changelog, users can click through the link to see the details of the problem this solved.

2021-02-04 20:37 UTC, tadgh commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/DateParamTest.java
> +		// too bad value is a j.u.Date instead of a new JSR-310 type
would be nice to be able to use JSR-310 dates

2021-02-04 20:37 UTC, tadgh commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/DateParamTest.java
> +		// Issue 1464 - the string "junk" wasn't returning 400 as expected.  Parsed as a prefix instead, and discarded.
Issue 1464/1465 does not exist in github, probably worth dropping it from the  test name.

2021-02-04 20:37 UTC, tadgh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/BaseParamWithPrefix.java
> +					throw new DataFormatException("Invalid prefix: \"" + prefix + "\"");
Nice! I cant believe we just let this slide before

2021-02-04 20:43 UTC, michaelabuckley commented
Where do changelogs live?  In hapi-fhir/hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_3_0/ ?

2021-02-04 20:50 UTC, tadgh commented
> Where do

You got it. Copy an existing one and update it to reflect your issue

2021-02-05 14:59 UTC, michaelabuckley commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/DateParamTest.java
> +		// Issue 1464 - the string "junk" wasn't returning 400 as expected.  Parsed as a prefix instead, and discarded.
I created issue #2361. Some invalid date parameters are silently ignored.

2021-02-05 15:34 UTC, tadgh approved these changes

2021-02-05 16:34 UTC, merged