2478 add extension mdm matcher
hapifhir/hapi-fhir pull request #2483
Opened 2021-03-17 20:12 UTC by longma1

Added mdm matcher based on extensions that returns true if two resources have one or more extensions in common with an optional theIdentifierSystem which can specify the url source of the extension.
Refactored TerserUtil by removing the comparison step in contains to its own function to create the equals function to deep compare two resources.

2021-03-18 16:02 UTC, nvg-smile commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/ExtensionMatcher.java
> +			if (leftExtensionValue.getUrl().equals(theIdentifierSystem) || theIdentifierSystem == null) {
That's probably a premature optimization, but can we check for nulls first? May be even extracting those checks into a separate method?

2021-03-18 19:24 UTC, longma1 commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java
> +		Method method = null;
I wanted to do something along the lines of:
`public static boolean equals(item1, item2){
equals(item1,item1,null);
}
`
to avoid duplicate logic but forgot to remove it when i added the entire thing for debugging purposes. Will remove this

2021-03-23 00:26 UTC, tadgh requested changes
Nicely tested! That said, I'm a bit confused about the purpose of this matcher. You are referring to `identifier system`s in a bunch of places, but this is for extensions by the looks of it. Also, your sample JSON shows a FHIRPath that goes to an identifer, which then reads the extensions on the identifier?

2021-03-23 00:26 UTC, tadgh commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/matcher/ExtensionMatcherR4Test.java
> +		assertFalse(MdmMatcherEnum.EXTENSION_ANY_ORDER.match(ourFhirContext, patient1, patient2, false, null));
I thought that unless you _specifically_ passed an extension URL, it would match on any urls? or am I misunderstanding the purpose of that optional field?

2021-03-23 00:26 UTC, tadgh commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/matcher/ExtensionMatcherR4Test.java
> +	public void testSpecificIdentifierSystem(){
ExtensionUrl

2021-03-23 00:26 UTC, tadgh commented on hapi-fhir-server-mdm/src/test/resources/rules-extension-search.json
> +		}
Gotta say I'm pretty confused.... are you comparing extensions _on identifiers_?

2021-03-23 13:53 UTC, nvg-smile commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/ExtensionUtil.java
> +	public static List<IBaseExtension<?, ?>> getExtensions(IBase theBase, Predicate<? super IBaseExtension> theFilter) {
Fixed, thank you.

2021-03-23 14:12 UTC, longma1 commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/matcher/ExtensionMatcherR4Test.java
> +		assertFalse(MdmMatcherEnum.EXTENSION_ANY_ORDER.match(ourFhirContext, patient1, patient2, false, null));
That is how the extension URL works but the matching still checks for matching URL and value so an extension from system A with value "123" does not match from an extension from system B with value "123"

2021-03-23 14:23 UTC, longma1 commented on hapi-fhir-server-mdm/src/test/resources/rules-extension-search.json
> +		}
yea, im just using this as a test if the json parser will accept EXTENSION_ANY_ODER but for the scope of the project I will be comparing extensions of identifiers

2021-03-23 14:38 UTC, nvg-smile commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/ExtensionUtil.java
> +	}
Fixed

2021-03-23 14:46 UTC, nvg-smile commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/ExtensionUtil.java
>  	public static List<IBaseExtension<?, ?>> getExtensions(IBaseHasExtensions theBase, String theExtensionUrl) {
Updated

2021-03-23 14:47 UTC, nvg-smile commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/PrimitiveTypeEqualsPredicate.java
> +import java.util.List;
Fixed

2021-03-23 14:49 UTC, nvg-smile commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java
> +	public static IBase getValue(FhirContext theFhirContext, IBaseResource theResource, String theFieldName) {
Fixed

2021-03-27 16:10 UTC, tadgh approved these changes

2021-03-29 14:13 UTC, merged