Kh 2526 add operation section to conformance statements resource section
hapifhir/hapi-fhir pull request #2575
Opened 2021-04-26 21:02 UTC by KevinIsAProgrammer

2021-04-26 21:10 UTC, patrick-vachon-smilecdr commented
Looks fine for me, but I'm still not an approved approver, so I can't approve it officially, yet. :-D

2021-04-27 15:51 UTC, tadgh requested changes
Code looks good, I'm just not sure if this actually sovles the issue. Can you post an actual conformance statement generated by this?

2021-04-27 15:51 UTC, tadgh commented on hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/ServerCapabilityStatementProviderR4Test.java
> +	}
This test just grabs the group resource, it also needs to actually assert contents I think

2021-04-27 15:51 UTC, tadgh commented on hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/ServerCapabilityStatementProviderR4Test.java
> +	public static class BulkDataExportProvider implements IResourceProvider {
Do we have to replicate the existing Bulk Export provider in this class? I'm worried this will drift as we make changes to the actual BulkExportProvider

2021-04-27 15:51 UTC, tadgh commented on hapi-fhir-validation/pom.xml
> +        </dependency>
I don't see this dep used anywhere in the code below. Is it supposed to be here?

2021-04-27 18:36 UTC, KevinIsAProgrammer commented on hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/ServerCapabilityStatementProviderR4Test.java
> +	public static class BulkDataExportProvider implements IResourceProvider {
It's just a copy of the annotations with stub methods, which is what James recommended for this test. :-)

2021-04-27 18:36 UTC, KevinIsAProgrammer commented on hapi-fhir-validation/pom.xml
> +        </dependency>
It doesn't want to run without it...

2021-04-27 18:37 UTC, KevinIsAProgrammer commented on hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/ServerCapabilityStatementProviderR4Test.java
> +	}
Good point. I had logged them, but the test should actually check them.

2021-04-27 18:59 UTC, KevinIsAProgrammer commented on hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/ServerCapabilityStatementProviderR4Test.java
> +	}
Here's the conformance statement it generates:{
  "resourceType": "CapabilityStatement",
  "id": "47660c79-95e0-49a5-910f-de71c1c57faf",
  "name": "RestServer",
  "status": "active",
  "date": "2021-04-27T14:58:18.008-04:00",
  "publisher": "Not provided",
  "kind": "instance",
  "software": {
    "name": "HAPI FHIR Server",
    "version": "5.4.0-PRE8-SNAPSHOT/3a901a6671/2021-04-27"
  },
  "implementation": {
    "description": "HAPI FHIR",
    "url": "http://localhost/baseR4"
  },
  "fhirVersion": "4.0.1",
  "format": [ "application/fhir+xml", "xml", "application/fhir+json", "json", "application/x-turtle", "ttl" ],
  "rest": [ {
    "mode": "server",
    "resource": [ {
      "type": "Group",
      "profile": "http://hl7.org/fhir/StructureDefinition/Group",
      "searchInclude": [ "*" ],
      "operation": [ {
        "name": "export",
        "definition": "http://localhost/baseR4/OperationDefinition/Group-it-export"
      }, {
        "name": "export-poll-status",
        "definition": "http://localhost/baseR4/OperationDefinition/Group-t-export-poll-status"
      } ]
    }, {
      "type": "OperationDefinition",
      "profile": "http://hl7.org/fhir/StructureDefinition/OperationDefinition",
      "interaction": [ {
        "code": "read"
      } ],
      "searchInclude": [ "*" ]
    } ]
  } ]
}

2021-04-27 19:51 UTC, tadgh approved these changes

2021-04-28 02:47 UTC, merged