2829 - Re-factored the R4-only tests to test both R4 and Dstu3.
hapifhir/hapi-fhir pull request #2832
Opened 2021-07-26 00:15 UTC by KevinDougan-SmileCDR

2021-08-04 20:48 UTC, tadgh requested changes
Implementation looks good, but I think the test suite should be cleaned up a bit.

2021-08-04 20:48 UTC, tadgh commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/HeaderPassthroughOptionR4Tests.java
> +}
I gotta say, I don't see how splitting this test class is helpful. Setting headers is completely identical regardless of which version of FHIR you are using. I would undo this refactor unless you've got an amazing reason for it, because at the end of the day its just harder to read than the original, (i have to go look at a super implementation to see what it is actually doing), and the 2 different FHIR versions exercise nothing differently. If you think the version difference _is_ exercising something of value, then make this test suite parameterized, instead of using inheritance.

2021-08-05 12:35 UTC, KevinDougan-SmileCDR commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/HeaderPassthroughOptionR4Tests.java
> +}
The HeaderPassThroughOptionTest was originally a Nested class within the UploadTerminologyCommandTest class. Once I re-factored the UploadTerminologyCommandTest class to support multiple FHIR versions, the Nested class no longer worked, so I created it as a separate class so we wouldn't lose any of those unit tests. I saw that it also specified a FHIR-VERSION when executing the App.main class, so I assumed (incorrectly, it seems) that it should also be re-factored to support multiple FHIR versions - I can revert this but I still need to create it as a separate test class to keep those tests intact.
So, we will end up with a new R4-only HeaderPassThroughOptionTest class (since you indicated that it doesn't matter which FHIR version is used), and a re-factored UploadTerminologyCommandTest class that supports DSTU3 and R4 and uses the JUnit Parameterized feature.
Is that an acceptable compromise?

2021-08-05 12:36 UTC, KevinDougan-SmileCDR commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/UploadTerminologyCommandDSTU3Test.java
> +}
I'll re-factor the UploadTerminologyCommandTest class to use the JUnit Parameterized feature - see my comment above.

2021-08-05 13:06 UTC, tadgh commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/HeaderPassthroughOptionR4Tests.java
> +}
That sounds perfect 👍🏻

2021-08-05 14:55 UTC, KevinDougan-SmileCDR commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/HeaderPassthroughOptionR4Tests.java
> +}
I have made the suggested changes to the test classes now and this is ready for a final review.

2021-08-05 15:47 UTC, tadgh approved these changes

2021-08-05 17:07 UTC, merged