Issue 2901 npe in bundle transaction
hapifhir/hapi-fhir pull request #2943
Opened 2021-09-02 13:50 UTC by TipzCM

2021-09-03 13:04 UTC, tadgh requested changes
Looks good! Just a few more tests need to be added to exercise a few things.

2021-09-03 13:04 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/AutoVersioningServiceImplTests.java
> +}
I would add some tests that actual touch a DB where you do the following: 
```
Patient p = new Patient();
DaoMethodOutcome outcome= myPatientDao.create(p);
myAutoVersioningService.getExistingAutoversionsForIds(Arrays.asList(outcome.getId()));
```

My guess is it will go boom.

2021-09-03 13:04 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoCreatePlaceholdersR4Test.java
> +		myPatientDao.update(patient);
As mentioned above, try to write a new test, but instead of using the dao update method, use the dao create, and get the returned ID.

2021-09-03 20:34 UTC, jamesagnew requested changes

2021-09-03 20:34 UTC, jamesagnew commented on hapi-fhir-jpaserver-api/src/main/java/ca/uhn/fhir/jpa/api/dao/IFhirResourceDao.java
> +	Map<IIdType, ResourcePersistentId> getIdsOfExistingResources(RequestPartitionId partitionId, Collection<IIdType> theIds);
I'd recommend against putting this method here - Smile CDR also has an implementation of the `IFhirResourceDao` interface for our MongoDB server so adding this will require a corresponding implementaiton there and it may not even be useful in that context. Also, typically anything on this interface is fhir-resource-type-specific but this method doesn't actually look like it cares about the resource type.

I think my recommendation would be to move this method into IdHelperService instead and just call it from there. You should be able to autowire an instance of that bean from anywhere you need it.

2021-09-03 20:34 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/AutoVersioningServiceImpl.java
> +	public Map<IIdType, ResourcePersistentId> getExistingAutoversionsForIds(RequestPartitionId theRequestPartitionId, Collection<IIdType> theIds) {
I guess similar to the comment above, you could also move this method into IdHelperService if you're moving the other one there. That'd avoid the need for any new beans which keeps things simple.

I also wonder about the name of this method - It's not terribly intuitive what an "autoversion" is in this context. Maybe `getLatestVersionIdsForResourceIds` ?

2021-09-03 20:34 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseStorageDao.java
> +					// 3 cases:
I love this kind of comment with the 3 possibilities. Always helpful!

2021-09-07 23:14 UTC, tadgh approved these changes
Looks good!

2021-09-07 23:50 UTC, jamesagnew approved these changes

2021-09-08 13:51 UTC, merged