3131 - Added support for the lookup operation in the Remote Terminology code
hapifhir/hapi-fhir pull request #3134
Opened 2021-11-01 20:26 UTC by KevinDougan-SmileCDR

Close #3131

2021-11-03 00:50 UTC, tadgh requested changes
Idea looks solid, couple changes needed though: 

1. All this STU-specific parameters work can be done with ParametersUtil, as it is STU-agnostic. 
2. This needs a changelog
3. I would like to see slightly more robust testing as there are lots of uncovered lines in this MR. This last one is a nice to have only, and not a blocker.

2021-11-03 00:50 UTC, tadgh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupportTest.java
> +	}
codecov reports lots of uncovered lines in this PR, can we build out the tests to cover them?

2021-11-03 19:47 UTC, KevinDougan-SmileCDR commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +					.named("$lookup")
Done.

2021-11-03 19:47 UTC, KevinDougan-SmileCDR commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +					paramsR4.addParameter().setName("language").setValue(new org.hl7.fhir.r4.model.StringType(theDisplayLanguage));
Done.

2021-11-04 12:13 UTC, KevinDougan-SmileCDR commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupportTest.java
> +	}
I added a new Unit Test specifically for DSTU3 and look forward to seeing the results of the next Code Coverage run.

2021-11-05 13:11 UTC, KevinDougan-SmileCDR commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupportTest.java
> +	}
Last commit for additional Code Coverage was made this morning...should be good-to-go now!

2021-11-05 14:13 UTC, tadgh approved these changes

2021-11-05 14:13 UTC, tadgh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +							return generateLookupCodeResultR4(theCode, theSystem, (org.hl7.fhir.r4.model.Parameters)outcome);
nitpick: you could also use parametersutil to fetch the params from the IBsaeParameters instead of switching. not a blocker though

2021-11-05 14:14 UTC, merged