3136 - Provide RemoteTerminologyServiceValidationSupport Implementation For Operation $validate-code
hapifhir/hapi-fhir pull request #3142
Opened 2021-11-04 12:53 UTC by KevinDougan-SmileCDR

Closes #3136

2021-11-16 16:24 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java
> +			if (myValidationSupportChain.isRemoteTerminologyServiceConfigured()) {
IMO let's just always pass validation requests through the validation support chain, instead of having this branching logic. I don't actually see any reason we need to specifically put it through the DAO method ever, the chain has caching and that kind of nice benefit so might as well always use it - That allows us to drop the `isRemoteTerminologyServiceConfigured` method too so we don't need any special handling in the chain

2021-11-16 16:24 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java
> +			if (myValidationSupportChain.isRemoteTerminologyServiceConfigured()) {
..unless there's something i'm not considering of course...

2021-11-16 16:27 UTC, jamesagnew requested changes
Lookin' good - But I think it could actually be simplified even more

2021-11-16 16:33 UTC, KevinDougan-SmileCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java
> +			if (myValidationSupportChain.isRemoteTerminologyServiceConfigured()) {
Hi @jamesagnew,

I did try using your suggestion of a more simplified approach with my first implementation, but it caused 77 Unit Tests to fail!

This new approach works without negatively impacting those DAO-based Unit Tests and greatly reduces the work required to implement a solution.

Let me know if this new approach is still acceptable, or if you want me to go back and try to address it using the single validation support chain approach, and working on those failing DAO-based Unit Tests...

Thanks!
Kevin

2021-11-16 17:19 UTC, KevinDougan-SmileCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java
> +			if (myValidationSupportChain.isRemoteTerminologyServiceConfigured()) {
Actually, let me try that simplified approach one more time. I might've ran into problems earlier with my Unit Tests not properly cleaning up their artifacts in the @AfterEach method...

2021-11-22 21:18 UTC, jdar8 approved these changes

2021-11-22 21:19 UTC, KevinDougan-SmileCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java
> +			if (myValidationSupportChain.isRemoteTerminologyServiceConfigured()) {
The DAO Unit Test failures were not a "quick fix" and therefore, I'll go ahead with this approach, and look for an opportunity to re-factor the implementation to make it simpler in the future.

2021-11-23 15:39 UTC, tadgh commented
I am going to merge this for now, with sights towards a refactor defined here: https://github.com/hapifhir/hapi-fhir/issues/3184

2021-11-23 15:39 UTC, merged