Validate contains change
hapifhir/hapi-fhir pull request #3209
Opened 2021-12-02 16:17 UTC by markiantorno

Give me a moment to review this myself first, then  I will provide details and tag people.

2021-12-02 21:46 UTC, markiantorno commented
Alright so, these changes are related to bumping the dependency on [org.hl7.fhir.core](https://github.com/hapifhir/org.hl7.fhir.core) to version 5.3.0. 

The main updates that resulted in the majority of the changes in this PR were the addition of the interface [IValidationPolicyAdvisor](https://github.com/hapifhir/org.hl7.fhir.core/blob/4d0692ff61880f37083ad0738fcf25571dcc9cc5/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/validation/IValidationPolicyAdvisor.java), and the refactoring of some of the main validation classes (for cleaning purposes). Also, many of the error messages were updated, so the resulting tests in HAPI had to be modified to reflect these message changes.

In regard to the new interface IValidationPolicyAdvisor, by implementing this interface and passing it through the validation context in HAPI to the [InstanceValidator] (https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java) in the core libraries, users can now control the behavior of the validator when validating references, contained resources, and coded content. Previously, only references were controlled in this way, and users controlled this by overriding the validation fetcher.

Test cases were added in the [validation test cases repository](https://github.com/FHIR/fhir-test-cases/) to demonstrate it's functionality. In particular, the two test cases `contained-resource-bad-id`, and `contained-resource-bad-id-ignore`. The definitions and expected outcomes of these test cases are in the [manifest.json](https://github.com/FHIR/fhir-test-cases/blob/master/validator/manifest.json) in that repository.

Please let me know if you have any questions.

2021-12-02 23:54 UTC, tadgh requested changes
Overall looks good, just a couple minor questions for my own clarity, and some minor style stuff. 

1. This requires a changelog
2. Does this change _break_ Smile CDR? If so, bumping the HAPI version makes sense here, otherwise you can leave it at PRE3. 

Otherwise, lgtm.

2021-12-02 23:54 UTC, tadgh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/validation/FhirValidator.java
> +	private IInterceptorBroadcaster iInterceptorBroadcaster;
HAPI convention is `my` as a prefix for member variables. 

2021-12-02 23:54 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoDstu3ValidateTest.java
> +		BestPracticeWarningLevel a = BestPracticeWarningLevel.Ignore;
may as well fix the variable name while you're in here. `a` is not great.

2021-12-02 23:54 UTC, tadgh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirDefaultPolicyAdvisor.java
> +		return ContainedReferenceValidationPolicy.CHECK_VALID;
this spacing kinda wild. might just be GH formatting, but try to de-dent the parameters a few levels.

2021-12-02 23:54 UTC, tadgh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionTypeAdvisorDstu21.java
> +public class VersionTypeAdvisorDstu21 extends BaseAdvisor_14_50 {
14_50 ? what is 14? and what does 21 mean here?

2021-12-02 23:54 UTC, tadgh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java
> +		verify(resourceFetcher, times(12)).resolveURL(any(), any(), anyString(), anyString(), anyString());
any clue why this number had to change? Just internal refactoring requiring less calls?

2021-12-03 14:02 UTC, markiantorno commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionTypeAdvisorDstu21.java
> +public class VersionTypeAdvisorDstu21 extends BaseAdvisor_14_50 {
I didn't wite it,but I'm pretty sure DSTU21 is MAY2014 release that was a special release done for Telus.

It is referred to in the conversion libraries by the shortform '14'.
```
10 = DSTU2
14 = DSTU2014MAY
30 = DSTU3
40 = R4
50 = R5
```

So, if you can tell the purpose of a conversion class/util through it's name
***_10_50 -> Converts from DSTU2 to R5 and back
***_14_50 -> Converts from DSTU2014 to R5 and back
***_10_30 -> DSTU2 to DSTU3 and back
etc

2021-12-03 14:03 UTC, markiantorno commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java
> +		verify(resourceFetcher, times(12)).resolveURL(any(), any(), anyString(), anyString(), anyString());
The internal refactoring in the validator resulted in less calls. Same result as before though.

2021-12-06 14:07 UTC, markiantorno commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoDstu3ValidateTest.java
> +		BestPracticeWarningLevel a = BestPracticeWarningLevel.Ignore;
Fixed

2021-12-06 14:08 UTC, markiantorno commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirDefaultPolicyAdvisor.java
> +		return ContainedReferenceValidationPolicy.CHECK_VALID;
Fixed

2021-12-06 14:10 UTC, markiantorno commented
> Overall looks good, just a couple minor questions for my own clarity, and some minor style stuff.
> 
>     1. This requires a changelog
> 
>     2. Does this change _break_ Smile CDR? If so, bumping the HAPI version makes sense here, otherwise you can leave it at PRE3.
> 


Chagelog added, and this will break things in CDR, so I bumped to PRE-4

2021-12-06 16:24 UTC, tadgh approved these changes

2021-12-06 16:25 UTC, merged