3242 search content param removed not readded
hapifhir/hapi-fhir pull request #3244
Opened 2021-12-13 18:49 UTC by TipzCM

closes #3242 

Changes:
* Fixed issue of searchmap mutation
* added changelog
* updated unit tests

2021-12-13 18:52 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java
> +					List<List<IQueryParameterType>> textAndTerms = theParams.get(Constants.PARAM_TEXT);
This behaviour is intentional, so that HAPI-FHIR's DAO-layer does not process _content or _text parameters, and they are only processed by the fulltext service. What is the impetus for this change?

2021-12-14 15:03 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java
> +					List<List<IQueryParameterType>> textAndTerms = theParams.get(Constants.PARAM_TEXT);
Fixed - changed to copy params

2021-12-17 06:50 UTC, tadgh requested changes
Minor changes requested, specifically just  a minor addition to a test, and a few naming/doc nitpicks. Overall, great work, and nice comments.

2021-12-17 06:50 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml
> +title: "Fixed bug that caused accurate elastisearch searches to return all values when using
```suggestion
title: "Fixed bug that caused queries that checked Elastisearch when setting `_total=accurate` searches to return all values when using
```

2021-12-17 06:50 UTC, tadgh commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java
> +	public SearchParameterMap cpy() {
```suggestion
	public SearchParameterMap clone() {
```

2021-12-17 06:50 UTC, tadgh commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java
> +		}
I would like to see logic in the below test which exercises this part of the clone. I'd like to see in test that the two actual SP sets are the same. The current test just asserts on flags of the sp map, so i think this enhancement would help.

2021-12-17 14:50 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java
> +		}
the test actually does do that, too.

but i added a more explicit test

2022-01-04 17:58 UTC, tadgh approved these changes
Approved pending super minot changes.

2022-01-04 17:58 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml
> +title: "Fixed bug that caused queries that checked Elastisearch when setting `_total=accurate` searches to return all
```suggestion
title: "Fixed bug that caused queries that checked Elasticsearch when setting `_total=accurate` searches to return all
```

2022-01-04 17:58 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +	//TODO - remove
is this a valid todo?

2022-01-04 17:58 UTC, tadgh commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java
> +	 * @return
incomplete docstring, remove the return or fill it out

2022-01-04 19:38 UTC, merged