3283 delete will not return a 404 if resource is not found
hapifhir/hapi-fhir pull request #3284
Opened 2022-01-06 19:37 UTC by TipzCM

closes #3283 

Fixed code to not throw a 404 if resource is not found on delete.
Added changelog

2022-01-06 21:00 UTC, fil512 requested changes

2022-01-06 21:00 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDaoTest.java
>  class BaseHapiFhirResourceDaoTest {
This needs to be a provider integration test.  Probably in `ResourceProviderR4Test`.

2022-01-07 18:15 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java
> +	private DaoMethodOutcome createMethodOutcomeForDelete(String theId) {
will return 200 as per james/gary's suggestion

2022-01-17 16:48 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void testDeleteNonExistentResourceReturns200() throws IOException {
Please also test the scenario where you create a patient, delete it, and then delete it a second time.

2022-01-17 19:53 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDaoTest.java
>  class BaseHapiFhirResourceDaoTest {
added Integration Tests as required

2022-01-17 19:53 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void testDeleteNonExistentResourceReturns200() throws IOException {
Added Integration Test testing double deletes, as required

2022-01-17 20:34 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		String id = "A";
This is the same id as the test above which means the test execution order could affect the outcome.  Find a way to make the id unique for each test.  (Some people use the test method name.  I like using interesting names.  Doesn't really matter how.)

2022-01-17 20:38 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		HttpDelete delete = new HttpDelete(ourServerBase + "/Patient/A");
These operations should be done using myClient, not HttpDelete etc

2022-01-17 20:38 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		HttpPut put = new HttpPut(ourServerBase + "/Patient/" + id);
These operations should be done using myClient, not HttpDelete etc

2022-01-17 22:06 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		HttpDelete delete = new HttpDelete(ourServerBase + "/Patient/A");
Actually looks like there's no way to get the status out otherwise, so STET this one.

2022-01-17 22:06 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		HttpPut put = new HttpPut(ourServerBase + "/Patient/" + id);
Actually looks like there's no way to get the status out otherwise, so STET this one.

2022-01-18 16:07 UTC, jamesagnew approved these changes

2022-01-18 16:13 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		String id = "A";
updated ids

2022-01-18 17:01 UTC, fil512 approved these changes

2022-01-18 18:07 UTC, merged