2718 cross partition support for subscription
hapifhir/hapi-fhir pull request #3298
Opened 2022-01-13 19:21 UTC by longma1

added the option for subscriptions to be matched against resources from all partitions rather than just the the partition the subscription is saved on

2022-01-17 16:27 UTC, TipzCM requested changes

2022-01-17 16:27 UTC, TipzCM commented on hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/entity/ModelConfig.java
> +	private boolean crossPartitionSubscription = false;
should this be called myCrossPartitionSubscription?

2022-01-21 15:04 UTC, TipzCM approved these changes
looks good. just some little things to fix

2022-01-21 19:05 UTC, longma1 commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/subscription/SubscriptionValidatingInterceptorTest.java
> +		;
huh how did that get in there, fixed.

2022-01-21 22:04 UTC, merged