3335 allow alternative character encoding length in searchparam
hapifhir/hapi-fhir pull request #3336
Opened 2022-01-26 19:08 UTC by TipzCM

closes #3335 

Added support to allow specifying max code length for phonetic encoders (for supported encoders only - metaphone and double_metaphone).
Added change log

2022-01-26 19:36 UTC, tadgh requested changes

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderEnum.java
> +	 * Use PhoneticEncoderWrapper instead.
use {@link PhoneticEncoderWrapper} notation here for easy tracing.

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +	 */
If you're going to write javadocs, may as well use the standard format: 

```
	/**
	 * Subclasses should override this method to supply the set of compartments that
	 * the user making the request should actually have access to.
	 *
	 * <p>
	 * Typically this is done by examining <code>theRequestDetails</code> to find
	 * out who the current user is and then building a list of Strings.
	 * </p>
	 *
	 * @param theRequestDetails The individual request currently being applied
	 *
	 * @return The list of allowed compartments and instances that should be used
	 * for search narrowing. If this method returns <code>null</code>, no narrowing will
	 * be performed
	 */
```

```

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +		}
suggest refactoring the number-finder into another method, and call it instead of doing the finding in-line

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3335-added-configuration-to-specify-max-code-lengths.yml
> +smile: 3603
`smile` is not a key that goes into changelogs. If anything, you are looking for `jira: SMILE-1234` for the jira link.

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3335-added-configuration-to-specify-max-code-lengths.yml
> +      Phonetic Encoders (Metaphone, Double_Metaphone)."
indicate _how_ to do this somewhere. In [documentation](https://smilecdr.com/docs/fhir_repository/search_parameter_phonetic.html), and also this changelog, for those who only use hapi-fhir

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchCustomSearchParamTest.java
> +	}
very nice test!

Generally for asserts, we import them individually, so you just do `assertNotEquals` without having to qualify with `Assertions.`

2022-01-26 19:36 UTC, tadgh commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapperTest.java
> +	}
I would add tests for more weird edge cases. e.g.

`METAPHONE()`
`METAPHONE(-1)`
`METAPHONE(INT_MAX)` :P 
`METAPHONE(()`

2022-01-26 19:55 UTC, fil512 approved these changes

2022-01-26 19:55 UTC, fil512 commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +			switch (enumVal) {
Nitpick: We should use polymorphism for this. Not a switch statement

2022-01-26 19:55 UTC, fil512 commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +public class PhoneticEncoderWrapper {
Rather than calling it a wrapper (which I feel is a specific design pattern that doesn't really apply here) can we instead call it a ParameterizedPhoneticEncoder.  And can it interoperate with a regular PhoneticEncoder so we can mix and match them (i.e. they both implement the same interface called something like IPhoneticEncoder).

2022-01-26 20:55 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3335-added-configuration-to-specify-max-code-lengths.yml
> +      Phonetic Encoders (Metaphone, Double_Metaphone)."
as discussed, the documentation update will happen in https://gitlab.com/simpatico.ai/cdr/-/issues/2780

2022-01-26 20:58 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderEnum.java
> +	 * Use PhoneticEncoderWrapper instead.
done

2022-01-26 20:58 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +	 */
updated

2022-01-26 20:58 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3335-added-configuration-to-specify-max-code-lengths.yml
> +smile: 3603
fixed

2022-01-26 20:58 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchCustomSearchParamTest.java
> +	}
updated

2022-01-26 20:58 UTC, TipzCM commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapperTest.java
> +	}
added

2022-01-26 20:59 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +public class PhoneticEncoderWrapper {
Refactored into Utils class so IPhoneticEncoder is returned directly instead.

2022-01-26 20:59 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +		}
Refactored out.

2022-01-26 21:00 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +			switch (enumVal) {
Hmm. Is there more insight you can give me on this?

Does this comment still make sense now that we refactored out the "wrapper" class?

I think we'll need a switch statement either way to take enum value -> encoder.

2022-01-26 21:31 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/phonetic/PhoneticEncoderWrapper.java
> +			switch (enumVal) {
updated

2022-01-27 16:36 UTC, tadgh approved these changes

2022-01-27 17:29 UTC, merged