Can't specify specific resource type permissions for bulk export
hapifhir/hapi-fhir pull request #3376
Opened 2022-02-10 19:00 UTC by oliviayou

Closes [#3394](https://github.com/hapifhir/hapi-fhir/issues/3394)
* When exporting data that should only belong to a specific group of resources the user is permitted to export, data from other groups is returned. This has been corrected.
* New tests
* Add changelog

2022-02-10 19:58 UTC, fil512 requested changes

2022-02-10 19:58 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/RuleBulkExportImpl.java
> +					return new AuthorizationInterceptor.Verdict(PolicyEnum.DENY,this);
please add a unit test for this fix

2022-02-11 16:10 UTC, oliviayou commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/RuleBulkExportImpl.java
> +					return new AuthorizationInterceptor.Verdict(PolicyEnum.DENY,this);
added

2022-02-14 21:52 UTC, fil512 approved these changes

2022-02-14 21:52 UTC, merged