Smile 2775 package install logs ignore resource validation
hapifhir/hapi-fhir pull request #3381
Opened 2022-02-11 15:15 UTC by kailiu-smile

Added method to get URL from SearchParameter resource. Added log entries for package install validation.

2022-02-11 17:13 UTC, tadgh requested changes

2022-02-11 20:23 UTC, kailiu-smile commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +			ourLog.warn("Failed to upload resource of type {} with ID {} - Error: Resource failed validation", theResource.fhirType(), theResource.getIdElement().getValue());
We are working with package install which is directly linked to pre-seeding. Its main function is to ingest implementation guides. These implementation guides often have many different versions. Many of theses versions contain “draft” resources and should NOT be installed. i.e, they will fail validation. We EXPECT the validation to deny certain resources. Throwing any kind of error would terminate the installation of the package, hence why we are throwing a warning

2022-02-11 20:42 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +			ourLog.warn("Failed to upload resource of type {} with ID {} - Error: Resource failed validation", theResource.fhirType(), theResource.getIdElement().getValue());
understood 👍🏻

2022-02-28 18:41 UTC, tadgh approved these changes

2022-02-28 19:52 UTC, merged