Convert Reindex into Batch2 Job
hapifhir/hapi-fhir pull request #3458
Opened 2022-03-08 11:09 UTC by jamesagnew

2022-03-14 15:58 UTC, TipzCM requested changes

2022-03-14 15:58 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/reindex/ResourceReindexSvcImpl.java
> +		Slice<Object[]> slice = myResourceTableDao.findIdsTypesAndUpdateTimesOfResourcesWithinUpdatedRangeOrderedFromOldest(page, theStart, theEnd);
I feel like it might be clearer to have either a service in the way between these calls (and the service returns a serializable obj instead of an Object[])

Or maybe we can at least document what these values in the array are. It's used down lower - t[0], t[1], etc. But since this code has nothing to do with the dao, it's entirely possible that someone might update the dao and miss these lines, breaking this functionality.

2022-03-14 15:58 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/GenerateRangeChunksStep.java
> +				String nextResourceType = nextUrl.substring(0, nextUrl.indexOf('?'));
is the url guaranteed to have query params? (the `?` in the string)

2022-03-14 15:58 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexStep.java
> +	private static final Logger ourLog = LoggerFactory.getLogger(ReindexStep.class);
minor - but can we have the logger on the top of the class?

2022-03-14 15:58 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java
> +		mySvc = new ReindexProvider(myCtx, myJobCoordinator);
does @InjectMocks not work? 🤔  (you might have to annotate myCtx with @Spy )

2022-03-14 15:58 UTC, TipzCM commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/svc/IResourceReindexSvc.java
> +	boolean isAllResourceTypeSupported();
Q: if this returned false, how would we know which resource types are supported?

2022-03-14 20:27 UTC, StevenXLi commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/svc/IResourceReindexSvc.java
> +	boolean isAllResourceTypeSupported();
I believe this is for whether reindexing on all the resources at the same time is supported. As oppose to, if a given resource type is supported for reindexing

2022-03-16 17:41 UTC, jamesagnew commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/GenerateRangeChunksStep.java
> +				String nextResourceType = nextUrl.substring(0, nextUrl.indexOf('?'));
Yup, it's enforced in the constraints on the model object.

2022-03-16 17:41 UTC, jamesagnew commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexJobParameters.java
> +	private List<@Pattern(regexp = "^[A-Z][A-Za-z0-9]+\\?.*", message = "If populated, URL must be a search URL in the form '{resourceType}?[params]'") String> myUrl;
Exactly.

2022-03-16 17:41 UTC, jamesagnew commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexStep.java
> +	private static final Logger ourLog = LoggerFactory.getLogger(ReindexStep.class);
Whoops... Will move.

2022-03-16 17:51 UTC, jamesagnew commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java
> +		mySvc = new ReindexProvider(myCtx, myJobCoordinator);
Ooh great suggestion! Just tried it and you're right, it needs that `@Spy` but with that added it works. I didn't even think of that.

2022-03-16 18:12 UTC, jamesagnew commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/svc/IResourceReindexSvc.java
> +	boolean isAllResourceTypeSupported();
Oh man - I meant to add a validator that would reject the job is this returned false and no URLs were supplied, and your comment reminded me that I forgot all about that.

Have added one, thanks.

2022-03-16 18:57 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/reindex/ResourceReindexSvcImpl.java
> +		Slice<Object[]> slice = myResourceTableDao.findIdsTypesAndUpdateTimesOfResourcesWithinUpdatedRangeOrderedFromOldest(page, theStart, theEnd);
That's what this service is (the intermediary betwen the JPA Repository DAOs and the actual reindexer). FWIW the javadocs for the repository DAO do explicitly state what the values in the object array are and in what order. It's ugly I agree, but I can't find any other way of writing a query that selects a projection.

2022-03-16 18:58 UTC, jamesagnew commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/LoadIdsStep.java
> +			if (nextChunk.getLastDate().getTime() == previousLastTime) {
I thought about that, but we'd run into issues if multiple resources have the same timestamp and come back in different orders (unlikely but not impossible). This way seems safer.

2022-03-16 19:16 UTC, TipzCM approved these changes

2022-03-19 20:07 UTC, merged