3470 ne date search
hapifhir/hapi-fhir pull request #3471
Opened 2022-03-16 19:00 UTC by oliviayou

* add support for the `NOT_EQUAL` prefix on dates
* refactored the `addParam(...)` method to group together operations when `theParsed.getPrefix()` is null, EQUAL, or NOT_EQUALS
* add changelog
* add test

2022-03-24 00:15 UTC, jdar8 reviewed
I like the refactor, great work!

2022-03-24 20:28 UTC, TipzCM requested changes

2022-03-24 20:28 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/DateRangeParam.java
> +		switch (theParsed.getPrefix()) {
Can we at least add some unit tests for all your various DateRange options (including error states)?

There's a DateRangeParamTest class. I suggest adding them there.

`setValueAsQueryTokens_conditionUnderTest_expectedResult()`


Might help with understanding the lower down logic for me, too. Cause it seems unusual to me that you check lowerbound is not null. Then set it to something anyways (for instance)

2022-03-25 15:14 UTC, oliviayou commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/DateRangeParam.java
> +		switch (theParsed.getPrefix()) {
Sure, I added some tests for the `ne` DateRange option inside `DateRangeParamTest`.
The null check for the lower bound was written back in 2015 (it shows up because i refactored this method) so I am not sure if the error would be invoked unless we introduce a bug that sets the lower or upper bound more than once.

2022-03-25 18:59 UTC, TipzCM approved these changes
Just minor changes please :)

2022-03-25 18:59 UTC, TipzCM commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/DateRangeParamTest.java
> +	public void testSetValueAsQueryTokens_neDay() {
Looking good!

But as a minor point (i want to try and adapt a new standard here), can you rename all your unit tests as follows?

methodUnderTest_testConditions_expectedResult()

eg:
setValuesAsQueryTokens_withQualifiedParamListNEToGivenDate_setsLowerBoundValue

or something like this

2022-03-25 21:51 UTC, merged