Allowing any client assigned ID throws ResourceNotFoundException when creating a resource
hapifhir/hapi-fhir pull request #3505
Opened 2022-03-29 21:06 UTC by oliviayou

2022-03-30 07:30 UTC, jkiddo commented
I believe this relates to https://github.com/hapifhir/hapi-fhir/issues/3462

2022-04-11 18:33 UTC, jamesagnew requested changes
I'm having trouble understanding this fix TBH - There is a new parameter `isPid` added to `resolveResourcePersistentIds(...)` but it doesn't have any javadoc and I'm not clear on what it actually signifies.

You seem to be calling it as `false` for everything except the codesystem lookup, but it's not clear to me why that specific lookup satisfies `isPid`. Perhaps that parameter needs a more descriptive name and a javadoc explaining what it does what when you might set it to true/false?

2022-04-11 19:27 UTC, oliviayou commented
I added some javadocs for this new parameter, now named, `theIdIsPid`. I felt this parameter was required because we don't have a way to track whether an id passed into `resolveResourcePersistentIds(...)` is a pid or a forced id when `ClientIdStrategyEnum=ANY` because both can be fully numeric.

I might be wrong, but it looks like the only instance where `resolveResourcePersistentIds(...)` is called and the id is a pid is after the CodeSystem lookup, hence being set to true.

2022-04-11 21:39 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +		ResourcePersistentId codeSystemResourcePid = myIdHelperService.resolveResourcePersistentIds(RequestPartitionId.allPartitions(), csId.getResourceType(), csId.getIdPart(), true);
Ok, now that I see your addition.. I get what you're doing but this fix makes me uneasy. Technically an `IIdType` should never have a PID in it. So I think you're fixing the wrong problem here.

Based on the unit test you added, your server ID strategy is UUID, meaning that `csId` should have that UUID. IMO the right thing to do is to investigate why the UUID that is assigned to the new resource doesn't end up being populated into that `IIdType`

2022-04-12 19:59 UTC, fil512 requested changes

2022-04-12 19:59 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/index/IdHelperService.java
> +	public ResourcePersistentId resolveResourcePersistentIds(@Nonnull RequestPartitionId theRequestPartitionId, String theResourceType, String theId, boolean theIdIsPid) {
Adding a boolean flag to a method is an anti-pattern.   See https://martinfowler.com/bliki/FlagArgument.html

Instead, create a new method name.

2022-04-12 20:03 UTC, oliviayou commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/index/IdHelperService.java
> +	public ResourcePersistentId resolveResourcePersistentIds(@Nonnull RequestPartitionId theRequestPartitionId, String theResourceType, String theId, boolean theIdIsPid) {
Thanks! the plan is to take out this parameter and fix the underlying problem with the IIdType having a PID or resource path in it

2022-04-14 18:38 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +				ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(theCodeSystem.getUserData(RESOURCE_PID_KEY));
Tiny nitpick:

Recommend replacing:

```java
ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(theCodeSystem.getUserData(RESOURCE_PID_KEY));
```

with

```java
Long pid = (Long)theCodeSystem.getUserData(RESOURCE_PID_KEY);
assert pid != null;
ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(pid);
```

Just in case someone ever makes a change that causes the PID to not end up in that map, this assert should avoid any hard-to-figure out bugs, since that would probably cause an NPE much later

2022-04-14 18:38 UTC, jamesagnew approved these changes

2022-04-14 18:46 UTC, oliviayou commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +				ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(theCodeSystem.getUserData(RESOURCE_PID_KEY));
That makes perfect sense! Replaced 👍🏻

2022-04-14 20:46 UTC, oliviayou commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +				ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(theCodeSystem.getUserData(RESOURCE_PID_KEY));
The assert statement helped me realize that it's breaking stuff in r5 . This is because in the hl7 fhir convertor does not convert the userData field (which contains the pid) from the r5 to the r4 model in `convertCodeSystem(org.hl7.fhir.r5.model.CodeSystem src)` 

Our options are 
1. add the userData field to the convertor, or 
2. find another way to get the pid (`theCodeSystem.getIdElement().myUnqualifiedId`)

Thoughts?

2022-04-14 22:11 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +				ResourcePersistentId codeSystemResourcePid = new ResourcePersistentId(theCodeSystem.getUserData(RESOURCE_PID_KEY));
@oliviayou could we copy it over wherever it gets converted? ie. not modify the converter, but modify whatever thing in the term service classes is calling it?

2022-04-17 12:02 UTC, jamesagnew approved these changes

2022-04-17 12:02 UTC, merged