3658 adding updating with history rewrite feature
hapifhir/hapi-fhir pull request #3659
Opened 2022-05-30 21:26 UTC by StevenXLi

2022-06-03 14:33 UTC, tadgh requested changes
Overall looks great!, but theres enough changes that need to be made that I'm going to set it to request changes. This is a pretty big feature, so we want as much coverage as possible. The parts I'm most concerned about are:

1. What happens in the case of current resource version (with history number included, e.g. _history/3)  when the setting is enabled. Ensure that theres no new entries in the table. 
2. The RuleBuilder is just unfamiliar enough to me that I'm not sure this implementation is solid. I'm going to delegate to another dev to review that chunk.
3. The IGenericClient has no new tests in it for new behaviour.
4. The RuleBuilder has no new tests in it for the new behaviour.

2022-06-03 14:33 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	}
nitpick (non-blocking): When extracting a common piece of functionality, it generally pays dividends to write a javadoc for the newly extracted method.

2022-06-03 14:33 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +
nice refactor 🎉

2022-06-03 14:33 UTC, tadgh commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4HistoryRewriteTest.java
> +
This test class overall looks good, but I need to see a couple things: 
1. Ensure that ResourceHistoryTableDao has the same number of entries _before_ and _after_ the update.
2. Know what the _intended_ behaviour is when they pass in the current version. Existing behaviour would cause a new version, but when this flag is enabled, no new version would be created. Is that accurate as per our implementation docs? That just needs to be verified.

2022-06-03 15:07 UTC, jamesagnew requested changes

2022-06-03 15:12 UTC, StevenXLi commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/i18n/Msg.java
I didn't know the current HAPI FHIR doesn't throw an error when a version is included in the URL for Update. I agree that is bad.
I will add in the requirement for custom header for this operation, i think that's a good idea.

2022-06-03 17:27 UTC, StevenXLi commented
> Overall looks great!, but theres enough changes that need to be made that I'm going to set it to request changes. This is a pretty big feature, so we want as much coverage as possible. The parts I'm most concerned about are:
> 
> 1. What happens in the case of current resource version (with history number included, e.g. _history/3)  when the setting is enabled. Ensure that theres no new entries in the table.
> 2. The RuleBuilder is just unfamiliar enough to me that I'm not sure this implementation is solid. I'm going to delegate to another dev to review that chunk.
> 3. The IGenericClient has no new tests in it for new behaviour.
> 4. The RuleBuilder has no new tests in it for the new behaviour.

@tadgh for 3., the tests are written on the cdr side, should I move those over, or write more tests on the hapi side?

2022-06-07 16:55 UTC, StevenXLi commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/GenericClient.java
> +			}
I can definitely add a check here

2022-06-07 17:02 UTC, StevenXLi commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_plain/rest_operations.md
> +ID of the resource to delete.
it's from using commit in IntelliJ with reformat code option checked i believe

2022-06-07 17:02 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +				IBaseExtension<?, ?> sourceExtension = getExcludedElements(resourceType, excludeElements, meta);
thanks!

2022-06-07 17:03 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	@NotNull
auto generated method, will change all occurrences

2022-06-07 17:03 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	}
done

2022-06-07 17:07 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		}
Not sure what you meant by this, it's used differently depending on if the updating resource is the current version or not.
How would I go about extracting it?

2022-06-07 17:07 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +
Thanks!

2022-06-07 17:07 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java
> +	private DaoMethodOutcome doUpdateWithHistoryRewrite(T theResource, RequestDetails theRequest, TransactionDetails theTransactionDetails) {
done

2022-06-07 17:08 UTC, StevenXLi commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4HistoryRewriteTest.java
> +
added check for table entry before and after

2022-06-07 17:08 UTC, StevenXLi commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/client/api/IGenericClient.java
> +	 * instance on the server
added

2022-06-12 21:34 UTC, jamesagnew requested changes

2022-06-12 21:34 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/gclient/IUpdateWithRewrite.java
> +public interface IUpdateWithRewrite {
Does this interface need to exist? Could you just have the `updateHistoryRewrite()` method just return `IUpdate`, and have two internal implementations of this interface?

Or potentially even better internally this could even just be a boolean "is this rewrite history" property on the existing internal implementation of IUpdate (UpdateInternal). That way all of the existing tests for the various flavours of update will apply also to the history rewrite too.

2022-06-12 21:34 UTC, jamesagnew commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/GenericClient.java
> +				myResource = parseResourceBody(myResourceBody);
Here's an example of where combining these (update and updateHistoryRewrite) into a single internal implementation would be great - You're getting warnings that much of this class isn't covered by unit test coverage, but that will all go away if you collapse it into a single implementation.

2022-06-12 21:34 UTC, jamesagnew commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_plain/rest_operations.md
> +```http
Presumably this example is no longer accurate after the most recent change

2022-06-12 21:34 UTC, jamesagnew commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4HistoryRewriteTest.java
> +public class FhirResourceDaoR4HistoryRewriteTest extends BaseJpaR4Test {
This test needs some additional beefing up IMO. Recommend adding test methods:

* Calling update with the header present on an ID that doesn't already exist should throw an exception
* Calling update with the header present on an ID that exists but a version that doesn't exist should throw an exception

Also, after any update call with the header present you should do a versionless read on the resource and make sure that the current version number has not changed. After any update call with the header not present you should do a versionless read and make sure that the version number has changed.

2022-06-12 21:34 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java
> +		if (theRequest == null || !"true".equals(theRequest.getHeader(JpaConstants.HEADER_REWRITE_HISTORY))) {
I'd recommend moving this check up a level, so that we decide whether to come into this method in the first place based on whether the header is present.

In other words:

* If the header is not present it's a normal update
* If the version is present in the URL and the header is present it's a rewrite history
* If the version is not present in the URL and the header is present it's an error
* If the ID or version are invalid it's an error

That logic preserves the current behaviour of ignoring the version if it's present in a normal update (ie where no header is present). This is perhaps suboptimal purely from a standards perspective, but I can guarantee there are lots of people depending on this behaviour currently and if we suddently change it to an error there will be urgent tickets filed..

2022-06-14 15:11 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java
> +		if (theRequest == null || !"true".equals(theRequest.getHeader(JpaConstants.HEADER_REWRITE_HISTORY))) {
updated

2022-06-14 15:12 UTC, StevenXLi commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_plain/rest_operations.md
> +```http
added the header requirements here

2022-06-14 15:13 UTC, StevenXLi commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/gclient/IUpdateWithRewrite.java
> +public interface IUpdateWithRewrite {
changed to using IUpdate, and added a property

2022-06-14 17:43 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		}
nvm figured it out

2022-06-15 13:44 UTC, jamesagnew approved these changes

2022-06-15 16:40 UTC, tadgh approved these changes

2022-06-15 16:40 UTC, merged