mdm clear move to batch2
hapifhir/hapi-fhir pull request #3671
Opened 2022-06-06 14:35 UTC by fil512

2022-06-24 18:09 UTC, TipzCM requested changes
minor stuff, but some of it i think should be fixed first

2022-06-24 18:09 UTC, TipzCM commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/pid/HomogeneousResourcePidList.java
> +			return myResourceType;
return getResourceType(); ? (nitpick)

2022-06-25 15:49 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderClearLinkR4Test.java
> +			// Expected exception
the assertion is that the patient is now gone.  the assertion's in two parts, the `fail()` and the ``catch`

2022-06-25 15:52 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/IMdmLinkSvc.java
> +	void deleteLinksWithAnyReferenceTo(List<ResourcePersistentId> thePersistentIds);
added javadoc.  you're right all interface methods should include javadoc

2022-06-25 15:53 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/config/Batch2Constants.java
> +	public static final Date BATCH_START_DATE = new InstantType("2000-01-01T00:00:00Z").getValue();
This date was hardcoded in the system before.  I pulled it out into a constant.  Added javadoc.

2022-06-25 16:37 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/jobs/chunk/ResourceIdListWorkChunkJson.java
> +		return myTypedPids.size();
Good call!

2022-06-25 16:46 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/jobs/step/IIdChunkProducer.java
> +	IResourcePidList fetchResourceIdsPage(Date theNextStart, Date theEnd, @Nonnull Integer thePageSize, @Nullable RequestPartitionId theRequestPartitionId, IT theData);
Excellent questions.  I have added plenty of javadoc.

2022-06-25 16:48 UTC, fil512 commented on hapi-fhir-storage-mdm/src/main/java/ca/uhn/fhir/mdm/batch2/MdmBatch2Config.java
> +		myJobDefinitionRegistry.addJobDefinition(jobDefinition);
if logs a warning message and skips the registration if it's already registered.

2022-06-25 16:49 UTC, fil512 commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/pid/HomogeneousResourcePidList.java
> +			return myResourceType;
I'm not accustomed to coding this way, but it does feel more polymorphic with the accessor.  Changed.

2022-06-25 22:54 UTC, tadgh approved these changes
Lgtm

2022-06-26 00:26 UTC, merged