add support for in and not-in qualifiers
hapifhir/hapi-fhir pull request #3680
Opened 2022-06-09 14:47 UTC by JasonRoberts-smile

https://github.com/hapifhir/hapi-fhir/issues/3620

2022-06-09 15:46 UTC, michaelabuckley commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +			Optional<IQueryParameterType> optionalParameter = theAndOrParams.stream().flatMap(List::stream).filter(param -> !supportedQualifier(theParamDef, param)).findAny();
Minor - you only need to check the head of each OR list.  Each OR-list has the same modifier.

2022-06-09 15:47 UTC, michaelabuckley commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +		InMemoryMatchResult checkUnsupportedResult = checkUnsupportedQualifiers(theParamName, paramDef, theAndOrParams);
Nice

2022-06-09 15:49 UTC, michaelabuckley commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +		if (!checkUnsupportedResult.supported()) {
Minor: I wonder if this would be cleaner as a single outer loop over the AND clauses.
Then each or-list is homogenous, and you do all these checks on the first element: type, modifier, chain, etc.

2022-06-09 15:51 UTC, michaelabuckley commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +		return theNextAnd.stream().anyMatch(token -> matchParam(theModelConfig, theResourceName, theParamName, paramDef, theSearchParams, token));
Very clear.

2022-06-09 15:54 UTC, michaelabuckley commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +					.noneMatch(t -> systemContainsCode(theQueryParam, t));
Nice.  This was a bug in JPA.  `:not` would match when there were multiple codes and one didn't match.  noneMatch is correct.

2022-06-13 12:30 UTC, tadgh approved these changes

2022-06-13 12:30 UTC, tadgh commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +	private boolean matchTokenParam(ModelConfig theModelConfig, String theResourceName, String theParamName, RuntimeSearchParam theParamDef, ResourceIndexedSearchParams theSearchParams, TokenParam theQu
Would love to see a small javadoc over this function explaining that we only support 2 qualifiers and not default tokens

2022-06-13 12:42 UTC, tadgh reviewed
un-approving as this is draft

2022-06-14 18:10 UTC, JasonRoberts-smile commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +			Optional<IQueryParameterType> optionalParameter = theAndOrParams.stream().flatMap(List::stream).filter(param -> !supportedQualifier(theParamDef, param)).findAny();
I agree that there is some redundancy in checking every parameter, but the lists aren't so very long, and the added complexity of ensuring that we only check the first entry in each list doesn't seem like a great trade-off to me.

2022-06-16 13:56 UTC, fil512 requested changes

2022-06-16 13:56 UTC, fil512 commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +				myValidationSupport = Optional.of(myApplicationContext.getBean(IValidationSupport.class));
This throws a `NoSuchBeanDefinitionException` if no bean of the given type was found

2022-06-16 13:56 UTC, fil512 commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +	private Optional<IValidationSupport> myValidationSupport = Optional.empty();
Rather than two flags, could we just use myValidationSupport being null as an indicator that it's not initialized yet?  Feels like a pretty common pattern...

2022-06-16 13:56 UTC, fil512 commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +			return false;
Oh I just read the code below.  If I'm reading it right this return false should never happen.  Maybe throw an IllegalStateException instead if this code can never be reached?

2022-06-16 13:56 UTC, fil512 commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +			return false;
or if you want to fail nice, at a minimum, log an error

2022-06-16 14:24 UTC, JasonRoberts-smile commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +	private Optional<IValidationSupport> myValidationSupport = Optional.empty();
IJ complains, and rightly so, if I try to set an Optional to null or perform a null-check. For the sake of clarity, I'll replace the boolean with a more explicit state variable.

2022-06-16 15:15 UTC, JasonRoberts-smile commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +				myValidationSupport = Optional.of(myApplicationContext.getBean(IValidationSupport.class));
I did not know that. Thank you for catching it.

2022-06-16 18:36 UTC, fil512 approved these changes

2022-06-16 18:36 UTC, fil512 commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/matcher/InMemoryResourceMatcher.java
> +	private IValidationSupport getValidationSupport() {
```suggestion
	private IValidationSupport getValidationSupportOrNull() {
```

2022-06-16 20:17 UTC, merged