3662 batch2 reduction step
hapifhir/hapi-fhir pull request #3681
Opened 2022-06-09 14:55 UTC by TipzCM

Changes:
* added support for a final reduction step on batch2 jobs
* added changelog

2022-06-09 20:33 UTC, fil512 requested changes

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.addColumn("20220601.1", "RECORD")
REPORT :-)

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/batch2/Batch2CoordinatorIT.java
> +		for (int i = 0; i < secondStepInt.get(); i++) {
This is a really great test.  Super clear and well written.

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * @param theInstanceId - job instance id
mongo isn't a think in hapi

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IReductionStepWorker.java
> +public interface IReductionStepWorker<PT extends IModelJson, IT extends IModelJson, OT extends IModelJson>
Javadoc

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/ReductionStepExecutionDetails.java
> +public class ReductionStepExecutionDetails<PT extends IModelJson, IT extends IModelJson, OT extends IModelJson>
Javadoc

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +			0, // what is sequence? Does it matter in reduction?
shouldn't matter.  I think this is for reporting only

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		calculator.calculateAndStoreInstanceProgress();
I'm worried this may collide with the scheduled maintenance task

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +				"Expected a single data sink for reduction step, but received {} instead. Only the first is accepted!",
```suggestion
				"Expected a single work chunk for reduction step, but received {} instead. Only the first is accepted!",
```

2022-06-09 20:33 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> +					@Nonnull String theInstanceId,
I would prefer the job data sink not know anything about its instanceid.  this is needed presumably in order to set the report on the final reduction step.  We should be able to do that in the maintenance service (which will have the instance id) instead of in the sink.

2022-06-10 13:31 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> +					@Nonnull String theInstanceId,
Perhaps this is an issue for a different bug then?

I didn't actually add the instanceId to the data sink - it was always there. I just reformatted the constructor for easier reading.

2022-06-10 16:00 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2JobInstanceEntity.java
> +	@Column(name = "RECORD", nullable = true, length = Integer.MAX_VALUE - 1)
updated

2022-06-10 16:00 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * Fetches all workchunks specified either by the list of ids (JPA) or by the instance ID (mongo)
updated

2022-06-10 16:00 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +			0, // what is sequence? Does it matter in reduction?
ok, i thought not. but nothing was clear in the code or documentation for it.

2022-06-10 16:01 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +				"Expected a single data sink for reduction step, but received {} instead. Only the first is accepted!",
updated

2022-06-10 16:01 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/ReductionStepExecutionDetails.java
> +public class ReductionStepExecutionDetails<PT extends IModelJson, IT extends IModelJson, OT extends IModelJson>
added

2022-06-10 16:02 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		calculator.calculateAndStoreInstanceProgress();
I've refactored the code about with this in mind.

Please re-review and let me know if this is better.

2022-06-10 17:34 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	List<WorkChunk> fetchWorkChunks(String theInstanceId, List<String> theChunkIds);
removed instance id

2022-06-10 18:13 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> +					@Nonnull String theInstanceId,
Oh my bad, I thought it was a new add

2022-06-10 19:38 UTC, fil512 requested changes

2022-06-10 19:38 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		BatchWorkChunk newWorkChunk = new BatchWorkChunk(
Issue: I don't understand why this extra work chunk exists.  Why wouldn't the final step simply just work on all the chunks directly.

I assumed the way this would work is in the maintenance service for gated jobs, when we detect all the chunks for the penultimate step were done, we'd send them to the defined reducer method to produce the final report and then save the report there...

2022-06-10 19:38 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +public class JobStepExecutorSvc {
Having a class named `JobStepExecutor` and `JobStepExecutorSvc` feels confusing to me.  can we rename one of them?

2022-06-10 19:38 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +public class ReductionStepDataSink<PT extends IModelJson, IT extends IModelJson, OT extends IModelJson>
per issue above, I believe this class can be removed

2022-06-10 19:38 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobInstance.java
> +	public String getRecord() {
Report

2022-06-10 19:38 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				// do execution of the final step now
Issue: I expected to see something like this here (this is pseudo-code.  presumably there would be generic-typed services that do this work)

```
reductionStep = myInstance.getJobReductionStep();
report = reductionStep.produceReport(myProgressAccumulator.getWorkChunks());
instance.setReport(report);
save(instance);
```

2022-06-10 20:17 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +		Iterable<Batch2WorkChunkEntity> entities = myWorkChunkRepository.findAllById(theChunkIds);
refactored to fetch 100 at a time, just in case.

2022-06-10 20:17 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +		retVal.setRecord(theEntity.getReport());
updated

2022-06-10 20:25 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +	@Query("UPDATE Batch2WorkChunkEntity e SET e.myStatus = :status, e.myEndTime = :et, e.mySerializedData = null WHERE e.myId IN(:ids)")
updated it to do it in smaller chunks

2022-06-10 20:25 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +		// add new RECORD column to BATCH2 tables
updated

2022-06-10 20:27 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +	private void fetchChunks(String theInstanceId, boolean theIncludeData, int thePageSize, int thePageIndex, IChunkProcessor theProcessor) {
done

2022-06-10 20:27 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	interface IChunkProcessor {
removed

2022-06-10 20:28 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IReductionStepWorker.java
> + * @param <OT> Output Parameter Type
done

2022-06-10 20:29 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorOutput.java
> +	private final boolean myIsSuccessful;
done

2022-06-10 20:29 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorOutput.java
> +		myIsSuccessful = theIsSuccessful;
I always prefer to return objects for exactly this reason: extensibility.

2022-06-10 20:30 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		boolean succeed = executeStep(stepExecutionDetails,
done

2022-06-10 20:31 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		if (theCursor.getCurrentStep().isReductionStep()) {
done

2022-06-10 20:39 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +		BatchWorkChunk newWorkChunk = new BatchWorkChunk(
I'll remove the extra workchunk object

2022-06-10 20:40 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutorSvc.java
> +public class JobStepExecutorSvc {
will rename this class

2022-06-10 20:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +public class ReductionStepDataSink<PT extends IModelJson, IT extends IModelJson, OT extends IModelJson>
As per our discussion, i'veleft this class in so as to reuse as much logic as possible.

2022-06-10 20:42 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				// do execution of the final step now
As per our discussion, left in new execution service

2022-06-15 18:41 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/ArrayUtil.java
> +	public static <T> List<List<T>> subdivideListIntoListOfLists(List<T> theInput, int theSize) {
done

2022-06-15 20:12 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutionSvc.java
> +		List<WorkChunk> chunks = myJobPersistence.fetchAllWorkChunks(theInstance.getInstanceId(), true);
Replaced with iterator

2022-06-15 20:12 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/JobInstanceProgressCalculator.java
> +		List<WorkChunk> chunks = myJobPersistence.fetchAllWorkChunks(myInstance.getInstanceId(), false);
replaced with iterator

2022-06-15 21:44 UTC, fil512 requested changes

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutor.java
> +		JobStepExecutorOutput<PT, IT, OT> successOutput = myJobExecutorSvc.doExecution(
nitpick: I'd call this variable stepExecutorOutput

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobStepExecutor.java
> -		BaseDataSink<PT,IT,OT> dataSink;
Nice encapsulation

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +		if (count == 0) {
this looks nice and clean.

I'm curious about the role of myCounter.  This batch system is by design multi-process, and the scope of myCounter is only to this particular stack.  If you're worried about multiple reductions maybe instead of using an in-stack field to track it, you should use the database.  I.e. throw an exception if instance.getReport() is not null before setting it.

If you want to avoid the race condition you could go to town by adding a fetchInstanceForUpdate method that does a `@Lock(LockModeType.PESSIMISTIC_READ)`

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutionSvc.java
> +		IReductionStepWorker<PT, IT, OT> theWorker = (IReductionStepWorker<PT, IT, OT>) theStep.getJobStepWorker();
issue: I know you're keen to merge this, but this cast just seems really strange.  If theWorker is in fact a worker that complies with the IJobStepWorker interface, then I would expect to run it, passing in step execution details and a data sink.  But instead, we're ignoring the run method completely and calling addChunk on it, which is something we do with data sinks.  Something feels broken with the modelling here.  I recommend collaborating with Buckley or me to align the model with the current design.

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IReductionStepWorker.java
> +	void addChunk(WorkChunk theChunk, Class<IT> theInputType);
Shouldn't this be called `accept()` since it functions like a special kind of data sink?

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				}
suggestion: extract to method

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobDefinition.java
> +		public <OT extends IModelJson> Builder<PT, OT> addLastReducerStep(String theStepId, String theStepDescription, Class<OT> theOutputType, IReductionStepWorker<PT, NIT, OT> theStepWorker) {
suggestion: `addFinalReducerStep` ?

2022-06-15 21:44 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/JobInstanceProgressCalculator.java
> +		while (workChunkIterator.hasNext()) {
nice improvement!

2022-06-16 13:34 UTC, fil512 commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IReductionStepWorker.java
> +	void addChunk(WorkChunk theChunk, Class<IT> theInputType);
Here is a change to the API that feels more consistent with the existing API:

remove the IReductionStepWorke.addChunk`  method and instead when we call run() on it, the step execution details we pass into it contains the workchunk iterator as the data. We could have a subclass of StepExecutionDetails called ReductionStepExecutionDetails that makes it explicit how it works (i.e. defines the type of the data as a work chunk iterator)

2022-06-16 14:06 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/BaseDataSink.java
> +		return myJobDefinitionId;
i set the value using the job definition instead.

2022-06-16 14:16 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepDataSink.java
> +		if (count == 0) {
i'm not sure i understand the last point, but i'll log if it's not null (michael had suggested last in wins so maybe i'll just switch tothat instead of first in wins)

2022-06-16 14:18 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutionSvc.java
> +		IReductionStepWorker<PT, IT, OT> theWorker = (IReductionStepWorker<PT, IT, OT>) theStep.getJobStepWorker();
renamed

2022-06-16 14:31 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobDefinition.java
> +		public <OT extends IModelJson> Builder<PT, OT> addLastReducerStep(String theStepId, String theStepDescription, Class<OT> theOutputType, IReductionStepWorker<PT, NIT, OT> theStepWorker) {
done

2022-06-16 14:32 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/BaseDataSink.java
> +		return myJobDefinitionId;
I just reassigned variable in constructor instead.

2022-06-20 18:59 UTC, merged