3719 enable map response terminology for bulk export
hapifhir/hapi-fhir pull request #3735
Opened 2022-06-23 16:09 UTC by StevenXLi

- Refactored out the logic for mapping codes in `ResponseTerminologyTranslationInterceptor` into a service called `ResponseTerminologyTranslationSvc`
- added logic in the write to file step of bulk export to call the `ResponseTerminologyTranslationSvc` to map the codes before export, in the file `BaseResourceToFileWriter`

2022-06-27 15:59 UTC, tadgh requested changes

2022-06-27 15:59 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/JpaConfig.java
> +	}
Qustion: Have you tried to build this locally and ensured CDR does not break? Or at least checked the repo for instances of the interceptor to ensure it is only instantiated here in HAPI? Should be safe, but should also check.

2022-06-27 15:59 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationInterceptor.java
> +	private final Map<String, String> myMappingSpecifications = new HashMap<>();
design issue: It feels very strange to me that the interceptor still retains these mappings. Why does the interceptor need to know about them?

2022-06-27 15:59 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public ResponseTerminologyTranslationSvc(ResponseTerminologyTranslationInterceptor theMyResponseTerminologyTranslationInterceptor) {
Issue: This service should need to know precisely nothing about the Interceptor. I see that you are using it internally to yank out context and mappings. I think a better design is to have this service accept the mappings and the FhirContext directly. This class ideally knows nothing about its related interceptors.

2022-06-27 15:59 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public void processResourcesForTerminologyTranslation(List<IBaseResource> resources) {
Design: This method should read: `processResourcesForTerminilogyTranslationWithMappings(List<IBaseREsource> theResources, Map theMappings){}` And you can pass the mappings down to the model visitor. This will remove the need for you to know about the interceptor in this code.

2022-06-27 15:59 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public void processResourcesForTerminologyTranslation(List<IBaseResource> resources) {
Alternatively, change the `addMapping()` so that it lives in the translator SVC instead, and that way it will easily apply to both locations.

2022-06-27 16:18 UTC, StevenXLi commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationInterceptor.java
> +	private final Map<String, String> myMappingSpecifications = new HashMap<>();
I've tested the version with the mappings fully moved to the service. It didn't work as expected in the bulk export service call.
I think the issue is that after the service and the interceptor is created and autowired in the config, when trying to set the mapping with `addMappingSpecification` call in the interceptor somewhere in the code, the same service doesn't get updated with the new mappings

2022-06-27 16:29 UTC, StevenXLi commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public ResponseTerminologyTranslationSvc(ResponseTerminologyTranslationInterceptor theMyResponseTerminologyTranslationInterceptor) {
see: https://github.com/hapifhir/hapi-fhir/pull/3735#discussion_r907566323

2022-06-27 16:29 UTC, StevenXLi commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public void processResourcesForTerminologyTranslation(List<IBaseResource> resources) {
see: https://github.com/hapifhir/hapi-fhir/pull/3735#discussion_r907566323

2022-06-27 16:37 UTC, StevenXLi commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseTerminologyTranslationSvc.java
> +	public ResponseTerminologyTranslationSvc(ResponseTerminologyTranslationInterceptor theMyResponseTerminologyTranslationInterceptor) {
I've also tried without passing in the interceptor, passing in only the `IValidationSupport`, the same issue as the other comment happens

2022-06-27 17:20 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/JpaConfig.java
> +	}
I have built this locally, but haven't ran all the tests.
The only place outside of HAPI where this interceptor is used is when this setting: https://smilecdr.com/docs/configuration_categories/fhir_endpoint_terminology.html#property-response-mapping
is enabled

2022-06-28 17:36 UTC, StevenXLi commented
The mapping specification will be removed from `ResponseTerminologyTranslationInterceptor` once the cdr side has been changed to use the new service as a way to set the mappings in terminology translation.

This way cdr will not break during this code change

2022-06-28 18:32 UTC, tadgh approved these changes
Approved pending changelog change

2022-07-12 16:24 UTC, merged