3776 add https support for hapi fhir cli using tls
hapifhir/hapi-fhir pull request #3777
Opened 2022-07-10 21:00 UTC by nathandoef

2022-07-18 14:19 UTC, StevenXLi requested changes

2022-07-18 14:19 UTC, StevenXLi commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +	public static X509TrustManager createTrustManager(Optional<TrustStoreInfo> theTrustStoreInfo) {
missing test case, trustManagerFactory returning no instants of `X509TrustManager` based on `theTrustStoreInfo ` input

2022-07-18 14:19 UTC, StevenXLi commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/apache/ApacheRestfulClientFactory.java
> +			if(optionalSslContext.isPresent()){
This newly added condition doesn't seem to be tested in `ApacheRestfulClientFactoryTest`

2022-07-18 17:30 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/tls/TrustStoreInfo.java
> +public class TrustStoreInfo extends StoreInfo{
This class is basically a concrete class to differentiate between a KeyStore and a TrustStore. There are a lot of fields shared between KeyStore and TrustStore which is why I made a StoreInfo superclass. Any suggestions on ways to change this?

2022-07-18 17:38 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BaseRequestGeneratingCommand.java
> +			String theBasicAuthOptionName, String theBearerTokenOptionName, String theTlsAuthOptionName) throws ParseException {
`theTlsAuthOptionName` is optional and follows similar logic as the old function. `theBasicAuthOptionName`, `theBearerTokenOptionName` and  `theTlsAuthOptionName` are not required, but are passed in and used if they are present.

2022-07-18 17:43 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +	public static X509TrustManager createTrustManager(Optional<TrustStoreInfo> theTrustStoreInfo) {
Added test case here: https://github.com/hapifhir/hapi-fhir/pull/3777/commits/63282ca37769840d4bd3b209f30fededff3bb3d4#diff-2cf2bcae7608be69d6c2bad5c26cc1e7673c828dbb8df8406aee05bb8f864663

2022-07-18 18:03 UTC, StevenXLi commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/tls/TrustStoreInfo.java
> +public class TrustStoreInfo extends StoreInfo{
My suggestion would be to extend Keystoreinfo off of Truststoreinfo, and have the current StoreInfo be renamed to Truststoreinfo

2022-07-18 18:15 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/apache/ApacheRestfulClientFactory.java
> +			if(optionalSslContext.isPresent()){
I just set a break point inside `TlsAuthenticationSvc` where the SSLContext logic is happening and it is being hit when I run `ApacheNativeClientTest` and for tests inside `hapi-fhir-cli-api`

2022-07-18 18:29 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/tls/TrustStoreInfo.java
> +public class TrustStoreInfo extends StoreInfo{
I agree that's it's a bit strange that TrustStore only calls the constructor, but I think it might be better to leave it for readability. For example inside the method:

`TlsAuthenticationSvc#createKeyStore(StoreInfo theStoreInfo){ ... } `

I think it would be strange to pass in a TrustStoreInfo object. The java.security.KeyStore api can accommodate both keystores and truststores so I think using a generic name like StoreInfo will communicate that a little clearer.

2022-07-18 19:32 UTC, fil512 requested changes

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/ImportCsvToConceptMapCommandR4Test.java
> +		myRestServerR4Helper.clearDataAndCounts();
this should be in the helper's afterEach so it's automatically called

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/UploadTerminologyCommandTest.java
> +			Arguments.arguments(FHIR_VERSION_DSTU3, true),
very nice

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/client/ApacheNativeClientTest.java
> +		assertDoesNotThrow(() -> {
there is no need to wrap in assertDoesNotThrow

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-client-okhttp/src/test/java/ca/uhn/fhir/okhttp/OkHttpRestfulClientFactoryTest.java
> +		assertThrows(SSLHandshakeException.class, () -> {
do not use assertThrows.  Use the try fail() pattern instead.  (I questioned this initially, but have since learned it is the best pattern.)

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +			throw new TlsAuthenticationException(Msg.code(2104)+"Could not find TrustManager");
Maybe be more specific with "could not find X509 Trust Manager"

2022-07-18 19:32 UTC, fil512 commented on hapi-fhir-client/src/test/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvcTest.java
> +		Exception exceptionThrown = assertThrows(TlsAuthenticationSvc.TlsAuthenticationException.class, () -> {
search all the assertThrows and replace with the try fail() pattern please :-)

2022-07-18 19:46 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java
> +	 * without incurring any performance penalty
Hmm, I think you might be right. The method I added was an overloaded method for `newRestfulGenericClient(final String theServerBase)` and used the same JavaDoc. Do you want me to remove the performance note for both?

2022-07-18 20:02 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/tls/StoreInfo.java
> +	private final char[] myStorePass;
Tried to keep it consistent with the [java.security.KeyStore](https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html) api

2022-07-19 14:41 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/client/api/IRestfulClientFactory.java
> +	IHttpClient getHttpClient(StringBuilder theUrl, Optional<TlsAuthentication> theTlsAuthentication, Map<String, List<String>> theIfNoneExistParams, String theIfNoneExistString, RequestTypeEnum theRequ
Fixed

2022-07-19 14:42 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/client/api/IRestfulClientFactory.java
> +	IGenericClient newGenericClient(String theServerBase, Optional<TlsAuthentication> theTlsAuthentication);
Fixed

2022-07-19 14:48 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BaseCommand.java
> +			if(keyStoreInfo.isEmpty() && trustStoreInfo.isEmpty()){
I think || is correct here because there is the possibility that the server just has server authentication and no client authentication

2022-07-19 14:56 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/ImportCsvToConceptMapCommandR4Test.java
> +		myRestServerR4Helper.clearDataAndCounts();
Fixed

2022-07-19 14:56 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/ca/uhn/fhir/cli/UploadTerminologyCommandTest.java
> +	public void testDeltaAddInvalidFileType(String theFhirVersion, boolean theIncludeTls) throws IOException {
Thanks!

2022-07-19 14:56 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/client/ApacheNativeClientTest.java
> +		assertDoesNotThrow(() -> {
Fixed

2022-07-19 15:01 UTC, nathandoef commented on hapi-fhir-cli/hapi-fhir-cli-api/src/test/java/client/ApacheNativeClientTest.java
> +			HttpUriRequest request = new HttpGet(fhirVersionParams.getSecuredPatientEndpoint());
`BaseFhirVersionParameterizedTest` uses the new HTTPS functionality inside `BaseRestServerHelper` to connect to a HTTP endpoint (`getPatientEndpoint()`) or an HTTPS endpoint (`getSecuredPatientEndpoint()`) depending on how the test is parameterized.

2022-07-19 15:01 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +	public static Optional<SSLContext> createSslContext(Optional<TlsAuthentication> theTlsAuthentication){
Fixed

2022-07-19 15:03 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +		if(theTlsAuthentication.isEmpty()){
Fixed

2022-07-19 15:03 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvc.java
> +			throw new TlsAuthenticationException(Msg.code(2104)+"Could not find TrustManager");
Fixed

2022-07-19 15:03 UTC, nathandoef commented on hapi-fhir-client/src/test/java/ca/uhn/fhir/rest/client/tls/TlsAuthenticationSvcTest.java
> +		Exception exceptionThrown = assertThrows(TlsAuthenticationSvc.TlsAuthenticationException.class, () -> {
Removed all occurrences of assertThrows()

2022-07-19 15:04 UTC, nathandoef commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerDstu3Helper.java
> +		stop();
Fixed

2022-07-19 15:05 UTC, nathandoef commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/TlsAuthenticationTestUtil.java
> +public class TlsAuthenticationTestUtil implements AfterEachCallback {
Went with `TlsAuthenticationTestHelper` since this class is used a lot with `BaseRestServerHelper` and it's subclasses

2022-07-19 18:15 UTC, fil512 commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java
> +	 * without incurring any performance penalty
I'd leave it in only if it's true.  You should be able to whip up a quick test to find out.

2022-07-19 19:18 UTC, fil512 requested changes

2022-07-19 19:18 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BaseCommand.java
> +			if(keyStoreInfo.isEmpty() && trustStoreInfo.isEmpty()){
It looks like you still have &&

2022-07-19 19:18 UTC, fil512 commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/apache/ApacheRestfulClientFactory.java
> +	public synchronized IHttpClient newHttpsClient(StringBuilder theUrl, TlsAuthentication theTlsAuthentication,
These two methods look too similar.  I'm worried it will lead to errors.  Maybe instead call this one
`newTlsHttpsClient`

2022-07-19 19:18 UTC, fil512 commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/RestfulClientFactory.java
> +	public synchronized IGenericClient newHttpGenericClient(String theServerBase) {
serious issue: This method cannot be renamed.  It's used thousands of places.

2022-07-19 19:18 UTC, fil512 commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/RestfulClientFactory.java
> +	public synchronized IGenericClient newHttpsGenericClient(String theServerBase, TlsAuthentication theTlsAuthentication) {
maybe `newTlsGenericClient` ?

2022-07-19 19:18 UTC, fil512 commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/method/BaseHttpClientInvocationWithContents.java
> +		IHttpClient httpClient = getRestfulClientFactory().newHttpClient(url, myIfNoneExistParams, myIfNoneExistString, getRequestType(), getHeaders());
oh I didn't realize that this method already existed.  We can't change the name if it was already called getHttpClient()

2022-07-19 21:08 UTC, nathandoef commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java
> +	 * without incurring any performance penalty
Updated the JavaDocs on both methods to indicate the additional GET request to /metadata

2022-07-19 21:12 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/apache/ApacheRestfulClientFactory.java
> +	public synchronized IHttpClient newHttpsClient(StringBuilder theUrl, TlsAuthentication theTlsAuthentication,
Renamed to `getTlsHttpsClient()` since `newHttpClient()` had to be changed back to `getHttpClient()`

2022-07-19 21:12 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/RestfulClientFactory.java
> +	public synchronized IGenericClient newHttpGenericClient(String theServerBase) {
Fixed

2022-07-19 21:13 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/RestfulClientFactory.java
> +	public synchronized IGenericClient newHttpsGenericClient(String theServerBase, TlsAuthentication theTlsAuthentication) {
Fixed

2022-07-19 21:13 UTC, nathandoef commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/method/BaseHttpClientInvocationWithContents.java
> +		IHttpClient httpClient = getRestfulClientFactory().newHttpClient(url, myIfNoneExistParams, myIfNoneExistString, getRequestType(), getHeaders());
Fixed

2022-07-20 14:27 UTC, fil512 approved these changes

2022-08-02 13:27 UTC, StevenXLi approved these changes

2022-08-02 13:27 UTC, merged