3792 providing capability to alter source resource content before mdm matching
hapifhir/hapi-fhir pull request #3802
Opened 2022-07-18 13:01 UTC by epeartree

2022-07-18 15:38 UTC, tadgh requested changes
Overall looks good, but since this is a potentially risky operation, I would feel safer if we saw a few more things: 
1. A test which shows that changes made to the resource via the interceptor _are not persisted_. 
2. Documentation indicating the same (can be added to the hook's documentation). 
3. Documentation on the hook indicating its actual purpose (e.g. resource pseudo-modification for MDM purposes, in case you want to skip various elements). 
4. An actual callout in the real MDM documentation about when you might want to do this, and an example of how (for example, ignoring MDM on SSNs if we detect a dummy SSN).

2022-07-18 15:38 UTC, tadgh commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> -	}
Question: Why was this helper method removed? It appears as though the logic was extracted from it and just placed where this method used to be called

2022-07-18 15:38 UTC, tadgh commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmPreProcessingInterceptorIT.java
> +}
issue (non-blocking) : seems a bit heavyweight to do a full IT to effectively check "did an interceptor get called". Is there any way this could be reworked with just mocks on the mesage handler? If not, that's fine as well

2022-07-18 17:44 UTC, epeartree commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmPreProcessingInterceptorIT.java
> +}
yes, mocking could be used but it would not guaranty that all the pieces fit together.  the goal of this IT is to test that:
- the interceptor can indeed see and act on the new pointcut;
- that the pointcut implementation is provided the correct parameter (as per Ken's recommendation);

it can easily be reworked.

2022-07-25 15:31 UTC, fil512 approved these changes

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java
> +	 * modification of the resource elements to influence the MDM linking process.  Any modification to the resource are not persisted.
```suggestion
	 * modification of the resource elements to influence the MDM linking process.  Any modifications to the resource are not persisted.
```

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +MDM supports a pointcut invocation right before it starts matching an incoming source resource against defined rules.  A possible use of the pointcut would be to alter a resource property(ies) with t
```suggestion
MDM supports a pointcut invocation right before it starts matching an incoming source resource against defined rules.  A possible use of the pointcut would be to alter a resource content with the intention of influencing the MDM matching and linking process.  Any modifications to the source resource are NOT persisted to the database.  Modifications performed within the pointcut will remain valid during MDM processing only.
```

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +MDM supports a pointcut invocation right before it starts matching an incoming source resource against defined rules.  A possible use of the pointcut would be to alter a resource property(ies) with t
hapi-fhir does not have modules

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +{{snippet:file:hapi-fhir/hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/PatientNameModifierMdmPreProcessingInterceptor.java}}
snippets FTW!

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +This section describes customization supported by MDM.
Fantastic to see our documentation improved like this!!!  Excellent initiative!

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> +			theSourceResource = Objects.requireNonNullElse(interceptedSourceResource, theSourceResource);
I would have expected the source resource parameter contents to be modified (like how we allow pointcuts to modify user details that are passed in).  I would expect a void return value here.

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> +			theSourceResource = Objects.requireNonNullElse(interceptedSourceResource, theSourceResource);
If there needs to be defensive copying, then it can happen before the pointcut call.  But I believe the resource has allready been serdesered in the channel, so there should not be a need to defensive copy (we should never rely on a customer making the defensive copy themselves)

2022-07-25 15:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> +	private MdmLinkEvent getLinkChangeEvent(MdmTransactionContext theMdmContext) {
I'd call this `buildLinkChangeEvent` so it's not confused with an accessor

2022-07-26 10:47 UTC, epeartree commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +MDM supports a pointcut invocation right before it starts matching an incoming source resource against defined rules.  A possible use of the pointcut would be to alter a resource property(ies) with t
done

2022-07-26 10:54 UTC, epeartree commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +This section describes customization supported by MDM.
All the praise and credit should go to GG.  He told me where to put it and what he wanted.

2022-07-26 11:57 UTC, epeartree commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> +			theSourceResource = Objects.requireNonNullElse(interceptedSourceResource, theSourceResource);
U'r right.  i'll remove the return value

2022-07-26 12:02 UTC, epeartree commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/broker/MdmMessageHandler.java
> +	private MdmLinkEvent getLinkChangeEvent(MdmTransactionContext theMdmContext) {
changed.

2022-07-26 19:40 UTC, tadgh approved these changes

2022-07-26 19:40 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_customizations.md
> +## MDM Preprocessing Pointcut
Ideally indicate which pointcut it is : `MDM_BEFORE_RESOURCE_CHECKED` or something like that.

edit: Ah I see you mention it below, disregard this.

2022-07-26 19:40 UTC, tadgh commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/PatientNameModifierMdmPreProcessingInterceptor.java
> +	String myNewValue = EMPTY;
I don't know how much i like using the Stringutils.EMPTY here....I think this example would be clearer if you were to remove the human name elements that were offending. This example also only replaces the family name, not the given names. I think the clearest example would be one where it removes any human name elements if they match "john doe"

2022-07-27 11:29 UTC, epeartree commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/PatientNameModifierMdmPreProcessingInterceptor.java
> +	String myNewValue = EMPTY;
Done.  Clearing the entire name.  Test also modified to fit the new interceptor implementation.

2022-07-27 12:46 UTC, merged