Make sure that direct resource load path is only executed for synchro…
hapifhir/hapi-fhir pull request #3833
Opened 2022-07-21 20:45 UTC by jmarchionatto

…nous searches

2022-07-21 21:04 UTC, michaelabuckley requested changes
Looks ok, but I'd like to consolidate the logic.

Have your verified that we produce next links on the non-offset path?

2022-07-21 21:04 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java
>  		if (theParams.isLoadSynchronous() || loadSynchronousUpTo != null || isOffsetQuery) {
Please move this line inside the strategy calculation.  That's the whole point of the strategy factory -- avoiding the boolean checks being distributed over the entire trace.

2022-07-21 21:16 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java
>  		if (theParams.isLoadSynchronous() || loadSynchronousUpTo != null || isOffsetQuery) {
I don't understand your ask, as we still want to have a path for not-direct synchronous query, so the check would be duplicated unless we left it outside of the strategy.

2022-08-04 19:30 UTC, michaelabuckley approved these changes

2022-08-04 19:38 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java
>  		if (theParams.isLoadSynchronous() || loadSynchronousUpTo != null || isOffsetQuery) {
We agreed on look into this change by deepening the scope of strategy sometime later

2022-08-04 22:19 UTC, merged