Fixed the issue
hapifhir/hapi-fhir pull request #3845
Opened 2022-07-25 13:19 UTC by Qingyixia

#3837

2022-07-25 13:46 UTC, jmarchionatto approved these changes

2022-08-04 16:30 UTC, tadgh requested changes

2022-08-04 16:30 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_1_0/3837-fix-query-to-include-substances.yaml
> +title: "Fix the query to include substances."
Issue: Changelog requires much more description. Somebody reading this changelog has no idea what was fixed. Which query, which class of queries, what was fixed? It looks like the meat of the MR is a correction to _includes behaviour, so maybe talk about that.

2022-08-04 19:26 UTC, Qingyixia commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_1_0/3837-fix-query-to-include-substances.yaml
> +title: "Fix the query to include substances."
Fixed

2022-08-04 19:33 UTC, tadgh approved these changes

2022-08-08 17:33 UTC, merged