Fix to the issue
hapifhir/hapi-fhir pull request #3855
Opened 2022-07-27 20:44 UTC by Qingyixia

#3854

2022-08-11 14:37 UTC, StevenXLi requested changes

2022-08-11 14:37 UTC, StevenXLi commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +	private boolean UploadingIsEndNow(String url, IGenericClient client) {
Suggestion: the name of the method can be a little more intention revealing. It should say something like checkJobComplete or similar.
Also method names should begin with a lowercase letter.

2022-08-11 14:37 UTC, StevenXLi commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		return uploadingEnded;
Suggestion: this can be simplified to just return the `diagnostics.equals("Job is complete.")` part

2022-08-11 14:37 UTC, StevenXLi commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		Object resource = response.getResource();
Nitpick: You can just inline this variable

2022-08-11 14:51 UTC, Qingyixia commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		Object resource = response.getResource();
Changes have been made according to the suggestions. Thank you!

2022-08-12 00:33 UTC, fil512 requested changes

2022-08-12 00:33 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		String diagnostics = ((OperationOutcome) response.getResource()).getIssue().get(0).getDiagnostics();
you need some null checks and size checks here to avoid a NullPointerException or an ArrayIndexException

2022-08-12 00:33 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		return diagnostics.equals("Job is complete.");
Instead of checking the string, use the response code.  I.e. 200.

See `BulkDataImportProvider.importPollStatus()` for the list of status codes.  Any code except 202 should end the loop.  If there is a 500, you should `ourLog.error()` the error message

2022-08-12 18:37 UTC, Qingyixia commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		String diagnostics = ((OperationOutcome) response.getResource()).getIssue().get(0).getDiagnostics();
Changes are made according to the suggestion.

2022-08-12 18:37 UTC, Qingyixia commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +		return diagnostics.equals("Job is complete.");
Changes are made according to the suggestion.

2022-08-12 19:33 UTC, fil512 approved these changes

2022-08-12 19:33 UTC, fil512 commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +			} else {
maybe confirm it is 202 and if it is not 202 and not 200 also end the loop with an "unexpected response status code".

2022-08-12 19:55 UTC, StevenXLi approved these changes

2022-08-13 00:07 UTC, tadgh commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/BulkImportCommand.java
> +			} else {
Deferred to https://github.com/hapifhir/hapi-fhir/issues/3914

2022-08-13 00:07 UTC, merged