fix-matchers-not-contains-in-asserts
hapifhir/hapi-fhir pull request #3913
Opened 2022-08-12 19:37 UTC by jdar8

2022-09-01 16:33 UTC, jmarchionatto requested changes

2022-09-01 16:33 UTC, jmarchionatto commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/CustomMatchersUtil.java
> +	public static <T> void assertDoesNotContainAllOf(List<T> theActual, List<T> theShouldNotContain) {
issue: The method name does not match the comment. Assuming that the comment is the correct part, `assertDoesNotContainAllOf` implies that it could still contain one or more, as far as is not all of them.
suggestion: I think `assertDoesDoesNotContainAnyOf` matches the purpose better

2022-09-01 16:33 UTC, jmarchionatto commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	//FIXME: remove
issue: Is this a miss?

2022-09-01 19:25 UTC, jdar8 commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	//FIXME: remove
Oops, yes this was my test to make sure that the matchers usage was actually incorrect.

2022-09-21 11:49 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	//FIXME: remove
fix me removed

2022-09-21 15:53 UTC, jmarchionatto approved these changes

2022-09-21 15:54 UTC, merged