3929 batch2 jobs file fetching step strict policy for response header content type
hapifhir/hapi-fhir pull request #3945
Opened 2022-08-23 13:02 UTC by MykolaMedynskyiSCDR

2022-08-24 15:52 UTC, epeartree requested changes

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/BulkImportFileServlet.java
> +	public void setHeaderContentType(String theHeaderContentType) {
we'll move this to a test class so it can be removed from here.

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStep.java
> +			|| contentType.equals(Constants.CT_FHIR_JSON)
it is always better to call .equals() on a string for which u are 100% sure that a value exists:
`Constants.CT_FHIR_JSON.equals( theContentType );`

with the above construction, u avoid a NPE.
please change all 4.

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStep.java
> +	private boolean isValidContentType(String contentType) {
all method parameters start with 'the'

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/BulkImportFileServletTest.java
> +	@ParameterizedTest
Let's completely remove this test, we no longer need it.

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStepTest.java
private final ContentTypeHeaderModifiableBulkImportFileServlet myBulkImportFileServlet = new ContentTypeHeaderModifiableBulkImportFileServlet();

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStepTest.java
at the end of the class but within the class:
```
public static class ContentTypeHeaderModifiableBulkImportFileServlet extends BulkImportFileServlet{

		public String myContentTypeValue;


		public void setHeaderContentTypeValue(String theContentTypeValue) {
			myContentTypeValue = theContentTypeValue;
		}

		@Override
		public String getHeaderContentType() {
			return Objects.nonNull(myContentTypeValue) ? myContentTypeValue : super.getHeaderContentType();
		}
	}
```

2022-08-24 15:52 UTC, epeartree commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStepTest.java
i did not like my original solution where i modified class BulkImportFileServlet.  class should be closed for modification and open for extension.

2022-09-12 16:00 UTC, tadgh reviewed
Overall, looks good, but I want to ensure that you've actually covered the  original issue. 

It appears as though you've added support for not failing out on other content-types, but no actual support for _consuming_  other content-types. For example, in FetchFilesStep.java, you will notice that the processing (occurring in line 95 and onward), is still processing it as though it is NDJSON. If the client server supplies a bundle, or something similar (e.g. application/fhir+json), then the fetch files step will fail during parsing as it is not NDJSON content.

Are you sure the content you'll be receiving is in fact NDJSON?

2022-09-12 16:02 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStep.java
> +					Validate.isTrue(isValidContentType(contentType), "Received non-NDJSON content type \"%s\" from URL: %s", contentType, nextUrl);
issue(blocking): This validation message is no longer accurate, it should be updated to reflect the reality of the updated concent-types. 

Furthermore, you should _definitely_ add an INFO log message if we receive a content-type of anything other than NDJSON, and indicate that we will try to process it, but it may not complete correctly if the actual data is not NDJSON

2022-09-12 16:03 UTC, tadgh approved these changes

2022-09-13 13:51 UTC, MykolaMedynskyiSCDR commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/BulkImportFileServletTest.java
>  		}
I don't see where else I can use it. Maybe I am missing something.

2022-09-21 11:02 UTC, epeartree approved these changes

2022-09-21 15:29 UTC, merged