3960 when creating a resource patient where patientmetasource is provided with a hash the hash value is overwritten
hapifhir/hapi-fhir pull request #3965
Opened 2022-08-29 15:55 UTC by MykolaMedynskyiSCDR

What was done:
-Meta source id is not replaced if provided.
-Added new test to check source id replacement.
-Added change log.

2022-09-08 18:09 UTC, epeartree commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/DaoConfig.java
> +	 * Default is false.
This is good.  Still, i think we could provide further clarifications like "Default is false ie. a client provided requestId will be overwritten."

2022-09-08 18:11 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	@Autowired
Please remove the historyProvenanceDao as it is no longer needed.

2022-09-08 18:12 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void createResource_withPreserveRequestIdEnabled_RequestIdIsPreserved(){
Please lower case my mistake (RequestIdIsPreserved to requestIdIsPrserved)

2022-09-08 18:14 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void createResource_withPreserveRequestIdDisabled_RequestIdIsOverwritten(){
this test and the one above can be combined with the use of a @MethodSource but it's no big deal at all.

2022-09-08 18:17 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void searchResource_bySourceAndCustomRequestIdWithPreserveRequestIdDisabled_fails(){
please remove 'Custom'

2022-09-08 18:22 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +	public void searchResource_bySourceAndWrongCustomRequestIdWithPreserveRequestIdEnabled_fails() {
remove 'custom'

2022-09-08 18:25 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
>  			MetaUtil.setSource(myContext, retVal, sourceString);
please add breathing lines before and after MetaUtil.setSource

2022-09-08 18:27 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		String requestId = getRequestId(theRequest, source);
this is good to encapsulate the logic in a properly named method.  really adds clarity to the code.
please move the line to where requestId was previously defined.

2022-09-08 18:32 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		if (myConfig.isPreserveRequestIdInResourceBody()) {
This is one hard logic to read.  i'm turning green.  cant' figure out what's going on unless i write my own unit test, which i did.

let's try replacing the entire logic withing the if statement with
return StringUtils.substringAfter(theSource, "#");


Re-inventing the wheel is innefficient and introduces errors.  when ever i have to do some type of manipulation that seems trivial or common, i'll try to find a utility method to do it for me.

2022-09-08 18:33 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	private String getRequestId(RequestDetails theRequest, String source) {
change String source to String theSource.  member properties always start with 'my' while method parameters start with 'the'

2022-09-08 18:36 UTC, epeartree commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java
> +		myDaoConfig.setStoreMetaSourceInformation(DaoConfig.StoreMetaSourceInformationEnum.SOURCE_URI_AND_REQUEST_ID);
i've added this setStoreMeta... to ensure that the associated property was indeed source_uri_and_request_id.  i don't think it is needed.  i'd try to remove it, re-run all tests in the class and see if we broke something.  and most likely we wont.

2022-09-08 18:46 UTC, epeartree commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_2_0/3960-when-creating-a-resource-patient-where-patientmetasource-is-provided-with-a-hash-the-hash-value-is-overwritten.yaml
> +title: "Previously, when the source in meta was specified with id, the id was replaced. This has been corrected."
now that we are experts with the meta resource, let's make this clearer by adding more meat to the bone:
Previously, when a client would provide a requestId within the source uri of a Meta.source, the provided requestId would get discarded and replaced by an id generated by the system.  This has been corrected.

2022-09-09 11:31 UTC, epeartree requested changes
Please have a look at the comments.

2022-09-09 15:25 UTC, MykolaMedynskyiSCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		String requestId = getRequestId(theRequest, source);
Now requestId depends on source, and in place where it was previously defined the source does not yet have its value.

2022-09-09 17:21 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +			return requestId.equals("") ? null : requestId;
can we really have EMPTY sting as a value returned by substringAfter

2022-09-12 17:33 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	protected IResourceHistoryTableDao myResourceProvenanceDao;
The name was change for the interface to better reflect it's nature, that is, to be a JpaRepository of ResourceHistoryProvenanceEntity.  The name could be further refined to 'IResourceHistoryProvenanceDao'.

Modification will be made.

2022-09-12 19:59 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	protected IResourceHistoryTableDao myResourceProvenanceDao;
I understand reasoning behind the change to the interface's name. But is the change here specifically intentional? Are we using the History table instead?

2022-09-13 17:55 UTC, MykolaMedynskyiSCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +	protected IResourceHistoryTableDao myResourceProvenanceDao;
We do not use it so I removed it.

2022-09-16 11:13 UTC, epeartree approved these changes

2022-09-16 15:27 UTC, StevenXLi approved these changes

2022-09-19 14:17 UTC, merged