SMILE-3459 Implemented -l parameter in validator. Added SnapshotGener…
hapifhir/hapi-fhir pull request #3983
Opened 2022-09-01 20:09 UTC by KGJ-software

Implemented support for -l parameter. Added test to ensure local profile is used.

Closes #4003

2022-09-01 20:28 UTC, dotasek commented
I would need to see some manner of test for this to verify that it's working.

I'd imagine that it would follow a similar format to: ca.uhn.fhir.cli.ValidateCommandTest testValidateLocalProfileR4() for example.

2022-09-01 20:34 UTC, dotasek commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java
> -			.setValidatorResourceFetcher(validatorResourceFetcher)
This looks like it will cause breakage; ValidatorWrapper would have no way to have its ValidatorResourceFetcher set here.

2022-09-01 20:37 UTC, dotasek commented on hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/ValidateCommand.java
> +						new LocalFileValidationSupport(ctx),
I think, based on what I see below, that LocalFileValidationSupport and SnapshotGeneratingValidationSupport can be added optionally. Like it is when theCommandLine.hasOption("r") adds support with addValidationSupport.

2022-09-01 20:43 UTC, KGJ-software commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java
> -			.setValidatorResourceFetcher(validatorResourceFetcher)
setValidatorResourceFetcher is called below, I think the one I removed was merely a duplicate.

2022-09-07 20:40 UTC, KGJ-software commented
@dotasek @nathandoef 

I think this PR is in a good place now.

2022-09-08 19:48 UTC, dotasek requested changes
See comments in code for details:

1) The ValidateCommandTest is perhaps a little too brittle. There's a less verbose check that might be sufficient.
2) LocalFileValidationSupport doesn't discriminate between types of resource, which could cause errors, and could be updated to be more robust. 
3) LocalFileValidationSupport should have its own unit test.

2022-09-09 14:18 UTC, markiantorno commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java
> -			.setValidatorResourceFetcher(validatorResourceFetcher)
Might be a good opportunity to change this implementation of Validator wrapper to take a parameter argument, vs just chaining in 10+ vars here.

2022-09-09 14:28 UTC, markiantorno reviewed
So, if there are tests that already exist that test that validation works when you provide a local profile, I wouldn't test that again. 

What I would suggest is going even more granular and tests the changes specifically, test the 'l' param is detected and causes the load to occure, test the struct def is loaded correctly, and test that the validator is called with the appropriate structure def used.

If we add another validation here, it will add more time to the overall tests. We want to keep them as lean as possible.

2022-09-14 18:31 UTC, dotasek approved these changes
This looks good to me. If @markiantorno approves as well, we're good to go!

2022-09-15 21:07 UTC, markiantorno approved these changes

2022-09-20 17:36 UTC, merged