4030 bulk export to support fhir basepatientid$export endpoint
hapifhir/hapi-fhir pull request #4032
Opened 2022-09-15 19:02 UTC by StevenXLi

- added new operation for the new endpoint
- added new field for all relevant objects in the bulk export pipeline to support patient id

2022-09-16 15:28 UTC, tadgh requested changes
Before we do a full once-over, i think we need to add support for the `patient` parameter of the Patient Export operation, defined here: 
https://hl7.org/fhir/uv/bulkdata/OperationDefinition-patient-export.html

2022-09-16 16:22 UTC, tadgh requested changes
Looks good! I do have some requested changes though to get this merged in. Let me know when they've been addressed and I'll re-review

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_2_0/4030-bulk-export-to-support-fhir-basepatientidexport-endpoint.yaml
> +title: "Previously, bulk export only supports endpoint [fhir base]/Patient/$export, where all patient records are export.
```suggestion
title: "Previously, Patient Bulk Export only supported endpoint [fhir base]/Patient/$export, which exports all patients. 
```

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_2_0/4030-bulk-export-to-support-fhir-basepatientidexport-endpoint.yaml
> +Now, it also supports [fhir base]/Patient/[id]/$export, where only one patient's records are exported.
```suggestion
Now, Patient Export can be done at the instance level, following this format:  `[fhir base]/Patient/[id]/$export`, which will export only the records for one patient.
```

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_2_0/4030-bulk-export-to-support-fhir-basepatientidexport-endpoint.yaml
> +Additionally, added support for the patient parameter in Patient bulk export"
```suggestion
Additionally, added support for the `patient` parameter in Patient Bulk Export, which is another way to get the records of only one patient."
```

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/bulk/export/svc/JpaBulkExportProcessor.java
> +			additionSearchParameterForPatientExport(theParams, resourceType, patientSearchParam, map);
```suggestion
			filterBySpecificPatient(theParams, resourceType, patientSearchParam, map);
```

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/bulk/export/svc/JpaBulkExportProcessor.java
> +		if (!resourceType.equalsIgnoreCase("Patient")) {
Suggestion: Invert this conditional. Whenever possible, use a positive case, its just easier to read, e.g. 

```
if (resourceType.equalsIgnoreCase("Patient") {
} else {
}

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/bulk/export/svc/JpaBulkExportProcessor.java
> +	@NotNull
issue: this is a jetbrains annotation, which is not permitted, use javax.annotation.nonnull

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/bulk/BulkDataExportOptions.java
> +	}
question: When was the last time you pulled master into your branch? This class looks vastly different now, due to changes made on a release branch

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/bulk/export/model/ExportPIDIteratorParameters.java
> +	private List<String> myPatientId;
variables (all around) should be pluralized if they are a list, e.g. `myPatientIds`. I'm only going to mention it here, but i see it in a few classes.

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/bulk/export/provider/BulkDataExportProvider.java
> +		@OperationParam(name = JpaConstants.PARAM_EXPORT_PATIENT, min = 0, max = 1, typeName = "string") IPrimitiveType<String> thePatient,
issue: this cardinality does not match the spec. As per the spec, there is no maximum on the patient parameter: https://build.fhir.org/ig/HL7/bulk-data/OperationDefinition-patient-export.html.

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/bulk/export/provider/BulkDataExportProvider.java
> +		bulkDataExportOptions.setPatientId(ArrayUtil.commaSeparatedListToCleanSet(thePatientId.getValueAsString()).stream().map(IdType::new).collect(Collectors.toSet()));
issue: I think once you change the cardinality to many, you will not need to use this comma-separating logic, as there should just be a list. Have a look at _typeFilter for an example.

2022-09-16 16:22 UTC, tadgh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/util/BulkExportUtils.java
> +		}
Question: Do we have a validator for the bulk export job parameters? If so, I suggest we add a validation phase that ensures that the patient id is only filled if the style of export is patient, and the same for group.

2022-09-19 13:46 UTC, StevenXLi commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/bulk/BulkDataExportOptions.java
> +	}
I merged in master before I made this MR, so it's up to date. I double checked with the current version of this file in master, I don't see any difference, other than the parts I've added for this ticket

2022-09-19 13:49 UTC, StevenXLi commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/util/BulkExportUtils.java
> +		}
There is a validator, but looking at it, it's only enforcing required parameters, like group id in group export style. Since the patient id is optional, erroring when it can simply be ignored seems counter intuitive to me.

2022-09-19 16:59 UTC, dmuylwyk commented
FYSA, here's a ticket I've filed against PDex regarding the suspect request pattern they've described for Patient-level exports:

https://jira.hl7.org/browse/FHIR-38650

2022-09-20 17:36 UTC, tadgh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/util/BulkExportUtils.java
> +		}
I was suggesting erroring when the following condition is true: 
1. PAtient id is non null 
_and_ 
2. Group id is non-null. 

If those are both set, something has gone wrong. 
That said, this is non-blocking as it should never occur anyhow.

2022-09-20 17:37 UTC, tadgh approved these changes

2022-09-20 17:42 UTC, merged

2022-09-23 21:36 UTC, tadgh reviewed
LGTM