4017 creating a searchparameter with an expression referencing metasecurity will return error hapi 1118
hapifhir/hapi-fhir pull request #4037
Opened 2022-09-16 13:37 UTC by MykolaMedynskyiSCDR

2022-09-20 17:00 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +			if (theContext.getVersion().getVersion().isOlderThan(FhirVersionEnum.DSTU3)) {
addd code for dstu3

2022-09-20 17:00 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
add empty dstu2 loggic block

2022-09-21 11:24 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +				parseExpression(isUnique, theResource, expression, theContext);
we will not be touching the R4 processing for now.  restore previous implementation.

2022-09-21 11:28 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +			FhirVersionEnum currentVersion = theContext.getVersion().getVersion();
rename variable to fhirVersion would be more relevant to what the variable represent.

2022-09-21 11:32 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +					String resourceName = (dotIdx == -1) ? nextPath : nextPath.substring(0, dotIdx);
Let's wrap the resourceName extraction into a method that will return an Optional<String>:
private Optional<String> extractResourceNameFromExpression(String theExpression){...}

2022-09-21 11:35 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +					if (theDaoConfig.isValidateSearchParameterExpressionsOnSave()) {
check if our new optional has indeed a resource name as part of the if statement

2022-09-21 11:38 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> +						try {
Until we understand what's going on with parsing an expression, we are not going to validate an expression that does not start with a resource.  remove the encapsulating try/catch.

2022-09-21 11:45 UTC, epeartree reviewed
the next step is to understand what is happening with the parsing.
i presume, and verification is required, that the following line will assert that the fhirpath in the nextPath can be applied to the temporaryInstance.  
`theContext.newFluentPath().evaluate(temporaryInstance, nextPath, IBase.class);`

while line 
`theContext.newFluentPath().parse(theExpression);`
SHOULD be parsing the expression and scream if it contains unknown elements/datatype.  we have to figure out why we can pass it garbage and all is good.

2022-09-21 12:12 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
> -						if (theDaoConfig.isValidateSearchParameterExpressionsOnSave()) {
we have to figure out to what setting/variable is this flag referring too and if we need to apply it to R4 as well(most likely).

2022-09-21 12:23 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoSearchParameterR4.java
>  								theContext.newFluentPath().evaluate(temporaryInstance, nextPath, IBase.class);
method 'newFluentPaht' is deprecated.  replace as per documentation

2022-09-30 17:34 UTC, tadgh requested changes
Overall looks good minus the logical change of no longer validating DSTU2 and older SPs. This should still occur.

2022-09-30 17:34 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_2_0/4017-creating-a-searchparameter-with-an-expression-referencing-metasecurity-will-return-error-hapi-1118.yaml
> +title: "Previously, creating a DSTU3 SearchParameter with an expression that does not start with a resource type would thrown an error. This has been corrected."
```suggestion
title: "Previously, creating a DSTU3 SearchParameter with an expression that does not start with a resource type would throw an error. This has been corrected."
```

2022-10-12 14:21 UTC, tadgh approved these changes

2022-10-13 15:05 UTC, merged