update mdm documentation
hapifhir/hapi-fhir pull request #4322
Opened 2022-12-02 21:17 UTC by Dimitri04

Updated mdm docs after testing candidateSearchParams and candidateFilterSearchParams

2022-12-02 21:42 UTC, patrick-vachon-smilecdr requested changes
Review done!

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
>  then the above `candidateSearchParams` and `candidateFilterSearchParams` would result in the following two consecutive searches for candidates:
nitpick: It would not be consecutive, they are run in parallel.

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +If you also wish to search for Practtioners for which active=true, the `resourceTpye` msut be defined in the `candidateSearchParams` before the `candidateFilterSearchParams` can be applied.
typo: 'resourceTpye msut' should be 'resourceType must'

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +         "searchParam": "eamil"
typo: 'eamil' should be 'email'

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +and the practictioner looked like this:
typo: 'practictioner' should be 'practitioner'

suggestion: I would also tell 'the incoming practitioner' here too.

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +The results of these searsches would be:
typo: 'searsches' should be 'searches'

suggestion: I would said: 'The resulting searches would be:' to be more exact.

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +-  `Practitioner?given=Adam,&family=Smith&active=true`
typo: `Practitioner?given=Adam&family=Smith&active=true`. comma should be removed after Adam I think.

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +-  `Patient?identifier=urn:oid:1.2.36.146.595.404.0.1|56789`
question: it would do the same searches?

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +If the practitioner `resourceType` was not defined in the `canadidateSearchParams`, the results of these same searsches would be:
typo: 'searsches' should be 'searches'

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +For intastances where the `candidateFilterSearchParams` criteria is identical across both resource types and you would like to apply it to all resources, the `*` can be used to specify the `resourceT
typo: 'intastances' should be 'instances'

suggestion: the `*` wildcard could be used in `resourceType`.

2022-12-02 21:42 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +If, however, you would like to apply the `candidateFilterSearchParams` to specific resource types only, the resourse types must be individually defined.
suggestion: 'However if you would like'

typo: 'resourse' should be 'resource'

suggestion: 'must be individually defined, like in:'

```json
{
   "candidateFilterSearchParams": [
      {
         "resourceType": "Patient",
         "searchParam": "active",
         "fixedValue": "true"
      },
      {
         "resourceType": "Practitioner",
         "searchParam": "active",
         "fixedValue": "true"
      }
   ]
}
```

2022-12-05 15:05 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
>  then the above `candidateSearchParams` and `candidateFilterSearchParams` would result in the following two consecutive searches for candidates:
Done.

2022-12-05 15:06 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +If you also wish to search for Practtioners for which active=true, the `resourceTpye` msut be defined in the `candidateSearchParams` before the `candidateFilterSearchParams` can be applied.
Done.

2022-12-05 15:06 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +         "searchParam": "eamil"
Done.

2022-12-05 15:06 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +and the practictioner looked like this:
Done.

2022-12-05 15:06 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +The results of these searsches would be:
Done

2022-12-05 15:06 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +-  `Practitioner?given=Adam,&family=Smith&active=true`
Done

2022-12-05 15:08 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +For intastances where the `candidateFilterSearchParams` criteria is identical across both resource types and you would like to apply it to all resources, the `*` can be used to specify the `resourceT
Done

2022-12-05 15:08 UTC, Dimitri04 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +If, however, you would like to apply the `candidateFilterSearchParams` to specific resource types only, the resourse types must be individually defined.
Done

2022-12-05 15:10 UTC, patrick-vachon-smilecdr commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_rules.md
> +-  `Patient?identifier=urn:oid:1.2.36.146.595.404.0.1|56789`
Oh I see! Sorry about that!

2022-12-22 19:43 UTC, patrick-vachon-smilecdr approved these changes
With the modifications done after the initial review, approved.

2022-12-22 19:56 UTC, tadgh approved these changes

2022-12-22 19:56 UTC, merged