PackageInstallerSvcImpl Says R4 is NOT Compatible with R4B
hapifhir/hapi-fhir pull request #4396
Opened 2022-12-29 17:42 UTC by KevinDougan-SmileCDR

Closes #4395

2023-01-03 17:08 UTC, tadgh requested changes
Approved pending the addition of a changelog

2023-01-03 17:08 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +		}
issue: this requires a changelog

2023-01-04 04:07 UTC, KevinDougan-SmileCDR commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +		}
Changelog added.

2023-01-04 16:01 UTC, tadgh approved these changes

2023-01-04 19:34 UTC, merged