Added resourceType as a parameter to $mdm-duplicate-golden-resources operation
hapifhir/hapi-fhir pull request #4434
Opened 2023-01-16 22:39 UTC by Qingyixia

#4432

2023-01-16 22:54 UTC, tadgh requested changes

2023-01-16 22:54 UTC, tadgh commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +		theRequestDetails.setRequestResourceType(theResourceType);
issue: this shouldn't be smuggled through the request details, it should be its own top-level method parameter in the MDM interface that needs it.

2023-01-16 22:54 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/RequestDetails.java
> +	}
issue: I think this design should be reworked.

The solution provided here involves modifying RequestDetails, a high-level request-based concept, with a very low level query parameter that we only care about for MDM. Essentially this setting is being smuggled through the request details so that specifically MDM can process it. This is Non-obvious to implementers (that the implementation will use some arbitrary field of an existing parameter that ostensibly has nothing to do with MDM itself). 

Instead, why not make it so that the API interface of the MDM methods accepts a resourceType as an additional @Nullable method parameter on `getDuplicateGoldenResources` ?

2023-01-16 22:59 UTC, Qingyixia commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +		theRequestDetails.setRequestResourceType(theResourceType);
Sure, I'll add theResourceType as a parameter for `getDuplicateGoldenResources `method then.

2023-01-16 23:25 UTC, Qingyixia commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/RequestDetails.java
> +	}
Thanks for making a such detailed comment! I'll address the suggestions.

2023-01-17 21:40 UTC, jmarchionatto requested changes
Version bump may be needed

2023-01-17 21:40 UTC, jmarchionatto commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/IMdmControllerSvc.java
> +	Page<MdmLinkJson> getDuplicateGoldenResources(MdmTransactionContext theMdmTransactionContext, MdmPageRequest thePageRequest, RequestDetails theRequestDetails, String theRequestResourceType);
Note that this change requires popping the version, if previous version of this function is used by CDR

2023-01-17 21:44 UTC, Qingyixia commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/IMdmControllerSvc.java
> +	Page<MdmLinkJson> getDuplicateGoldenResources(MdmTransactionContext theMdmTransactionContext, MdmPageRequest thePageRequest, RequestDetails theRequestDetails, String theRequestResourceType);
Yes, I'll start the version bumping process after both the MR and PR been approved.

2023-01-17 21:45 UTC, jmarchionatto commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/IMdmControllerSvc.java
> +	Page<MdmLinkJson> getDuplicateGoldenResources(MdmTransactionContext theMdmTransactionContext, MdmPageRequest thePageRequest, RequestDetails theRequestDetails, String theRequestResourceType);
Excelent!

2023-01-17 21:47 UTC, jmarchionatto approved these changes

2023-01-17 22:49 UTC, tadgh approved these changes

2023-01-19 13:43 UTC, merged