Issue 4426 add sorting to mdm queries
hapifhir/hapi-fhir pull request #4439
Opened 2023-01-17 20:25 UTC by jmarchionatto

2023-01-18 15:05 UTC, lukedegruchy commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/mdm/MdmLinkDaoJpaImpl.java
> +		theParams.getSort().forEach(sortSpec -> {
Nitpick:  why not: getSort()
.stream()
.map(sortSpec -> ....) 
.collect(Collectors.toUnmodifiedList())

2023-01-18 15:07 UTC, lukedegruchy commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java
> +			List<Long> createdDates = linkList.stream().map(this::extractCreated).collect(Collectors.toList());
Nitpick:  Stream operations are easier to read if they're one per line ex:

linkList.stream()
.map(....)
.collect(.....)

2023-01-18 19:04 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/mdm/MdmLinkDaoJpaImpl.java
> +		theParams.getSort().forEach(sortSpec -> {
Sure. Good idea

2023-01-18 19:07 UTC, jmarchionatto commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java
> +			List<Long> createdDates = linkList.stream().map(this::extractCreated).collect(Collectors.toList());
I think it is a matter of use. I found code more readable using just a line for a simple method reference mapping

2023-01-20 00:26 UTC, tadgh requested changes
Overall looks good minus one comment. I do have a request though: Can you add a test that exercises pagination in conjunction with sort? I don't see one here, and there is new paging code here that previously didn't exist.

2023-01-20 00:26 UTC, tadgh commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmControllerSvcImpl.java
> +		new ReadPartitionIdRequestDetails(null, RestOperationTypeEnum.EXTENDED_OPERATION_SERVER, null, null, null);
question: Why is this here? It is not assigned to a variable, is it ever used?

2023-01-20 14:00 UTC, jmarchionatto commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmControllerSvcImpl.java
> +		new ReadPartitionIdRequestDetails(null, RestOperationTypeEnum.EXTENDED_OPERATION_SERVER, null, null, null);
Don't know. Looks like an old leftover. Removing it. Nice catch!

2023-01-20 17:25 UTC, tadgh approved these changes

2023-01-20 17:25 UTC, merged