4523 subscription sources
hapifhir/hapi-fhir pull request #4543
Opened 2023-02-12 05:35 UTC by tadgh

* Populate resource with correct source information before it gets published to subscriptions
   *  Parameterized test
   *  Changelog
   *  rename myContext to myFhirContext

2023-02-13 15:14 UTC, Qingyixia reviewed
A much better solution now! Thanks

2023-02-13 15:14 UTC, Qingyixia commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/match/deliver/BaseSubscriptionDeliverySubscriber.java
> +	protected IBaseResource updateDeliveryResourceWithMetaSource(IBaseResource thePayloadResource) {
Suggestion: This method is not used anymore, I think all the changes in this class can be reverted.

2023-02-13 15:14 UTC, Qingyixia commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/match/deliver/BaseSubscriptionDeliverySubscriberTest.java
> +	@Test
Suggestion: This test is regarding the previous solution, it can be deleted as well. Otherwise, it'll be failed.

2023-02-13 15:14 UTC, Qingyixia commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/match/deliver/BaseSubscriptionDeliverySubscriberTest.java
> +		when(myDaoRegistry.getResourceDao(anyString())).thenReturn(myResourceDao);
Suggestion: These added 'when' statements can also be deleted. In short, all changes in this class can be reverted.

2023-02-13 15:14 UTC, Qingyixia commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/message/MessageSubscriptionR4Test.java
> +	public void testCreateUpdateAndPatchRetainCorrectSourceThroughDelivery(DaoConfig.StoreMetaSourceInformationEnum theStorageStyle, String theExplicitSource, String theRequestId, String theExpectedSour
Praise: Wow, this test class will make my life much easier!! 👏

2023-02-17 13:35 UTC, epeartree requested changes
Good strong work.

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/MetaUtil.java
> +	public static String cleanProvenanceSourceUri(String theProvenanceSourceUri) {
suggest renaming to cleanProvenanceSourceUriOrEmpty

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/MetaUtil.java
> +	public static <R extends IBaseResource> void populateResourceSource(FhirContext theFhirContext, String theProvenanceSourceUri, String theProvenanceRequestId, R theRetVal) {
very busy and hard to figure out what's going on:

{
        String sourceString = cleanProvenanceSourceUriOrEmpty(theProvenanceSourceUri);
        
        if(isNotEmpty(theProvenanceRequestId)){
            sourceString = sourceString + "#" + theProvenanceRequestId;
        }

        if(isNotEmpty(sourceString)){
            setSource(......);
        }

        

}

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +
remove extra space

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/match/deliver/message/SubscriptionDeliveringMessageSubscriber.java
> +import ca.uhn.fhir.util.HapiExtensions;
please check if this import is required.

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/match/deliver/message/SubscriptionDeliveringMessageSubscriber.java
>  		String payloadId = theSourceMessage.getPayloadId();
if u remove the import above, remove both new line as we're not going to submit a mod for adding lines.

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDaoTest.java
> +		assertEquals("", MetaUtil.cleanProvenanceSourceUri(null));
add the following assert
assertEquals("abc", MetaUtil.cleanProvenanceSourceUri("abc#"));

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/message/MessageSubscriptionR4Test.java
> +
one new line too many

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/message/MessageSubscriptionR4Test.java
> +	}
add new line :)

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/message/MessageSubscriptionR4Test.java
> +	}
add new line :)

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/RestHookTestR4Test.java
u'r repeating "http://source-system.com" 4 times, i'd declare String sourceSystemUrl = "http://source-system.com";

but that's up to u

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/BaseSubscriptionsR4Test.java
>  		MethodOutcome methodOutcome;
nit picking here.  please make sure .getIdElement() will ALWAYS return something so we don't end up with NPE

2023-02-17 13:35 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/BaseSubscriptionsR4Test.java
>  		Observation observation = createBaseObservation(theCode, theSystem);
i'd use isNotBlank(), but that's up to u.  

Basically, when ever i can off load a.n.y work to a boiler library, i do it.  it just makes the code more redeable

2023-02-17 14:48 UTC, Qingyixia commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/MetaUtil.java
> +	public static <R extends IBaseResource> void populateResourceSource(FhirContext theFhirContext, String theProvenanceSourceUri, String theProvenanceRequestId, R theRetVal) {
done

2023-02-17 14:49 UTC, Qingyixia commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/match/deliver/message/SubscriptionDeliveringMessageSubscriber.java
> +import ca.uhn.fhir.util.HapiExtensions;
Removed

2023-02-17 14:53 UTC, Qingyixia commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/BaseSubscriptionsR4Test.java
>  		MethodOutcome methodOutcome;
Checked all possible situations and whether the subscription has an ID element or not, this condition check will work as expected.

2023-02-17 14:54 UTC, Qingyixia commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/subscription/BaseSubscriptionsR4Test.java
>  		Observation observation = createBaseObservation(theCode, theSystem);
Changed, thank you for your time and those detailed suggestions! Appreciate that👍

2023-02-17 17:50 UTC, epeartree approved these changes

2023-02-17 18:09 UTC, merged