typedbundleprovider getallresources override
hapifhir/hapi-fhir pull request #4552
Opened 2023-02-14 21:19 UTC by Capt-Mac

HapiFhirDal in Cr-common had a bug where pagination of searched resources resulted in null value if default queryCount was exceeded. Overriding from TypedBundleProvider.getallresources fixed the issue

2023-02-14 21:29 UTC, JPercival commented
Do we have a test that can reproduce the buggy behavior to validate that it's fixed?

In theory, loading up the server with 20+ dummy Patients and then trying to search for them using the HapiFhirDal would repro it.

2023-02-15 19:50 UTC, Capt-Mac commented
> 

added test to verify search finds all resources past set queryCount value, old code causes null pointer exception for this test, current code identifies all resources posted from test data

2023-02-15 21:37 UTC, JPercival requested changes

2023-02-15 21:37 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/CqlMeasureEvaluationR4ImmunizationTest.java
> +	void canSearchMoreThan50Patients(){
Could we instead add this to a Test class for the HapiFhirDal? This test isn't actually related to the immunization use case.

2023-02-15 22:09 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/CqlMeasureEvaluationR4ImmunizationTest.java
> +	void canSearchMoreThan50Patients(){
moved to it's own class

2023-02-15 22:36 UTC, JPercival approved these changes

2023-02-16 18:25 UTC, tadgh commented
Since DQM is now publicly available, this change requires a changelog. You can place your changelog in the `rel_6_6_0` folder in the docs project. Just copy an existing one, and modify it.

2023-02-16 19:02 UTC, tadgh approved these changes
Approved pending one final change

2023-02-16 19:02 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_6_0/4551-fix-hapifhirdal-search-pagination.yaml
> +type: change
This type should be `fix` as opposed to change, assuming my read of this as a bug is correct.

2023-02-16 20:59 UTC, merged