$care-gaps functionality integration
hapifhir/hapi-fhir pull request #4561
Opened 2023-02-16 21:01 UTC by chalmarm

2023-03-20 17:36 UTC, JPercival commented
issue: there are conflicts with the master branch that need to be resolved.

2023-03-20 17:36 UTC, JPercival requested changes

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsOperationProvider.java
> +		RequestDetails theRequestDetails,
todo: the parameters here don't match the hapi-fhir naming convention:
https://github.com/hapifhir/hapi-fhir/wiki/Contributing#code-style

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/SubmitDataService.java
> +public class SubmitDataService{
issue: I think we need some test coverage of this class. It's used indirectly for setting up a $care-gaps test, but the class itself isn't tested.

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/MeasureOperationsProviderTest.java
> +		/*List<StubServiceBuilder> reads = new ArrayList<>();
todo: Could you remove commented code that's not being used?

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/CareGapsOperationProviderIT.java
> +	public void careGapsEndToEnd() throws IOException {
todo: It's customary to have the description of the test outside the test as commentary, rather than at the top of the method.

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/CareGapsOperationProviderIT.java
> +			ourServerBase = "http://localhost:" + myPort + "/fhir/context";
issue: Did we ever chase down why this test needed `/fhir/context` as opposed to just `/fhir`? I don't understand the setup here.

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/dstu3/MeasureOperationsProviderTest.java
> +		/*List<StubServiceBuilder> reads = new ArrayList<>();
todo: Please remove commented code.

2023-03-20 17:36 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsOperationProvider.java
> +	/**
praise: Thanks for adding the description and links here. It's very helpful!

2023-03-21 02:00 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsOperationProvider.java
> +		RequestDetails theRequestDetails,
Addressed

2023-03-21 02:03 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/SubmitDataService.java
> +public class SubmitDataService{
Addressed

2023-03-22 15:07 UTC, JPercival requested changes

2023-03-22 15:07 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsService.java
> +	public CareGapsService(CrProperties crProperties,
todo: similar issues here with naming conventions

2023-03-22 15:07 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsService.java
> +	public CareGapsService(CrProperties crProperties,
Actually, throughout this file.

2023-03-22 23:01 UTC, barhodes commented on hapi-fhir-storage-cr/pom.xml
> +		</dependency>
This shouldn't be needed.  If it is it needs to use the project.version variable.

2023-03-23 13:31 UTC, chalmarm commented on hapi-fhir-storage-cr/pom.xml
> +		</dependency>
Removed. I don't think we need it.

2023-03-28 00:09 UTC, barhodes commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsService.java
> +	public Parameters getCareGapsReport(IPrimitiveType<Date> thePeriodStart,
This should maybe have a Javadoc

2023-03-28 00:09 UTC, barhodes commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/SubmitDataService.java
> +	public Bundle submitData(IdType theId, MeasureReport theReport, List<IBaseResource> theResources) {
This could also use a Javadoc

2023-03-28 19:46 UTC, JPercival approved these changes

2023-04-03 17:17 UTC, epeartree requested changes

2023-04-05 18:57 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/dstu3/measure/MeasureService.java
> +	protected void ensureSupplementalDataElementSearchParameter() {
Changed the implementation.

2023-04-05 18:57 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/MeasureService.java
> +	protected void ensureSupplementalDataElementSearchParameter() {
Changed the implementation.

2023-04-05 19:09 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/config/CrProperties.java
> +			return this.myCqlUseOfEmbeddedLibraries;
addressed.

2023-04-05 19:10 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/config/CrProperties.java
> +		public void setMeasureReport(MeasureReportConfiguration theMeasureReport) {
addressed/

2023-04-06 11:55 UTC, epeartree approved these changes

2023-04-06 19:52 UTC, fil512 approved these changes

2023-04-06 19:52 UTC, fil512 commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/IResourceLoader.java
> +		if (theLocation.endsWith("json")) {
suggestion: use EncodingEnum instead of a string

2023-04-06 19:52 UTC, fil512 commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/IResourceLoader.java
> +		String resourceString = stringFromResource(theLocation);
suggestion: consider using EncodingEnum.detectEncoding()

2023-04-06 19:52 UTC, fil512 commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/dstu3/CrProviderDstu3Test.java
> -//		assertEquals(entries.get(0).getResponse().getStatus(), "201 Created");
can these asserts be replaced with something equally assertive?

2023-04-06 19:52 UTC, fil512 commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/CareGapsOperationProviderIT.java
> +		if (ourRestServer == null) {
suggestion: use `RestfulServerExtension`

2023-04-07 14:05 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/dstu3/measure/MeasureService.java
> +public class MeasureService implements IDaoRegistryUser {
Ken, please suggest if you want me to take care for this PR. According to the class level notes captured on IDaoRegistryUser, plan is to address them once prioritized.

2023-04-10 12:24 UTC, chalmarm commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/dstu3/CrProviderDstu3Test.java
> -//		assertEquals(entries.get(0).getResponse().getStatus(), "201 Created");
addressed

2023-04-10 12:58 UTC, chalmarm commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/IResourceLoader.java
> +		String resourceString = stringFromResource(theLocation);
addressed

2023-04-10 12:59 UTC, chalmarm commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/IResourceLoader.java
> +		if (theLocation.endsWith("json")) {
addressed

2023-04-10 13:00 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/config/CrR4Config.java
> +	public SubmitDataProvider r4SubmitDataProvider(Function<RequestDetails, SubmitDataService> theSubmitDataServiceFunction){
addressed

2023-04-10 20:49 UTC, chalmarm commented
@fil512 Can you please take a look at this ticket and merge if it is good to.

2023-04-11 15:18 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsService.java
> +	Patient ensurePatient(String thePatientRef) {
addressed.

2023-04-11 15:18 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsService.java
> +					patient -> futures.add(CompletableFuture.supplyAsync(() -> patientReports(myRequestDetails,
addressed.

2023-04-11 15:31 UTC, chalmarm commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/r4/measure/CareGapsOperationProvider.java
> +@Component
Not required. Removed.

2023-04-11 16:28 UTC, merged