4570 add support for warning messages to the batch framework
hapifhir/hapi-fhir pull request #4571
Opened 2023-02-21 16:41 UTC by StevenXLi

- added new fields to batch entities (instance and work chunk) with new columns in the table
- added processing in the datasink to persistent the warning
- added new database query to save the warning to work chunk

2023-05-26 23:27 UTC, tadgh commented
@StevenXLi I am closing this PR as it is for 6.6.0 which has already shipped. If this code still needs to get merged, please re-implement against current master or cherry-pick your changes into a new PR.

2023-05-29 13:54 UTC, StevenXLi commented
@tadgh This PR is made against master, i don't see why i need to re-implement if i'm updating it to merge to current master

2023-05-30 15:02 UTC, TipzCM requested changes

2023-05-30 15:02 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/BaseDataSink.java
> +		if (theMessage.contains("Can not create resource") && theMessage.contains("it would create a duplicate unique index matching query")) {
Not a good idea to code default behaviour for a single flow into the base handler.

Base classes should only deal with base logic.

Otherwise, make this an abstract method, and implement it properly in all implementers.

I know you didn't want to break dependent code though. To which i'd suggest, maybe this is something you put on IDataSync with a default (empty) implementation, and add implementation for the one job you care about (here).

2023-05-30 15:02 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				myJobPersistence.updateWorkChunkWarningMessage(chunkId, theDataSink.getRecoveredWarning());
Your update replaces it.

Is it only possible to have 1 warning message? Should it always be replaced?

Last in wins is a valid choice, but it seems odd that it's always the default choice (is it expected that the last warning is always the worst?)

2023-05-30 15:29 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2JobInstanceEntity.java
> +	private String myWarningMessage;
yes, it'll be a single warning message when the job is done. It's similar to how the error message is implemented.

I can see how only having 1 at the end might not be ideal. The best way i can see to have more than one, is to add to the string with the other warnings, but this can reach the max length limit pretty quick.

2023-05-30 18:02 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				myJobPersistence.updateWorkChunkWarningMessage(chunkId, theDataSink.getRecoveredWarning());
Agree.  I suggest concatenating them with a newline.  You can do that in the jql with something like `jobInstance.myWarningMessage = CASE WHEN jobInstance.myWarningMessage is null THEN :new_warning_param ELSE CONCAT(jobInstance.myWarningMessage, '\n', :new_warning_param) END

2023-05-30 19:27 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.type(ColumnTypeEnum.STRING, 500);
I think this is a design choice, all the columns that we have us STRING instead of TEXT, i don't know what the difference is. I'm just sticking to conventions

2023-05-30 19:28 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +	@Query("UPDATE Batch2WorkChunkEntity e SET e.myWarningMessage = :wm WHERE e.myId = :id")
deleted, good note

2023-05-30 19:28 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	default void updateWorkChunkWarningMessage(String theChunkId, String theWarningMessage) {
done

2023-05-30 19:28 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				myJobPersistence.updateWorkChunkWarningMessage(chunkId, theDataSink.getRecoveredWarning());
done

2023-05-30 19:29 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				myJobPersistence.updateWorkChunkWarningMessage(chunkId, theDataSink.getRecoveredWarning());
ok, added

2023-05-30 19:30 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/BaseDataSink.java
> +		if (theMessage.contains("Can not create resource") && theMessage.contains("it would create a duplicate unique index matching query")) {
I still am confused on the implementation of this. Can you elaborate how this should be done?

2023-05-30 19:30 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2JobInstanceEntity.java
> +		myWarningMessage = theWarningMessage;
changed, via suggestion on the other comment

2023-05-30 19:31 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2JobInstanceEntity.java
> +	private String myWarningMessage;
changed, via suggestion on the other comment

2023-05-30 19:31 UTC, StevenXLi commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4570-add-support-for-warning-messages-to-the-batch-framework.yaml
> +title: "The batch2 framework now supports warning messages."
deleted now

2023-05-30 20:10 UTC, michaelabuckley approved these changes
Approved with some suggestions.
I misunderstood where the concatenation needed to happen.

2023-05-30 20:10 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +		"e.myWarningMessage = CASE WHEN e.myWarningMessage is null THEN :warningMessage ELSE CONCAT(e.myWarningMessage, '\\n', :warningMessage) END " +
error:  Oops.  I told you the wrong thing.  We are just updating the single chunk here, and only once.   We don't need the fancy CASE statement.  I thought this was for the instance.  Please simplify back.

2023-05-30 20:10 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.type(ColumnTypeEnum.STRING, 500);
ColumnTypeEnum.STRING have limited sizes, while TEXT is unlimited size.  I recommend using TEXT since we could have lots of warnings.

2023-05-30 20:10 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobInstance.java
> +	private String myWarningMessage;
minor: should this be `myWarningMessages` now?

2023-05-30 20:10 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/InstanceProgress.java
> +			myWarningMessages.addAll(Arrays.asList(theChunk.getWarningMessage().split("\\n")));
I misunderstood.  We'll only have one warning per chunk, so the split can be dropped.  Just check to see it if is null/empty.

2023-05-30 20:10 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/InstanceProgress.java
> +		String newWarningMessage = String.join("\\n", myWarningMessages);
question: do you mean to escape this?  I was suggesting a plain newline.
```suggestion
		String newWarningMessage = String.join("\n", myWarningMessages);
```

2023-05-31 14:26 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/InstanceProgress.java
> +		String newWarningMessage = String.join("\\n", myWarningMessages);
It was suppose to be a plain newline, nice catch

2023-05-31 14:27 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/progress/InstanceProgress.java
> +			myWarningMessages.addAll(Arrays.asList(theChunk.getWarningMessage().split("\\n")));
I see, thought we would have more than one update per chunk

2023-05-31 14:27 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobInstance.java
> +	private String myWarningMessage;
yes, changed

2023-05-31 14:27 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +		"e.myWarningMessage = CASE WHEN e.myWarningMessage is null THEN :warningMessage ELSE CONCAT(e.myWarningMessage, '\\n', :warningMessage) END " +
ok, simplified

2023-05-31 14:28 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.type(ColumnTypeEnum.STRING, 500);
I see, guess we never needed TEXT before

2023-05-31 14:28 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.type(ColumnTypeEnum.STRING, 500);
changed

2023-05-31 23:01 UTC, tadgh approved these changes

2023-06-01 14:41 UTC, StevenXLi commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			.type(ColumnTypeEnum.STRING, 500);
Seems like we can't just use TEXT data type. There seems to be compatablity issues with some dbs if a char column is unlimited size(or 1000000000 according to migrations). So the only solution here is to keep it as STRING with length 4000 (max column length) or use a LOB.

2023-06-01 15:15 UTC, TipzCM approved these changes

2023-06-01 15:15 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				event = new WorkChunkCompletionEvent(chunkId, recordsProcessed, recoveredErrorCount, theDataSink.getRecoveredWarning());
Why not just always pass it in and the workchunkcompletion can handle it?

2023-06-01 15:15 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IWarningProcessor.java
> +	public void recoverWarningMessage(String theErrorMessage);
because you only have 1 implementation of this for the entire job, might want to add other metadata to this call (wrapped in a parameter): maybe even the job execution step params.


Should also probably include info that this is *per data chunk* and not per job, or per step

2023-06-01 15:15 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IWarningProcessor.java
> +	public String getRecoveredWarningMessage();
So they can only store and return 1 warning message?

What if they have 12? or 200?

2023-06-01 15:32 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IWarningProcessor.java
> +	public void recoverWarningMessage(String theErrorMessage);
I don't see the value of passing the other metadata in at this point in time. Down the line, when that's necessary, the parameters for this method can change to support that.

2023-06-01 15:38 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IWarningProcessor.java
> +	public String getRecoveredWarningMessage();
The implementation right now is for one error to be persisted as a warning, having a repeat of 12 or 200 of the same warning doesn't really help at this point.
Remember this is the specified implementation for warning parsing, when it needs to support more warnings, we can change it to do so.

2023-06-01 15:43 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/StepExecutor.java
> +				event = new WorkChunkCompletionEvent(chunkId, recordsProcessed, recoveredErrorCount, theDataSink.getRecoveredWarning());
good point, changed

2023-06-01 17:16 UTC, merged