Ld 20230308 mdm link history rest jpa
hapifhir/hapi-fhir pull request #4648
Opened 2023-03-15 18:13 UTC by lukedegruchy

2023-03-20 22:20 UTC, michaelabuckley requested changes
We should talk about config.  We normally only use system properties for test hacks and debug stuff.  Normal features get a real configuration objects that decouple config from the mechanism.  JPA server-starter packages Hapi as a Spring-boot app, and that will be yaml-file driven.  Not system-properties.

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/system/HapiSystemProperties.java
> +	static final String NON_RESOURCE_DB_HISTORY_DISABLED = "non-resource-db-history.disabled";
question: It is strange to control storage via a system property instead of via a settings configuration object.  Why not provide a settings configuration source like the Hapi Daos with StorageSettings.

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_operations.md
> +MDM link history is made possible by a back-end configuration that enables saving the historical entries to a new audit table in the database.  This feature is enabled by default.  Some clients may w
suggestion: Positive language is clearer:
```suggestion
MDM link history is made possible by a back-end configuration that enables saving the historical entries to a new audit table in the database.  This feature is enabled by default.  Some clients may wish to leave this feature disabled in order to save disk space.
The `non-resource-db-history.disabled` system property disables this operation.
```

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/mdm/MdmLinkDaoJpaImpl.java
> +			throw new IllegalStateException(Msg.code(2291) + "The first element in the envers array must be an MdmLink");
minor: These checks are of internal code, not user data.  They should never happen.  You could use Validate.isInstanceOf() as an assert.

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/entity/AuditableBasePartitionable.java
> + * This is a copy of (@link {@link BasePartitionable} used ONLY for entities that are audited by Hibernate Envers.
Nice docs

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/MdmLinkJson.java
> +		return Objects.equals(myGoldenResourceId, that.myGoldenResourceId) && Objects.equals(mySourceId, that.mySourceId) && myMatchResult == that.myMatchResult && myLinkSource == that.myLinkSource && Obje
minor: this formatting is unreadable.

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/MdmLinkJson.java
> +		return Objects.hash(myGoldenResourceId, mySourceId, myMatchResult, myLinkSource, myCreated, myUpdated, myVersion, myEidMatch, myLinkCreatedNewResource, myVector, myScore, myRuleCount);
I'd much rather read a vertical list.  The main reviewer task is making sure that equals() and hashCode() agree, and this formatting makes that very hard.  Ideally listed in a column in the same order as each other for easy scan.

2023-03-20 22:20 UTC, michaelabuckley commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +			throw new MethodNotAllowedException(Msg.code(2297) + "The feature that shows historical results for MDM links is currently disabled.  Please disable or de-reference system property: non-resource-d
issue:  it is kinda gross to advertise that we support an operation in our metadata document, but then nerf it.  Instead, you could split this into a separate provider and only include the provider in the server when the operation is enabled.

2023-03-21 13:07 UTC, lukedegruchy commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/system/HapiSystemProperties.java
> +	static final String NON_RESOURCE_DB_HISTORY_DISABLED = "non-resource-db-history.disabled";
It was Ken who suggested this approach given that the feature needs to be toggleable by a hapi-fhir user.

This is the first time I've heard of StorageSettings.  I'll investigate how they work.

2023-03-21 19:34 UTC, lukedegruchy commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/system/HapiSystemProperties.java
> +	static final String NON_RESOURCE_DB_HISTORY_DISABLED = "non-resource-db-history.disabled";
I was able to address this but I had no choice but to do the hack that I had previously intended to do in `HibernatePropertiesProvider` as it was not possible to extend `jpaProperties` from `JpaConfig`

2023-03-21 21:27 UTC, michaelabuckley approved these changes
Minor doc suggestions.

2023-03-21 21:27 UTC, michaelabuckley commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java
> +	 * This setting controls whether non-resource DB history is disabled.
```suggestion
	 * This setting controls whether MdmLink and other non-resource DB history is disabled.
```

2023-03-21 21:27 UTC, michaelabuckley commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/configuration.md
> +This setting controls whether non-resource (ex: Patient is a resource, MdmLink is not) DB history is enabled.  Presently, this only affects the history for MDM links, but the functionality may be ext
```suggestion
This setting controls whether MdmLink and any other non-resource (ex: Patient is a FHIR resource, MdmLink is not) DB history is enabled.  Presently, this only affects the history for MDM links, but the functionality may be extended to other domains.
```

2023-03-21 21:29 UTC, michaelabuckley commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java
> +	private boolean myNonResourceDbHistoryDisabled = false;
suggestion: negative boolean properties are such trouble.  Change to myNonResourceHistoryEnabled.

2023-03-21 21:30 UTC, michaelabuckley commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java
> +	 * Since 6.6.0
```suggestion
	 * Since 6.6.0
	 * Applies to MDM links.
```

2023-03-22 13:20 UTC, lukedegruchy commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java
> +	private boolean myNonResourceDbHistoryDisabled = false;
Agreed.  I make this change.

2023-03-22 16:15 UTC, merged