Bug cql engine paging
hapifhir/hapi-fhir pull request #4664
Opened 2023-03-20 15:57 UTC by Capt-Mac

Removing previous bundle provider to allow for iterableBundle provider, which will allow for paging resources instead of full consumption of patient resources at once

2023-03-22 14:52 UTC, JPercival requested changes

2023-03-22 14:52 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiLibrarySourceProvider.java
> +	public IPagingProvider getPagingProvider() {
issue: Didn't we discover that we didn't need the paging provider passed around to all the different classes? Could we remove that?

2023-03-22 17:35 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiLibrarySourceProvider.java
> +	public IPagingProvider getPagingProvider() {
removed from tests and cr classes

2023-03-22 17:35 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +				throw new RuntimeException("Shouldn't happen bruh");
added msg code and updated msg string

2023-03-22 17:36 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +import ca.uhn.fhir.rest.api.server.IBundleProvider;
merged in master with those changes and updated this class to match

2023-03-27 00:11 UTC, fil512 requested changes

2023-03-27 00:11 UTC, fil512 commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +				var result = this.queryFunc.apply(dataType, queries.get(index)).iterator();
this is difficult to understand.  consider intermediate variables

2023-03-27 00:11 UTC, fil512 commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +	static class QueryIterable implements Iterable<Object> {
this is a pretty tricksy class.  Would benefit from JavaDoc

2023-03-27 00:11 UTC, fil512 commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +			private final BiFunction<String, SearchParameterMap, Iterable<IBaseResource>> queryFunc;
Wrapping `BiFunction<String, SearchParameterMap, Iterable<IBaseResource>>` in a small class with meaningful methods relevant to the context you're using it (i.e. a method name more specific than `apply()`) would go a long way to clarifying what's going on with this code.

2023-03-27 00:11 UTC, fil512 commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
>  			Method[] methods = hapiMap.getClass().getDeclaredMethods();
This doesn't look right at all.  We should talk about why reflection is required here.

2023-03-27 15:42 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +					currentResult = loadNext();
- **load initial query results:** if (currentResult == null && index < queries.size())  
- **load next query results after initial empties:** else if (!currentResult.hasNext())
- **current query results, does result have next value:** return currentResult != null && currentResult.hasNext();

2023-03-28 12:25 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +public class BundleIterable implements Iterable<IBaseResource> {
Good to know. I think this will require some downstream updates to make this change. Will keep now if it doesn't cause impacts to coredev.

2023-03-28 12:25 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +			if (this.currentResourceListIndex >= this.currentResourceList.size()) {
moved to an assertion, thanks

2023-03-28 12:26 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +	static class QueryIterable implements Iterable<Object> {
added javadoc, thanks

2023-03-28 12:47 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +			private final BiFunction<String, SearchParameterMap, Iterable<IBaseResource>> queryFunc;
added some comments around this class and method enclosed to provide more clarity

2023-03-28 13:34 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +public class BundleIterable implements Iterable<IBaseResource> {
added javadoc and used @NotThreadSafe annotation

2023-03-28 13:38 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +				var result = this.queryFunc.apply(dataType, queries.get(index)).iterator();
added javadoc and additional in line explanation of data flow

2023-03-28 17:54 UTC, fil512 commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/BundleIterable.java
> +public class BundleIterable implements Iterable<IBaseResource> {
nice!  I didn't know that was an annotation

2023-03-28 18:02 UTC, fil512 approved these changes

2023-03-28 18:02 UTC, fil512 commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/BundleIterableR4Test.java
> +		var bundleIt = bundleIterable.iterator();
Can be replaced by `Iterables.size(bundleIterable)`

2023-03-28 18:15 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/HapiFhirRetrieveProvider.java
> +	 * Mainly used to
updated

2023-03-28 18:15 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/BundleIterableR4Test.java
> +		var bundleIt = bundleIterable.iterator();
replaced

2023-03-28 19:45 UTC, JPercival approved these changes

2023-03-31 15:09 UTC, merged