4693 enable partitioning in bulk import
hapifhir/hapi-fhir pull request #4694
Opened 2023-03-28 15:48 UTC by StevenXLi

- added partitionid to jobinstance
- changed functionality in cosumefilestep to support mutitenancy

2023-03-28 21:30 UTC, michaelabuckley requested changes
This looks very clean, but we don't need two copies of the RequestPartitionId.  How about adding it to JobInstanceStartRequest and JobInstance, and the parameters don't need it.

2023-03-28 21:30 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/BulkImportJobParameters.java
> +	@JsonProperty(value = "partitionId", required = false)
I don't understand why we have the RequestPartitionId in both the JobInstance, and here.  JobInstance is available in StepExecutionDetails. Can we just do this in one place?

2023-03-28 21:31 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobInstance.java
> +	private PartitionablePartitionId myPartitionId;
I don't see this used at all.

2023-03-29 13:58 UTC, StevenXLi commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/JobInstance.java
> +	private PartitionablePartitionId myPartitionId;
This is being used in `importPollStatus` in `BulkDataImportProvider`

2023-03-29 13:59 UTC, StevenXLi commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/imprt/BulkImportJobParameters.java
> +	@JsonProperty(value = "partitionId", required = false)
`JobInstance` is available in `StepExecutionDetails`, however it's not available in `importByManifest` in `BulkDataImportProvider` where it needs to be set in order to be used in the `ConsumeFilesStep`

2023-03-30 20:48 UTC, michaelabuckley approved these changes
Looks good.

2023-03-31 13:43 UTC, merged