Enhance LogbackCaptureTestExtension
hapifhir/hapi-fhir pull request #4869
Opened 2023-05-11 17:37 UTC by pepsiofficial

Addresses #4852

2023-05-11 18:07 UTC, fil512 requested changes

2023-05-11 18:07 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmSubscriptionLoader.java
> +		SearchParameterMap searchParamMap = new SearchParameterMap();
issue: I recommend you use the `IBaseResource resource = read(IIdType theId, RequestDetails theRequestDetails, boolean theDeletedOk)` method instead and then call `resource.isDeleted()`

2023-05-11 18:26 UTC, pepsiofficial commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmSubscriptionLoader.java
> +		SearchParameterMap searchParamMap = new SearchParameterMap();
Looking at the javadoc, I’m not confident the three-param read is correct here.  The resources we’re looking for might not be there because this is the first time Smile is trying to create them.
If that doesn’t matter, and the javadoc just only considers the deletion case, I’m happy make the switch

2023-05-11 18:50 UTC, pepsiofficial commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmSubscriptionLoader.java
> +		SearchParameterMap searchParamMap = new SearchParameterMap();
Update: this issue no longer exists on master, and I've ported your fix from master

2023-05-12 14:48 UTC, TipzCM approved these changes
minor stuff

2023-05-12 14:48 UTC, TipzCM approved these changes
minor stuff

2023-05-12 15:22 UTC, pepsiofficial commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/tx/HapiTransactionService.java
> +						ourLog.debug("Unexpected transaction exception. Will not be retried.", e);
This is something Ken has already done on master.  I don't feel like I can comment intelligently here; I've already done this fix differently once

2023-05-12 15:27 UTC, pepsiofficial commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/test/util/LogbackEventMatcher.java
> +	private LogbackEventMatcher(String description, @Nullable Level theLevel,
Done

2023-05-18 14:42 UTC, merged