refactoring nickname matching
hapifhir/hapi-fhir pull request #4918
Opened 2023-05-18 20:36 UTC by TipzCM

closes #4917

2023-05-26 18:48 UTC, lukedegruchy approved these changes

2023-05-26 18:48 UTC, lukedegruchy commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/fieldmatchers/DateTimeWrapper.java
> +			myPrecision = ((org.hl7.fhir.dstu3.model.BaseDateTimeType) theDate).getPrecision();
Nitpick:  why not cast these once to a variable?

2023-05-26 18:48 UTC, lukedegruchy commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/models/MatchTypeEnum.java
> +//	CAVERPHONE1(new HapiStringMatcher(new PhoneticEncoderMatcher(PhoneticEncoderEnum.CAVERPHONE1))),
Did you mean to comment about all of this code, including the methods?

2023-05-26 18:48 UTC, lukedegruchy commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcherR4Test.java
> +	// it relies on matcher being null (is this a reasonable assumption?)
Did you mean to leave this TODO and to leave much of the test commented out?

2023-05-26 19:08 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcher.java
> +			boolean matches = matcher.matches(theLeftValue, theRightValue, getExtraMatcherParams());
changed

2023-05-26 19:11 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcher.java
> +		MatchTypeEnum matchTypeEnum = null;
Yup. i get there's other ways to do it, but i prefer the more verbose here because it makes the business logic a lot clearer.

If you want, i can change it though.

2023-05-26 19:22 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameServiceFactory.java
> +	public void setNicknameMap(Map<String, Collection<String>> theMap) {
i'll add some code to handle this case.

Thanks, nice catch

2023-05-26 19:24 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/fieldmatchers/DateTimeWrapper.java
> +			myPrecision = ((org.hl7.fhir.dstu3.model.BaseDateTimeType) theDate).getPrecision();
updated

2023-05-26 19:24 UTC, TipzCM commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcherR4Test.java
> +	// it relies on matcher being null (is this a reasonable assumption?)
oops. thanks!

removed

2023-05-26 19:34 UTC, lukedegruchy commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcher.java
> +		MatchTypeEnum matchTypeEnum = null;
That's fine.

2023-05-26 20:44 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameServiceFactory.java
> +	public void setNicknameMap(Map<String, Collection<String>> theMap) {
done

2023-05-26 20:46 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/models/MatchTypeEnum.java
> +//	CAVERPHONE1(new HapiStringMatcher(new PhoneticEncoderMatcher(PhoneticEncoderEnum.CAVERPHONE1))),
Yes. i meant to delete it

2023-05-26 20:48 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameServiceFactory.java
> +		if (myNicknameSvc == null) {
i don't think so. It's mostly reading in a file and populating it. But i put on a synchronized method just in case. (it's only called in a few places)

2023-05-30 20:04 UTC, tadgh requested changes
I really appreciate your effort in working on this feature, and I can see its potential usefulness. However, I do have a few concerns that I would like to discuss:

    Significant API changes: It seems like there are some significant changes to the API.

    Proxy class for MdmMatcherJson: I noticed the introduction of a proxy class for MdmMatcherJson. Is there a specific reason why this additional class is necessary? It would be great to explore if we can simplify the code by removing it.

    Factory that builds a singleton: I'm a bit confused about the need for a factory that builds a singleton. Could you provide some more context or reasoning behind this design choice?

    Switching from Enum with arguments to a simple Enum with a large switch statement: I understand that this change may be necessary due to the requirement of injecting a bean into the 'nickname' style Enum. However, it does introduce a significant change to the API surface for supporting a relatively small feature. Have we considered alternative design approaches that would achieve the same goal without such a substantial API change?

    documentation and explanation: I couldn't find any documentation changes or an explanation of how to actually use this new 'non-hard-coded' feature in both the pull request and the related issue. Considering the sizeable 1700 line diff, it would be extremely helpful to provide detailed information on what was implemented and why in the pull request description. This will enable reviewers to provide more meaningful insights. Also, I see that we have provided a CDR way to do this, but it would be nice to have docs in HAPI-FHIR for how to override our names.csv that is builtin.

2023-05-30 20:17 UTC, TipzCM commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmCommonConfig.java
> +		 */
removed. was mostly there as an alternative idea if someone else came along and thought it was unworkable as-is

2023-05-30 20:41 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/rules/matcher/IMatcherFactory.java
> +	IMdmFieldMatcher getFieldMatcherForEnum(MatchTypeEnum theMdmMatcherEnum);
renamed

2023-05-30 20:52 UTC, TipzCM commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/svc/MdmResourceFieldMatcherR4Test.java
> +//			.thenReturn(new NameMatcher(ourFhirContext, MdmNameMatchModeEnum.ANY_ORDER));
removed

2023-05-30 20:54 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameInterceptor.java
> +		myNicknameSvcFactory = theNicknameSvc;
renamed

2023-05-31 19:28 UTC, TipzCM commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/matcher/StringMatcherR4Test.java
> +	}
Refactored and replaced

2023-05-31 19:28 UTC, TipzCM commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/rules/svc/ResourceMatcherR4Test.java
> +			.thenReturn(new HapiStringMatcher());
removed mokcing

2023-05-31 22:46 UTC, tadgh approved these changes

2023-06-01 13:09 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameServiceFactory.java
> +				Resource nicknameCsvResource = new ClassPathResource("/nickname/names.csv");
We don't load them, but there are licence files there that are associated directly with the names.csv file. So moving that file out would make it less obvious where they belong.

This is also how it currently was (this is not a code change).

2023-06-01 13:12 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/IMdmSettings.java
> +	default Map<String, Collection<String>> nicknameMap() {
changed

2023-06-01 15:42 UTC, TipzCM commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/nickname/NicknameServiceFactory.java
> +		if (myNicknameSvc != null) {
i've added an assert. but i'm not sure there's a better way around this without breaking smile or existing implementations (but i'm open to ideas)

2023-06-02 18:04 UTC, merged

2023-10-08 22:48 UTC, gmartelly commented
@TipzCM When I turn on MDM in the application.yaml for the hapi-fhir-jpaserver I get the following error:

Parameter 2 of method matcherFactory in ca.uhn.fhir.jpa.mdm.config.MdmCommonConfig required a bean of type 'ca.uhn.fhir.jpa.nickname.INicknameSvc' that could not be found.


Action:

Consider defining a bean of type 'ca.uhn.fhir.jpa.nickname.INicknameSvc' in your configuration.

---
This is using hapi-fhir version 6.8