Resolve 4952 PUT requests for resources that don't exist get created in sequential format rather than abiding by the ResourceServerIdStrategy
hapifhir/hapi-fhir pull request #4953
Opened 2023-06-01 20:14 UTC by TynerGjs

2023-06-07 20:53 UTC, lukedegruchy approved these changes

2023-06-07 20:53 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4UpdateTest.java
> +import ca.uhn.fhir.jpa.api.model.DaoMethodOutcome;
Unused import

2023-06-07 20:53 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4UpdateTest.java
> +import org.apache.derby.impl.store.access.btree.index.B2INoLocking;
Unused import

2023-06-08 11:58 UTC, epeartree requested changes

2023-06-08 11:58 UTC, epeartree commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +		Patient p = new Patient();
line 368 are is not needed.  please remove;

2023-06-08 11:58 UTC, epeartree commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +		} catch (IllegalArgumentException exception){
it would be useful to know what was the id in the error message instead of just 'it's not uuid'.  please print the value of the id.

2023-06-08 11:58 UTC, epeartree commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +	@Test
a test name should convey what the test is doing without having to read the test.  that way, u can scan to a test file much faster to find if a condition is tested or not.  also, it helps understand if what the test is doing is correct.  

  let's rework the name a bit:
`testCreateWithConditionalUpdate_withUuidAsServerResourceStrategyAndNoIdProvided_uuidAssignedAsResourceId`

what do u think of that? do u need to read the test still?

2023-06-08 13:42 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4UpdateTest.java
> +import ca.uhn.fhir.jpa.api.model.DaoMethodOutcome;
unused imports removed

2023-06-08 13:42 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4UpdateTest.java
> +import org.apache.derby.impl.store.access.btree.index.B2INoLocking;
unused imports removed

2023-06-08 14:00 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +		Patient p = new Patient();
removed

2023-06-08 14:01 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +		// execute
Changed to `getIdPart`. Thanks!

2023-06-08 14:06 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4952-put-requests-for-resources-that-dont-exist-get-created-in-sequential-format-rather-than-abiding-by-the-resourceserveridstrategy.yaml
> +issue: 4952
Thanks! I really need to get better at summarizing for the changelog..

2023-06-08 14:06 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-dstu2/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2UpdateTest.java
> +	@Test
Indeed! I will start to creating more descriptive test names. Thanks for the tip!

2023-06-08 16:38 UTC, epeartree approved these changes

2023-06-08 16:38 UTC, merged