4968 mdm throws nonsensical error when updating resources after mdm clear
hapifhir/hapi-fhir pull request #4975
Opened 2023-06-09 19:15 UTC by jdar8

Closes #4968

2023-06-12 16:46 UTC, lukedegruchy requested changes

2023-06-12 16:46 UTC, lukedegruchy commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java
> +				ourLog.error("Old golden resource was null while updating MDM links with new golden resource. It is likely that a $mdm-clear was performed without a $mdm-submit. Link will not be updated.");
Why did you decide not to throw another Exception here?   The client will still see the NullPointerException in the logs as before, just with an extra error message before.   I see no reason to continue execution here.

2023-06-12 16:52 UTC, jdar8 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java
> +				ourLog.error("Old golden resource was null while updating MDM links with new golden resource. It is likely that a $mdm-clear was performed without a $mdm-submit. Link will not be updated.");
The NPE is thrown in `linkToNewGoldenResourceAndFlagAsDuplicate()` in the else statement, so it will not be seen by the client. I can definitely change to an exception with HAPI error code though

2023-06-12 16:58 UTC, jdar8 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java
> +				ourLog.error("Old golden resource was null while updating MDM links with new golden resource. It is likely that a $mdm-clear was performed without a $mdm-submit. Link will not be updated.");
If I add a HAPI error code, I think I will also change it to an exception, as it seems like the HAPI error codes are only used with exceptions and not with log error messages

2023-06-12 17:00 UTC, lukedegruchy commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java
> +				ourLog.error("Old golden resource was null while updating MDM links with new golden resource. It is likely that a $mdm-clear was performed without a $mdm-submit. Link will not be updated.");
I'm suggesting that you throw an InternalErrorException in this case, with a HAPI-****, rather than to simply log an error.

2023-06-12 17:13 UTC, lukedegruchy commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java
> +	public void testClearAndUpdateResource_WithoutMdmSubmit_LogsError() {
Suggestion, not crucial:  try adding the same test but with $mdm-submit and assert that the request completes without an error.

2023-06-12 17:14 UTC, lukedegruchy commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4968-fix-MDM-throws-nonsensical-error-when-updating-resources-after-mdm-clear.yaml
> +title: "Previously, when performing a `$mdm-clear` followed by an update to an existing resource without doing the required `$mdm-submit` first, a non-descriptive NullPointerException was thrown. To
Please don't forget to update the changelog with the new solution

2023-06-12 17:39 UTC, jdar8 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4968-fix-MDM-throws-nonsensical-error-when-updating-resources-after-mdm-clear.yaml
> +title: "Previously, when performing a `$mdm-clear` followed by an update to an existing resource without doing the required `$mdm-submit` first, a non-descriptive NullPointerException was thrown. To
ahh right, updated it. thanks!

2023-06-12 17:39 UTC, jdar8 commented on hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java
> +	public void testClearAndUpdateResource_WithoutMdmSubmit_LogsError() {
added new test with submit and ensure expected number of links are created

2023-06-12 17:43 UTC, lukedegruchy approved these changes

2023-06-14 01:22 UTC, tadgh approved these changes

2023-06-20 18:41 UTC, michaelabuckley approved these changes

2023-06-20 18:41 UTC, merged