Unit test and bug fix
hapifhir/hapi-fhir pull request #5012
Opened 2023-06-20 14:56 UTC by LalithE

Added unit test and bug fix to ensure no two partitions with the same ID cannot be created.

2023-06-20 15:22 UTC, davidraeside commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +			if(i.getId()==thePartition.getId()){
You should use i.getId().equals(thePartition.getId()) when not dealing with primitive data types.

2023-06-20 15:30 UTC, StevenXLi commented
You need to add a changelog

2023-06-20 15:48 UTC, LalithE commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +			if(i.getId()==thePartition.getId()){
will do thank you

2023-06-20 17:39 UTC, TipzCM requested changes

2023-06-20 17:39 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +			if(i.getId().equals(thePartition.getId())){
Q:

Isn't PartitionEntity.Id a unique field? How are these duplicate partitions being created at all?

This validation is also used for updates to partition (which should expect a duplicate id, since it's updating an existing one).

2023-06-20 17:39 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/partition/PartitionManagementProviderTest.java
> +		verify(myPartitionConfigSvc, times(0)).createPartition(any(), any());
can also use `never()` but that's a nitpick

2023-06-21 11:48 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +			if(i.getId().equals(thePartition.getId())){
I agree with this, its an `@Id` column, which means its a primary key. Primary keys are unique. It should be impossible to make 2 requests, which results in 2 individual entries in the partition table with the same ID. 

What actually happens in the test before you made this change? I would like to see the actual database entries.

2023-06-21 11:48 UTC, tadgh requested changes

2023-06-21 11:48 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +		List<PartitionEntity> allPartitions = myPartitionDao.findAll();
issue: myPartitionDao.findById() does what you want to do, but without having to iterate over every partition in the system.

2023-06-21 17:19 UTC, LalithE commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +			if(i.getId().equals(thePartition.getId())){
Yes, I misplaced the fix completely. I have now created a new method to deal with this. The issue was with two partitions being created not with the process of updating a partition. Sorry for the confusion.

2023-06-21 23:03 UTC, tadgh requested changes

2023-06-22 00:44 UTC, LalithE commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/partition/PartitionLookupSvcImpl.java
> +		List<PartitionEntity> allPartitions = myPartitionDao.findAll();
Agreed, so I have removed that from the code.

2023-06-22 01:05 UTC, tadgh approved these changes

2023-06-22 01:05 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/5011-partitioning-can-create-more-than-one-partition-with-same-id.yaml
> +title: "Fixed bug that allowed creation of two partitions with the same id"
issue: This is not an accurate statement anymore given our understanding of this bug. this should probably read: 
"Previously, if a partition was created with an ID that was alrady in use, it would overwite blah blah blah. now attempting to overwrite returns 400"

2023-06-22 15:17 UTC, TipzCM approved these changes

2023-06-22 15:23 UTC, merged