GenericClient POST paging support
hapifhir/hapi-fhir pull request #5013
Opened 2023-06-20 15:05 UTC by volodymyr-korzh

In order to support HTTP POST method for paging, enhanced GenericClient.GetPageInternal class to execute both GET or POST paging requests.

2023-06-20 17:14 UTC, epeartree requested changes

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> -		this(false, false);
not required.  please remove.

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +	private RestServerR4Helper(boolean theInitialize, boolean theTransactionLatchEnabled, boolean theExecutePostPagingRequestsEnabled) {
same here, no need for that. u have a setting method below and that's enough.  GET is the norm and if someone will use POST, they can use the setter.

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +	public void enableExecutePostPagingRequests(boolean theExecutePostPagingRequestsEnabled) {
rename to setHttpMethodForPagingRequest(PageStyle thePageStyle).

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +		private boolean myExecutePostPagingRequestsEnabled;
private PageStyle myPageStyle = PageStyle.GET;

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +			myExecutePostPagingRequestsEnabled = theExecutePostPagingRequestsEnabled;
the above is not needed.

2023-06-20 17:14 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +			// emulate a GET request invocation in the case of a POST paging request, as POST paging is not supported by FHIR RestServer
no need for the if/else if u use myPageStyle.

2023-06-20 17:56 UTC, volodymyr-korzh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/api/PageStyleEnum.java
> + */
I choose `PageStyleEnum` class name in accordance to similar logic related to search request invocation, see `SearchStyleEnum`. But let me know if you think that `PageTypeEnum` is more appropriate class name

2023-06-20 19:43 UTC, volodymyr-korzh commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/method/HttpSimplePostClientInvocation.java
> +/*
Great suggestion. Fixed

2023-06-20 19:44 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +			myExecutePostPagingRequestsEnabled = theExecutePostPagingRequestsEnabled;
You are right, removed

2023-06-20 19:45 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +		private boolean myExecutePostPagingRequestsEnabled;
Fixed.

2023-06-20 19:45 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +	public void enableExecutePostPagingRequests(boolean theExecutePostPagingRequestsEnabled) {
renamed

2023-06-20 19:46 UTC, volodymyr-korzh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/gclient/IGetPageTyped.java
> +
changed to usingMethod

2023-06-20 19:47 UTC, volodymyr-korzh commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/impl/GenericClient.java
> +			IClientResponseHandler binding = new ResourceResponseHandler(myBundleType, getPreferResponseTypes());
Looks much clearer, fixed

2023-06-20 19:47 UTC, volodymyr-korzh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/5008-generic-client-post-paging-requests-support.yaml
> +jira: SMILE-6727
Fixed

2023-06-20 19:48 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +			// emulate a GET request invocation in the case of a POST paging request, as POST paging is not supported by FHIR RestServer
removed if/else. fixed

2023-06-20 19:55 UTC, volodymyr-korzh commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/api/PageStyleEnum.java
> + */
maybe PageStyleEnum -> PagingRequestType ?

2023-06-21 11:49 UTC, epeartree commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/api/PageStyleEnum.java
> + */
i'd settle for PagingHTTPMethodEnum.  <-- expresses what the enum is doing  without having to look at its component or read comments.  SearchStyleEnum is different.  searchStyleEnum is not use to make an http request but to make conditional branching  while processing a search request that which can be expressed 3 different ways.

2023-06-21 11:50 UTC, epeartree approved these changes

2023-06-21 12:03 UTC, epeartree commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> -			}
`super.handleRequest(myPageStyle);`

2023-06-21 14:05 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> -			}
Changed to `super.handleRequest(myPagingHttpMethod.getRequestType(), request, response);`. We can't reuse RequestTypeEnum names in PagingHttpMethodEnum but we can take these values in PagingHttpMethodEnum constructor and use them like a mapping.

2023-06-21 14:06 UTC, volodymyr-korzh commented on hapi-fhir-client/src/main/java/ca/uhn/fhir/rest/client/method/HttpSimpleClientInvocation.java
> -		IHttpRequest retVal = createHttpRequest(myUrl, theEncoding, RequestTypeEnum.GET);
Changed to `IHttpRequest retVal = createHttpRequest(myUrl, theEncoding, myPagingHttpMethod.getRequestType());`. We can't reuse RequestTypeEnum names in PagingHttpMethodEnum but we can take these values in PagingHttpMethodEnum constructor and use them like a mapping.

2023-06-22 12:42 UTC, jmarchionatto approved these changes
Looks good! Approved with a question

2023-06-22 12:42 UTC, jmarchionatto commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +		private PagingHttpMethodEnum myPagingHttpMethod = PagingHttpMethodEnum.POST;
Isn't too much making POST the default? What is the reason?

2023-06-22 14:04 UTC, volodymyr-korzh commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/RestServerR4Helper.java
> +		private PagingHttpMethodEnum myPagingHttpMethod = PagingHttpMethodEnum.POST;
You are right.
I have changed it to GET, as logic in RestServerR4Helpler may be confusing if we set `myPagingHttpMethod = PagingHttpMethodEnum.POST;`.
Later, for doPost method in RestServerR4Helpler we are checking what type of paging method we have, and emulating doGet, if paging method is POST.
`RequestTypeEnum requestType = myPagingHttpMethod == PagingHttpMethodEnum.POST ? RequestTypeEnum.GET : RequestTypeEnum.POST;`
`super.handleRequest(requestType, request, response);`

2023-06-22 19:28 UTC, merged