adding pointcuts for mdm operations
hapifhir/hapi-fhir pull request #5116
Opened 2023-07-21 14:35 UTC by TipzCM

closes #5090

2023-07-21 20:04 UTC, tadgh requested changes

2023-07-21 20:04 UTC, tadgh commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +	private long synchronousMdmSubmitJob(
recommend reworking this method as it is quite confusing. it: 
1. If an ID is present, we add it as a URL and submit. 
2. Otherwise, if theres a resource type, we submit that, maybe, depending on its resource type. 
3. If neither 1 or 2 is true, then we submit all mdm-typed resource types. 

I recommend:
1. remove the word job from this method, as it is not a job 
2. make explicit the three submission routes, by breaking them into three subfunctions: 
         - submit single ID
         - submit resource type with criteria
         - submit all. 

Then this top-level method can just route to the correct subfunction depending on what it finds in its parameters.

2023-07-21 20:17 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/5090-adding-mdm-operation-pointcuts.yaml
> +issue: 5090
adding

2023-07-21 20:25 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/model/MdmOperationBaseParams.java
> +}
updated

2023-07-21 20:27 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +					);
removed

2023-07-21 20:29 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +			if (theResourceType.equals(PATIENT_RESOURCE)) {
That was what i originally did, but they do get rejected deeper down.

I'm not 100% certain on the idea behind this. I'm guessing it's because patients are always allowed into an MDM ruleset, while other resources aren't necessarily.

So i wrote it to maintain current code flow. Even though it looks a bit silly.

2023-07-21 20:36 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +	private long synchronousMdmSubmitJob(
done

2023-07-21 20:39 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/MdmProviderDstu3Plus.java
> +	// search for matches to the provided resource
added full documentation

2023-07-21 20:55 UTC, TipzCM commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmLinkCreateSvcImpl.java
> +		}
updated

2023-07-21 20:57 UTC, TipzCM commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/GoldenResourceMergerSvcImpl.java
> +			myInterceptorBroadcaster.callHooks(Pointcut.MDM_MERGE_GOLDEN_RESOURCES, params);
done

2023-07-21 20:58 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java
> +	 * This hook is invoked when link histories are queried.
added more documentation

2023-07-21 21:08 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java
> +	MDM_CREATE_LINK(
updated.

Changed all but the MDM_SUBMIT and MDM_CLEAR (since those hooks are a little more ambiguous about where they are invoked).

Added additional documentation to address this.

2023-08-01 15:35 UTC, tadgh approved these changes

2023-08-02 20:38 UTC, merged