5138 enhance existing historical link with mactchResultMap field
hapifhir/hapi-fhir pull request #5213
Opened 2023-08-17 16:27 UTC by jdar8

Closes #5138

2023-08-17 20:28 UTC, JasonRoberts-smile approved these changes

2023-08-17 20:28 UTC, JasonRoberts-smile commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		IBase subpart2 = ParametersUtil.createPart(myFhirContext, subpart, "matchedRules");
nitpick: these variables could have names that better reflect their contents

2023-08-17 20:28 UTC, JasonRoberts-smile commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		}
question: is this just a short-cut for efficiency? Or is there a risk that the algorithm below might give the wrong result in this scenario?

2023-08-17 21:33 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		IBase subpart2 = ParametersUtil.createPart(myFhirContext, subpart, "matchedRules");
I agree, fixed!

2023-08-17 21:47 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		}
I initially put this in as a shortcut, and to handle the `POSSIBLE_DUPLICATE` case because both the `goldenResourceId` and `resourceId` are technically golden resources. As a result, depending on how we merged the golden resources (from - to parameters), it can show up or not show up in the link history query. 

I gave this some more thought, and I think you are right, a `REDIRECT` does not have to be after a `POSSIBLE_DUPLICATE`. I can merge any two golden resources whenever I like, causing the REDIRECT relationship (a pre-existing `POSSIBLE_DUPLICATE` did not need to exist to merge). 

I should perform another query in this case to determine if `POSSIBLE_DUPLICATE` or `REDIRECT` should be returned. 

Thanks for catching this!!

2023-08-24 19:25 UTC, JasonRoberts-smile commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		}
The change seems fine to me

2023-08-31 19:43 UTC, TipzCM requested changes

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/MdmHistorySearchParameters.java
> +	private boolean myShouldFindLinksMatchingAllGoldenAndSourceIds = false;
I think it's a bit more 'elegant' to have this not be a boolean, but an enum for `AND` and `OR`, with `OR` being the default.

It's unclear that `shouldFindLinksMatchingAllGoldenAndSourceIds` means 'and these lists' and that the default is 'or theses lists' unless i dive into the code and see what's happening.

It's a minor point, but it would be nice if at least the creation of the parameters read this way.

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/model/mdmevents/MdmLinkJson.java
> +	private Set<Map.Entry<String, MdmMatchResultEnum>> myRule = new HashSet<>();
Document this line. It's not clear what a 'matchedRules' is.

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +			List<MdmLinkWithRevisionJson> result = myMdmControllerSvc.queryLinkHistory(params, theRequestDetails);
Does this work in mongo?

Do we support this feature in mongo?

(This might be a product question)

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +				.anyMatch(t -> t.getMdmLink().getMatchResult().equals(MdmMatchResultEnum.POSSIBLE_DUPLICATE));
It's an enum.

You can use `==` here.

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		if (theToMatch.getMdmLink().getMatchResult().equals(MdmMatchResultEnum.REDIRECT)) {
enums can use `==`

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +					: MdmMatchResultEnum.REDIRECT;
I'm not sure i understand why this returns this way.

Wouldn't the 'initial match result' be based on update timestamp? Why would it be different if there's a POSSIBLE_DUPLICATE?

2023-08-31 19:43 UTC, TipzCM commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmModelConverterSvcImpl.java
> +		retVal.translateAndSetRule(myMdmSettings.getMdmRules(), theLink.getVector());
What if the rules have changed since the link was created?

We're using a rules set that is created in one area with a vector value that could've been populated at another time.

How can we know if this is accurate?

2023-08-31 19:50 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +			List<MdmLinkWithRevisionJson> result = myMdmControllerSvc.queryLinkHistory(params, theRequestDetails);
We do not support `$mdm-link-history` in mongo

2023-08-31 19:57 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +					: MdmMatchResultEnum.REDIRECT;
`POSSIBLE_DUPLICATE` is different because both the `sourceResourceId` and `goldenResourceId` are actually IDs of golden resources. Here is an example: 

1. We have 2 GRs, GR/1 and GR/2
2. Duplicate link formed:
goldenResourceId: GR/1
sourceResourceId: GR/2
3. Merge from GR/2 to GR/1
4. REDIRECT link formed from merge will be as follows (the sourceResourceId is _always_ the merge "to" resource)
goldenResourceId: GR/2
sourceResourceId: GR/1
5. Query `$mdm-link-history?goldenResourceId=GR/2`
This will give the `REDIRECT` link, but it _will not_ give the original `POSSIBLE_DUPLICATE` link. So, in order to find the initial result, I need to do another query. I know it's not really elegant, but I couldn't think of a way of doing this without completely rewriting how `POSSIBLE_DUPLICATE`s are handled and stored

2023-08-31 20:04 UTC, jdar8 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmModelConverterSvcImpl.java
> +		retVal.translateAndSetRule(myMdmSettings.getMdmRules(), theLink.getVector());
If we update the rules with links already in the database, I feel like the existing links in the database would be inaccurate. If we add a rule, it's possible that we will be "missing" new links based on the new ruleset, if we remove rules, then we have links that shouldn't exist, and if we change a rule, then a link could no longer be valid. 

It would be best if the user at least do a `$mdm-submit` after changing the rules to re-evaluate resources (and better yet, a `$mdm-clear` and `$mdm-submit`). Doing this should update the vector values.

2023-08-31 20:08 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +			List<MdmLinkWithRevisionJson> result = myMdmControllerSvc.queryLinkHistory(params, theRequestDetails);
I don't think we clearly document what MDM operations are and aren't supported in Mongo anywhere. Could be something we add to the docs in the future

2023-08-31 20:10 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +				.anyMatch(t -> t.getMdmLink().getMatchResult().equals(MdmMatchResultEnum.POSSIBLE_DUPLICATE));
fixed

2023-08-31 20:10 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +		if (theToMatch.getMdmLink().getMatchResult().equals(MdmMatchResultEnum.REDIRECT)) {
changed

2023-08-31 20:28 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/api/MdmHistorySearchParameters.java
> +	private boolean myShouldFindLinksMatchingAllGoldenAndSourceIds = false;
Changed to enum+ added documentation for said enum

2023-08-31 20:33 UTC, jdar8 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/provider/BaseMdmProvider.java
> +					: MdmMatchResultEnum.REDIRECT;
And yes, in the base case (when we're not dealing with `POSSIBLE_MATCH`), it is based on the update timestamp which we do by calling `getRevisionNumber()` on line 269

2024-07-11 23:33 UTC, jdar8 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmModelConverterSvcImpl.java
> +		retVal.translateAndSetRule(myMdmSettings.getMdmRules(), theLink.getVector());
Inaccurate rules from the link history would only occur if the ruleset were changed and `$mdm-clear` is **not** run since `$mdm-clear` removes link history. 

It is not advised to change the ruleset and not run `$mdm-clear`.

2024-07-15 13:37 UTC, lukedegruchy approved these changes

2024-07-24 17:35 UTC, TipzCM approved these changes

2024-08-01 13:49 UTC, AD1306 approved these changes

2024-08-01 13:49 UTC, merged