Fixing empty last page if even results
hapifhir/hapi-fhir pull request #5229
Opened 2023-08-23 16:00 UTC by TipzCM

2023-11-16 19:51 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/ConsentEventsDaoR4Test.java
> +			IIdType obs1id = myObservationDao.create(obs1).getId();//.toUnqualifiedVersionless();
Did you mean to leave this commented out?

2023-11-16 19:52 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/ConsentEventsDaoR4Test.java
> +//			long i0 = Long.parseLong(o0.substring(o0.indexOf('/') + 1));
Did you mean to leave these commented out?

2023-11-16 19:57 UTC, michaelabuckley requested changes
the offset path looks good.  I think the changes to the saved-search path is redundant.  Can you test that path with these changes backed out?

2023-11-16 19:57 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java
> +					return toResourceList(sb, pidsSubList.subList(0, maxSize), theResponsePageBuilder);
This subList extraction would be clearer before the tx starts with the rest of the accounting.

2023-11-16 19:57 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaSearchFirstPageBundleProvider.java
> +				.execute(() -> toResourceList(mySearchBuilder, pids.subList(0, maxSize), thePageBuilder));
Same - move this extraction up with the rest of the accounting.

2023-11-16 19:57 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaSearchFirstPageBundleProvider.java
> +		int maxSize = Math.min(theToIndex - theFromIndex, pids.size());
suggestion: maybe assign pids.size() to a local to make sense of this bookkeeping.

2023-11-16 19:57 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java
> +		final List<JpaPid> pidsSubList = mySearchCoordinatorSvc.getResources(
This might be redundant here on the saved-search path.  We always read +1 there.  So we'll know it has ended and we'll update the total. Check out https://github.com/hapifhir/hapi-fhir/blob/fbc677cfd37dbb51e61a2ead69c6e84fec38be52/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java#L600-L609

2023-11-22 18:13 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/ConsentEventsDaoR4Test.java
> +			IIdType obs1id = myObservationDao.create(obs1).getId();//.toUnqualifiedVersionless();
yes. test was written wrong. just fixing it up to be more clear (and consistent with the naming it is using)

2023-11-22 18:13 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/ConsentEventsDaoR4Test.java
> +//			long i0 = Long.parseLong(o0.substring(o0.indexOf('/') + 1));
removed

2023-11-22 18:16 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java
> +					return toResourceList(sb, pidsSubList.subList(0, maxSize), theResponsePageBuilder);
updated

2023-11-22 18:18 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaSearchFirstPageBundleProvider.java
> +				.execute(() -> toResourceList(mySearchBuilder, pids.subList(0, maxSize), thePageBuilder));
updated

2023-11-22 18:22 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaSearchFirstPageBundleProvider.java
> +		int maxSize = Math.min(theToIndex - theFromIndex, pids.size());
updated

2023-11-22 18:29 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java
> +		final List<JpaPid> pidsSubList = mySearchCoordinatorSvc.getResources(
removed. i'll run the test suite and see if it was needed though

2023-11-27 16:19 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java
> +		final List<JpaPid> pidsSubList = mySearchCoordinatorSvc.getResources(
was needed - added it back

2023-11-27 16:31 UTC, michaelabuckley approved these changes

2023-11-28 20:07 UTC, closed without merging

2023-11-28 20:12 UTC, nathandoef commented
Duplicate of: https://github.com/hapifhir/hapi-fhir/pull/5506