Resolve 5262 adding new parameter strictmatch to the $mdm history link operation
hapifhir/hapi-fhir pull request #5264
Opened 2023-08-30 20:56 UTC by TynerGjs

What was done:
- added new parameter to `$mdm-link-history` on Pointcut `ProviderConstants.MDM_LINK_HISTORY`
- modified

2023-09-01 15:08 UTC, fil512 requested changes

2023-09-01 15:08 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_operations.md
> +Use the `$mdm-link-history` operation to request a list of historical entries for a given set of `goldenResourceId`s or `sourceResourceId`s.  Either parameter is optional but **at least one** must be
This doesn't seem like the correct implementation.  The API should follow REST conventions.  If both criteria are provided, then we should assume AND between them.

2023-09-01 15:08 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5262-adding-new-parameter-strictmatch-to-the-mdm-history-link-operation.yaml
> +title: "Added a new parameter `strictMatch` to $mdm-link-history operation to allow filtering the history links so that
I recommend removing the strictMatch parameter and always applying AND to all provided criteria per the REST standard.

2023-09-01 16:24 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_mdm/mdm_operations.md
> +Use the `$mdm-link-history` operation to request a list of historical entries for a given set of `goldenResourceId`s or `sourceResourceId`s.  Either parameter is optional but **at least one** must be
Yes, I too felt it's a bit weird to have "&" linking the two parameters but in fact it acts as an "or"...

2023-09-01 16:25 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5262-adding-new-parameter-strictmatch-to-the-mdm-history-link-operation.yaml
> +title: "Added a new parameter `strictMatch` to $mdm-link-history operation to allow filtering the history links so that
Would it be too large a breaking change? The same request would return different results after making this change.

2023-09-05 14:37 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5262-adding-new-parameter-strictmatch-to-the-mdm-history-link-operation.yaml
> +title: "Added a new parameter `strictMatch` to $mdm-link-history operation to allow filtering the history links so that
reverted changes and modified the default behaviour instead, please take a look when you have time!

2023-09-05 15:57 UTC, michaelabuckley commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5262-adding-new-parameter-strictmatch-to-the-mdm-history-link-operation.yaml
> +title: "Added a new parameter `strictMatch` to $mdm-link-history operation to allow filtering the history links so that
I didn't like this when we put it in in March, but we already shipped it as OR, and customers are using this.  Changing the default from OR to AND would be a breaking change.  I think we have to live with this being backwards unless you feel strongly we should break current clients.  @fil512

2023-09-05 17:10 UTC, fil512 commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5262-adding-new-parameter-strictmatch-to-the-mdm-history-link-operation.yaml
> +title: "Added a new parameter `strictMatch` to $mdm-link-history operation to allow filtering the history links so that
I seriously doubt anyone is using the broken behaviour.  We have like 1 mdm customer, and their usage of it is super limited.

2024-06-12 18:03 UTC, closed without merging