5089 cr measure refactor
hapifhir/hapi-fhir pull request #5324
Opened 2023-09-20 02:16 UTC by Capt-Mac

https://github.com/hapifhir/hapi-fhir/issues/5089

2023-09-20 17:18 UTC, JPercival requested changes

2023-09-20 17:55 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/common/IDaoRegistryUser.java
It is currently only used in test classes for loading resources into the server. I can move it to a Test class only

2023-09-20 18:00 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/config/TerminologyCacheConfig.java
> +	public ElmCacheResourceChangeListener elmCacheResourceChangeListener(
In Hapi, this is only used in EvaluationSettings on test cases. It sounds like with new changes to CR, this would also only be set & used in test cases. I think this whole class should be removed and added elsewhere

2023-09-21 16:45 UTC, JPercival approved these changes

2023-09-21 16:45 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/TestCrR4Config.java
> +		careGapsProperties.setCareGapsReporter("Organization/alphora");
suggestion: Fine for test code, but we should generally remove references to Alphora, and make sure the CDR code doesn't default to Alphora either. Setting an Org and an Author should be required config for caregaps.

2023-09-21 16:45 UTC, JPercival commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/TestCrR4Config.java
> +		CqlThreadFactory factory = new CqlThreadFactory();
question: The documentation says that this was required to support JAXB. Does it work ok if we exclude JAXB and rely only on Jackson serialization? We're planning on retiring JAXB anyway.

2023-09-21 16:47 UTC, JPercival commented
question: The test coverage for R4 is significantly better than for DSTU3. Is that just a matter of us not having content for DSTU3?

2023-09-21 16:54 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/test/java/ca/uhn/fhir/cr/r4/TestCrR4Config.java
> +		careGapsProperties.setCareGapsReporter("Organization/alphora");
Confirmed, no default is set in CDR. If left alone it fails on startup too

2023-09-22 20:14 UTC, lukedegruchy approved these changes

2023-09-22 20:14 UTC, lukedegruchy commented on hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/HtmlUtil.java
> +
Please reverse this change

2023-09-22 20:49 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/SearchConverter.java
> +			// } else if ()
should have been removed

2023-09-22 23:51 UTC, merged