adding additional logging to resource modified submitter svc
hapifhir/hapi-fhir pull request #5370
Opened 2023-10-18 15:25 UTC by TipzCM

closes #5369

2023-10-19 13:21 UTC, epeartree requested changes

2023-10-19 13:21 UTC, epeartree commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/submit/.gitkeep
do we need this empty file?

2023-10-19 13:21 UTC, epeartree commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/svc/ResourceModifiedSubmitterSvc.java
> +				} else {
u can get rid of the else block by declaring with assigning and overwriting when `resourceModifiedMessage` is nonNull.

2023-10-19 13:21 UTC, epeartree commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/svc/ResourceModifiedSubmitterSvc.java
> +				ourLog.error("Unexpected error encountered while processing resource modified message.", ex);
processed needs to be true and dont' roll back otherwise, it will try to submit the resource for ever.   after figuring out what the exception is, we can decide whether it is recoverable and keep trying or we quit on it.

2023-10-19 13:23 UTC, TipzCM commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/submit/.gitkeep
it's 0 bytes big and prevents the folder collapse. but i'll remove it :(

2023-10-19 13:26 UTC, TipzCM commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/svc/ResourceModifiedSubmitterSvc.java
> +				ourLog.error("Unexpected error encountered while processing resource modified message.", ex);
right

2023-10-20 13:56 UTC, epeartree approved these changes

2023-10-20 13:56 UTC, merged