Pass properties through to Remote Terminology Service on CodeSystem lookup
hapifhir/hapi-fhir pull request #5477
Opened 2023-11-22 06:37 UTC by codeforgreen

#5476

2023-11-22 15:27 UTC, epeartree requested changes

2023-11-22 15:27 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaResourceDaoCodeSystem.java
> +			IPrimitiveType<String> theDisplayLanguage,
new parameter theProperties is not passed down to doLookupCode?  
i might be mistaken but if we want properties to make it to remove look up, we need to pass them down.

2023-11-22 15:27 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaResourceDaoCodeSystem.java
>  			RequestDetails theRequestDetails) {
passing null always make me fringe.  please use emptyList()

2023-11-22 15:27 UTC, epeartree commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +			String theDisplayLanguage,
thePropertyValues?

2023-11-22 15:27 UTC, epeartree commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
>  				}
using thePropertyNames right away in a foreach is dangerous.  this is a public interface, ie, anyone can provide  a value of null which will lead to NPE when thePropertyNames.iterator() will be invoked.

please validate the collection at the door with 
ObjectUtil.defaultIfNull(thePropertyNames, emptyList());

2023-11-22 20:05 UTC, codeforgreen commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaResourceDaoCodeSystem.java
> +			IPrimitiveType<String> theDisplayLanguage,
Good catch. This is what I am talking about. Such bugs are not caught with the current test coverage because this is one of the classes which is not tested at all.

2023-11-22 20:06 UTC, codeforgreen commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaResourceDaoCodeSystem.java
>  			RequestDetails theRequestDetails) {
Thanks, I fully agree. I realized that at some point and did that in one place but I missed the other.

2023-11-22 20:24 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +			String theDisplayLanguage,
Thanks. I think it's best to use thePropertyNames. Please see the [documentation](http://hl7.org/fhir/R4/codesystem-operation-lookup.html), under field property it says the server will select certain additional properties for CodeSystem to return in the response and it mentions how they are turned. It's a bit weird how it's returned because they're returned as one parameter with sub-parameter one for each property and the value is also there. Although confusing, it is what it is. 
I'll look and see if I should add a comment in the code, it may be confusing for others as well how one Parameter in input translates into multiple into the output.

2023-11-22 20:25 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +			String theDisplayLanguage,
Yes, will use thePropertyNames, see above comment.

2023-11-24 14:39 UTC, jamesagnew requested changes

2023-11-24 14:39 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +			ValidationSupportParameterObject validationSupportParameterObject) {
Suggestion: I find the name `ValidationSupportParameterObject` kinda clunky, especially since it's only for this method and not others in this interface. Would `LookupCodeRequest` make more sense? That way it pairs nicely with the name of the return type too.

2023-11-24 14:39 UTC, jamesagnew commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportChain.java
>  	public LookupCodeResult lookupCode(
I would think for this class, you wouldn't want to replace the existing method, you'd want to add a new one for your new implementation. The IValidationSupportChain should have chained methods for every method on `IValidationSupport` that can be called.

2023-11-24 14:39 UTC, jamesagnew commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/CachingValidationSupport.java
>  	public LookupCodeResult lookupCode(
Similar to my comment below (or above?) on ValidationSupportChain, I would think you'd want to have a new method here, not to replace the existing ones which aren't going away.

2023-11-24 14:39 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
>  	 *                                    other method in the support chain, so that they can be passed through the entire chain. Implementations of this interface may always safely ignore this paramete
Meta-comment on this review: I don't think this is ready for merge yet - Keep in mind that:

* There are HAPI FHIR users out there who have implementations of this interface where they have coded their own implementations of the 'legacy' validateCode methods and obviously haven't implemented the new one you're adding. We need for any changes to this interface to not be a breaking change, which means that everything needs to continue to work even if people have implemented the old methods only.
* Most importantly, you need to look at any places where the legacy methods are called, and have that code try the new method and then try the old method if the new method returns null, so that you can be guaranteed that this isn't a breaking change. I note that a bunch of unit tests are failing, and that's why: currently most of the callers to this interface are still calling the old methods, but you've moved all the implementations to the new methods.

2023-11-24 14:42 UTC, jamesagnew commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_0_0/5476-pass-properties-through-remote-terminology-service-for-code-system.yaml
> +---
Recommend also adding a second changelog along the lines of:

> A new method on the `IValidationSupport` interface called `lookupCode(LookupCodeRequest)` has been added. This method replaced the existing `lookupCode` methods, which are now deprecated.

2023-11-24 14:43 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +	 * @param validationSupportParameterObject The parameters used to perform the lookup, including system and code.
Recommend adding:

```java
 * @since 7.0.0
```

2023-11-24 18:03 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
>  	 *                                    other method in the support chain, so that they can be passed through the entire chain. Implementations of this interface may always safely ignore this paramete
Thank you for the review, those are good comments. I'll update it accordingly.

2023-11-24 22:51 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
>  	 *                                    other method in the support chain, so that they can be passed through the entire chain. Implementations of this interface may always safely ignore this paramete
For second point, I'd actually updated all internal implementations to the new method, but one was missed due to some very interesting circumstances. Its `TermReadSvcImpl` lookupCode method, was missing the first parameter ValidationSupportContext which was there before, and the method was not marked as an Override. So I couldn't find it when searching for implementors. I am not sure how it worked before but once I replaced the parameters, it stopped working.
I wonder if implementing the fallback for `ValidationSupportChain` would be enough. In my opinion we would not need fallbacks for the rest of the internal implementations. Let me know if you consider otherwise. The other ones are either pass through or seem safe.

2023-11-27 18:28 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportChain.java
>  	public LookupCodeResult lookupCode(
I added a fallback in the new method as per the overall comment. Let me know if that's enough or you still feel old methods still need to live here.

2023-11-27 18:30 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/CachingValidationSupport.java
>  	public LookupCodeResult lookupCode(
I wonder if having the fallback in `ValidationSupportChain` is enough to cover the use-cases where (terminology) validation would be customized. Wondering if it would it be common for consumers to extend even `CachingValidationSupport`.

2023-11-27 20:32 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> -		return null;
Updated in lastest version. Resolving this.

2023-11-28 15:10 UTC, epeartree approved these changes

2023-11-28 21:12 UTC, merged