adding additional data to (bulk data export) parameters
hapifhir/hapi-fhir pull request #5541
Opened 2023-12-07 15:50 UTC by TipzCM

closes #5527

2023-12-14 22:51 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/BaseBatchJobParameters.java
> +	private Map<String, Object> myData;
We call this concept "userData" everywhere else, as opposed to "additionalData". It'd probably be more consistent to use that name.

2023-12-14 22:53 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/BaseBatchJobParameters.java
> +	public void setAdditionalData(String theKey, Object theValue) {
Values in this class need to be able to serialize to JSON. I'd recommend documenting that only String, Integer, and Boolean are valid value types, and adding a runtime check to make sure that only these types actually get used. This will help to catch issues early on, instead of them causing crashes later when it's hard to understand what has happened.

2023-12-14 22:56 UTC, jamesagnew commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/bulk/BulkExportJobParameters.java
> +public class BulkExportJobParameters extends BaseBatchJobParameters {
Should all of the other job parameter types be modified to also extend this new base class?

If so, we should also modify JobDefinition#setParametersType so that it uses the new mode specific base instead of just `IModelJson`.

2023-12-14 23:00 UTC, jamesagnew commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/consent/IConsentService.java
> +	default ConsentOutcome shouldIncludeResourceInExport(
I'm not following why we need a new method for this. I wouldn't expect that there would be cases where we'd want to have different consent rules between the REST API and Bulk Export. I'd recommend just using the `willSeeResource` method.

2023-12-14 23:01 UTC, jamesagnew requested changes
I don't love adding a new consent service method just for bulk exports. Recommend collapsing that.

2023-12-15 16:56 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/BaseBatchJobParameters.java
> +	private Map<String, Object> myData;
updated

2023-12-15 18:40 UTC, TipzCM commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/BaseBatchJobParameters.java
> +	public void setAdditionalData(String theKey, Object theValue) {
updated

2023-12-15 18:42 UTC, TipzCM commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/bulk/BulkExportJobParameters.java
> +public class BulkExportJobParameters extends BaseBatchJobParameters {
We could.

But considering all the other jobs are across a multitude of different modules, and not all modules even have interceptors provided in them, it's probably better to do this on a case by case basis as needed (imo).

2023-12-15 18:51 UTC, TipzCM commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/consent/IConsentService.java
> +	default ConsentOutcome shouldIncludeResourceInExport(
Unfortunately i don't know if that can be done.

The real purpose of this work is to support the $export invoked via $member-match, and allow users to control that based on the $member-match specifically.

But 2 issues:
* during bulk exports, users are not logged in (it's a batch job; no user session is available at all) - so there's not really a way for interceptor writers to even know the context of the "willSeeResource" (we don't have a RequestDetails or even a user session for that matter)
* willSeeResource has no way of having context about the job itself - like the fact that it *is* a bulk export nor the special member-match parameters provided to it when the job is first invoked.

2023-12-19 21:02 UTC, TipzCM commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/consent/IConsentService.java
> +	default ConsentOutcome shouldIncludeResourceInExport(
As discussed, this method will be removed and we'll use the willSeeResource instead

2023-12-19 21:47 UTC, jamesagnew commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/api/server/bulk/BulkExportJobParameters.java
> +public class BulkExportJobParameters extends BaseBatchJobParameters {
Makes sense - Might be a good idea to note that in the `BaseBatchJobParameters` javadoc (ie that not all parameters extend it and that it can be added as a base class on a case by case basis)

2023-12-19 22:42 UTC, jamesagnew approved these changes

2024-01-12 14:49 UTC, merged