Ld 2024 01 29 bundle patch cant handle transaction nested paramters
hapifhir/hapi-fhir pull request #5641
Opened 2024-01-29 16:25 UTC by lukedegruchy

2024-01-29 23:38 UTC, michaelabuckley requested changes
Please re-write these tests without mock.  You should be able to use the normal RuleBuilder and make normal assertions.

2024-01-29 23:38 UTC, michaelabuckley commented on hapi-fhir-server/src/test/java/ca/uhn/fhir/rest/server/interceptor/auth/RuleImplOpTest.java
> +//		ruleOp.applyRule(RestOperationTypeEnum.TRANSACTION, new SystemRequestDetails(), mockResouce, null, null, null, null);
problem: looks like the test is commented out.

2024-01-29 23:38 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/auth/FhirQueryRuleImplTest.java
> +			when(mockRuntimeResourceDefinition.getName()).thenReturn(BUNDLE);
problem:  I'm very skeptical we ever need to mock the FhirContext.  This test uses a concrete one.

2024-01-30 14:08 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/auth/FhirQueryRuleImplTest.java
> +			when(mockRuntimeResourceDefinition.getName()).thenReturn(BUNDLE);
I need to add a Bundle to a Bundle, which the BundleBuilder doesn't allow me to do.  If it does allow me to, it's not at all obvious.

2024-01-30 14:09 UTC, lukedegruchy commented on hapi-fhir-server/src/test/java/ca/uhn/fhir/rest/server/interceptor/auth/RuleImplOpTest.java
> +//		ruleOp.applyRule(RestOperationTypeEnum.TRANSACTION, new SystemRequestDetails(), mockResouce, null, null, null, null);
I forgot to revert my changes to this test after I realized I didn't have access to Parameters.

2024-01-30 16:40 UTC, michaelabuckley approved these changes
looks good.

2024-01-30 16:40 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/auth/RuleImplOpTest.java
> +public class RuleImplOpTest {
This looks nice and concrete.  Thanks.

question: does this test fail without your fix?

2024-01-30 16:43 UTC, lukedegruchy commented on hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/auth/RuleImplOpTest.java
> +public class RuleImplOpTest {
`testTransactionBundlePatchWithParameters()` fails without my fix.  The other two tests pass, as I expect them to

2024-01-30 19:23 UTC, merged