IPS API Refactor
hapifhir/hapi-fhir pull request #5682
Opened 2024-02-06 22:15 UTC by jamesagnew

This is a refactor of the IPS generation API in order to make it more flexible.

* Sourcing data from non-JPA sources is now supported
* Multiple generation strategies can be used

2024-02-08 16:49 UTC, jmarchionatto requested changes
Some questions and comments added

2024-02-08 16:49 UTC, jmarchionatto commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/jpa/section/PregnancyJpaSectionSearchStrategy.java
> +		}
Named constants would improve readability and extensibility

2024-02-08 16:49 UTC, jmarchionatto commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/strategy/MedicationNoInfoR4Generator.java
> +		// .setEffective(new
Please remove or comment why commented code stays

2024-02-08 16:49 UTC, jmarchionatto commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/jpa/section/MedicationSummaryJpaSectionSearchStrategy.java
> +public class MedicationSummaryJpaSectionSearchStrategy extends JpaSectionSearchStrategy {
Would be nice to refactor Strategies to use polymorphism instead of sequences of conditionals

2024-02-10 19:44 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/BundleBuilder.java
> +		addEntryAndReturnRequest(theResource);
Nope - This isn't actually making a substantive change in most cases, since `addEntryAndReturnRequest` does pull out the resource ID and add it to the entry.fullUrl if you don't supply one. The difference here is that the way we were doing it broke when placeholder IDs were used.

2024-02-10 19:44 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/narrative2/NarrativeGeneratorTemplateUtils.java
> +				.map(t -> t.getValue())
done

2024-02-10 19:45 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/BundleBuilder.java
> +		addEntryAndReturnRequest(theResource);
Nope - This isn't actually making a substantive change in most cases, since addEntryAndReturnRequest does pull out the resource ID and add it to the entry.fullUrl if you don't supply one. The difference here is that the way we were doing it broke when placeholder IDs were used.

2024-02-10 19:47 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/narrative2/NarrativeGeneratorTemplateUtils.java
> +public class NarrativeGeneratorTemplateUtils {
good call, done

2024-02-10 19:48 UTC, jamesagnew commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_2_0/5682-ips-api-refactor.yaml
> +   future use cases. Specifically, the section registry has been removed and folded into
Whoops! thought i had caught all of those... fixed

2024-02-10 19:58 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/generator/IpsGeneratorSvcImpl.java
> +		}
good call, done

2024-02-10 20:02 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/jpa/section/PregnancyJpaSectionSearchStrategy.java
> +		}
done

2024-02-10 23:12 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/jpa/section/IllnessHistoryJpaSectionSearchStrategy.java
> +				return true;
Good catch thanks!

2024-02-10 23:13 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/jpa/section/MedicationSummaryJpaSectionSearchStrategy.java
> +public class MedicationSummaryJpaSectionSearchStrategy extends JpaSectionSearchStrategy {
That's a good suggestion. I've reworked it to use a generic type on the search strategy and no more procedural checks.

2024-02-10 23:33 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/strategy/MedicationNoInfoR4Generator.java
> +		// .setEffective(new
Done

2024-02-11 12:48 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/api/IIpsGenerationStrategy.java
> +	 * to leake the server-generated IDs, the recommended way is to
fixed

2024-02-11 12:49 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/api/IpsSectionContext.java
> +	IpsSectionContext(IBaseResource theSubject, IIdType theSubjectId, Section theSection, String theResourceType) {
These classes are never used as hashmap keys and aren't intended to be used as such, so there would be no point.

2024-02-11 12:49 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/generator/IpsGeneratorSvcImpl.java
> +				.orElse(myGenerationStrategies.get(0));
Yeah, the intent here is to be best-effort. I'm soliciting community feedback about whether that's the best approach now, but for now that's the design.

2024-02-11 12:51 UTC, jamesagnew commented on hapi-fhir-jpaserver-ips/src/main/java/ca/uhn/fhir/jpa/ips/generator/IpsGeneratorSvcImpl.java
> +			IIpsGenerationStrategy theStrategy,
good call, done

2024-02-11 15:43 UTC, merged