5745 ready state batch2
hapifhir/hapi-fhir pull request #5764
Opened 2024-03-06 20:26 UTC by TipzCM

closes #5745

2024-03-08 18:04 UTC, michaelabuckley requested changes
It looks pretty solid.  I made a bunch of small suggestions but there is one must-fix, and one path that is too complicated:
1. We can't fetch the whole chunk in the maintenance loop.  Only the id.
2. The nested internal ifs in the callback are too complicated.  Let's figure out how to simplify those.

2024-03-08 18:08 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			myEntityManager.unwrap(Session.class).doWork(Connection::commit);
```suggestion
	public void enqueueWorkChunkForProcessing(String theChunkId, Consumer<Integer> theCallback) {
		int updated = myWorkChunkRepository.updateChunkStatus(
				theChunkId, WorkChunkStatusEnum.QUEUED, WorkChunkStatusEnum.READY);
		if (updated == 1) {
		theCallback.accept(updated);
			myEntityManager.flush();
			myEntityManager.unwrap(Session.class).doWork(Connection::commit);
```

2024-03-08 18:20 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/introduction.md
> +A Scheduled Job runs every so often (default once a minute), and does the following for each Job Instance in the database:
updated

2024-03-08 18:20 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/introduction.md
> +1. Moves any gated jobs onto their next step.
updated

2024-03-08 18:22 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/batch2_states.md
> +    [*]:
removed

2024-03-08 20:32 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		getTxBuilder().withPropagation(Propagation.REQUIRES_NEW).execute(() -> {
removed

2024-03-12 13:29 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				}
removed

2024-03-12 13:44 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			IHapiTransactionService theTransactionService) {
removed

2024-03-12 14:24 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/test/java/ca/uhn/fhir/batch2/coordinator/JobCoordinatorImplTest.java
> -		verify(myBatchJobSender, times(1)).sendWorkChannelMessage(myJobWorkNotificationCaptor.capture());
done

2024-03-12 14:25 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			myEntityManager.unwrap(Session.class).doWork(Connection::commit);
updated

2024-03-12 15:55 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +	private void enqueueReadyChunks(JobInstance theJobInstance, JobDefinition<?> theJobDefinition) {
Question: is there any reason to do this at the job level?  Could we not open a cursor on _all_ chunks in ready state and queue them?

2024-03-20 13:31 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		return myTransactionService.withSystemRequest().withRequestPartitionId(RequestPartitionId.allPartitions());
hapi transaction is removed

2024-03-21 14:08 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +	private void enqueueReadyChunks(JobInstance theJobInstance, JobDefinition<?> theJobDefinition) {
This is fine at the per-job level.

2024-03-21 14:37 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	Stream<WorkChunk> fetchAllWorkChunksForJobInStates(
fatal performance: This loads all data into ram.  All we need for queue message is chunkId and stepId.  Either replace with Pair<chunkId,stepId>, WorkChunk with no data.

2024-03-22 21:17 UTC, michaelabuckley approved these changes
No show-stoppers.
I think the new interator class has already been written.
Love the new metadata view. Much more explicit that the old no-data path.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	@Deprecated
problem: deprecations should describe their replacement.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
>  	public boolean canAdvanceInstanceToNextStep(String theInstanceId, String theCurrentStepId) {
suggstion: I think this is all dead code.  There are tests calling this, but no runtime path.  Can we move the tests to use the method in the JobInstanceProcessor?  Or just delete the tests and this method.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/testjob/models/FirstStepOutput.java
> +public class FirstStepOutput implements IModelJson {
question:  What are these for?  They don't seem related to READY, and have no javadoc.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/test/java/ca/uhn/fhir/batch2/coordinator/JobDataSinkTest.java
> +		verify(myBatchJobSender, never()).sendWorkChannelMessage(any());
performance: this will add a minute of latency to every non-gated step.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +public class JobMaintenanceStateInformation {
trivial: javadoc, pls.  Something like: initial and expected states and step ids for some chunks.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +   			2|READY,2|QUEUED
praise: These are pretty easy to read.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +   		2|READY
Nice!

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	@Disabled
problem: why disabled?  Add a string to the annotation as a comment.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +     		# READY chunks should transition; others should stay
so nice to read.

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	default void test_ungatedJob_advancesSteps() throws InterruptedException {
Is this the write title?  Maybe test_ungatedJob_queuesReadyChunks

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +		3|GATED|READY
Nice.  This will help Tyner

2024-03-22 21:17 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	default void test_gatedJob_stepReady_advances() throws InterruptedException {
question: do we need a version of this with the old codes?  Maybe I'm confused.  If this is step advance, then the legacy chunks might start in QUEUED.

2024-03-25 13:23 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2WorkChunkMetadataView.java
> +public class Batch2WorkChunkMetadataView implements Serializable {
added

2024-03-25 13:58 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +	class ReadyChunkIterator implements Iterator<WorkChunkMetadata> {
removed

2024-03-25 14:08 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +		enableMaintenanceRunner(false);
moved to a beforeeach

2024-03-25 14:23 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	@Disabled
i disabled it so i wouldn't get a bunch of failures. it's mostly a test for tyner. i'll let him know to remove it though

2024-03-25 14:26 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	default void test_ungatedJob_advancesSteps() throws InterruptedException {
chanbged

2024-03-26 00:40 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/Batch2WorkChunkMetadataView.java
> +public class Batch2WorkChunkMetadataView implements Serializable {
done

2024-03-26 00:40 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +	class ReadyChunkIterator implements Iterator<WorkChunkMetadata> {
done (using the paging iterator)

2024-03-26 00:40 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IWorkChunkErrorActionsTests.java
> +public interface IWorkChunkErrorActionsTests extends IWorkChunkCommon, WorkChunkTestConstants {
i'm sorry :(

2024-03-26 00:48 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> -		if (!myGatedExecution) {
added

2024-03-26 00:52 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/ReductionStepExecutorServiceImpl.java
> +		if (theChunk.getStatus() != WorkChunkStatusEnum.READY) {
I added a check for COMPLETED (legacy) as well as READY (new)

Added a comment for this too

2024-03-26 00:57 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	@Deprecated
added

2024-03-26 00:59 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
>  	public boolean canAdvanceInstanceToNextStep(String theInstanceId, String theCurrentStepId) {
oops i should've read this first. the above comment is no longer relevant if i delete it.

but for context, i had only left it as Deprecated because i am aware this is a public repo and i didn't want to remove the API. but it's fine - gone

2024-03-26 01:02 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/testjob/models/FirstStepOutput.java
> +public class FirstStepOutput implements IModelJson {
added documentation.

But for context, these are just sample output objects used for demo jobs. I moved them out of a test class so they can be accessed by more than just those tests.

2024-03-26 01:07 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/test/java/ca/uhn/fhir/batch2/coordinator/JobDataSinkTest.java
> +		verify(myBatchJobSender, never()).sendWorkChannelMessage(any());
added back

2024-03-26 01:14 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +public class JobMaintenanceStateInformation {
added some better doumentation

2024-03-26 01:27 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	Page<WorkChunkMetadata> fetchAllWorkChunkMetadataForJobInStates(
i've updated the internal no-data path to use the metadata view. but i'll leave the normal data rich path alone.

2024-06-12 17:40 UTC, closed without merging