Resolve 5818 Update Batch2 framework with GATE_WAITING state
hapifhir/hapi-fhir pull request #5819
Opened 2024-04-03 15:01 UTC by TynerGjs

What was done: 
- Implemented GATE_WAITING state for the batch2 state machine.
- This will be the initial status for all workchunks of a gated job.
- made compatible with the equivalent "fake QUEUED" state in the Old batch2 implementation.
- Updated corresponding docs.
- added corresponding tests and changelog

2024-04-03 17:29 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		runInTransaction(() -> assertEquals(LAST_STEP_ID, myJobInstanceRepository.findById(instanceId).orElseThrow(IllegalArgumentException::new).getCurrentGatedStepId()));
might be better to do this all in a single transaction?

2024-04-03 17:29 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		if (WorkChunkStatusEnum.READY.equals(theExpectedStatusAfterTransition)) {
it's an enum. use == please.

2024-04-03 17:34 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/AbstractIJobPersistenceSpecificationTest.java
> +        if (jobDefinition.isGatedExecution()) {
is there a formatting issue here?

2024-04-03 17:35 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/AbstractIJobPersistenceSpecificationTest.java
> +			instance.setCurrentGatedStepId(jobDefinition.getFirstStepId());
I knwo you are doing this for convenience, but i think unless this is affecting many many tests, i'd opt to have the tests set this value on the returned instance object itself.

The test should know what step it wants, after all.

It also makes it clear for the person reading the test (where it matters most)

2024-04-03 17:39 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +		2|READY,2|QUEUED
i'm not sure about this test case here.

This test is called `gatedStep2NotReady_notAdvance`

But this is clearly an advance since you have a final state that is.... different.

Not saying the test is unnecessary, but it doesn't belong here.

2024-04-03 17:41 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +			// ignore the last step
why?

Comments should explain the business logic, not the code. i can see you're ignoring the last step, but i'm not sure why

2024-04-03 17:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * @return
you should explain what the return value is.

2024-04-03 17:42 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * Update all chunks of the given step id for the given job from
from....?

Don't leave me hanging! From what?

----

I also wonder if this method is a bit 'too powerful'.

The advancing of the statemachine should not be just by instanceid and step. it should be a bit more controlled.

2024-04-03 17:49 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			isEnqueue = true;
i like that you added comments to each if statment.

But because of the way this method is being invoked (after the canAdvanceGatedJob), and there's no clear way to link these, it might be helpful to add documentation to explain what states you expect here and why.

2024-04-03 19:36 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +						"Updated {} chunks of gated instance {} for step {} from fake QUEUED to READY.",
"legacy" is a good euphemism.

2024-04-03 20:35 UTC, michaelabuckley requested changes

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +	public void updateAllChunksForStepWithStatus_forGatedJob_updatesChunkStatus() {
problem: Missing a chunk in QUEUED.  We might have mixed data here.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		runInTransaction(() -> assertEquals(WorkChunkStatusEnum.GATE_WAITING, myWorkChunkRepository.findById(firstChunkId).orElseThrow(IllegalArgumentException::new).getStatus()));
problem:  This is too hard to read.  Pleae combine the transaction lambdas, and introduce a getChunkOrThrow() helper to shorten these lines.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +	private String storeWorkChunk(String theJobDefinitionId, String theTargetStepId, String theInstanceId, int theSequence, String theSerializedData, boolean theGatedExecution) {
suggestion: do we we need the boolean?  The job definition is registered - we can check.
Otherwise, consider having two methods - storeWorkChunk and storeGatedWorkChunk.  Booleans make terrible parameters.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IWorkChunkStorageTests.java
>  		enableMaintenanceRunner(false);
minor: should enableMaintenanceRunner just be in a @BeforeEach instead of every test?

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IWorkChunkStorageTests.java
>  		enableMaintenanceRunner(false);
trivial: I am skeptical this is better as a parameterized test instead of two named tests.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	int updateAllChunksForStepWithStatus(
serious problem:  This method allows all sorts of transitions that aren't legal.  Is the new status ever not READY?  I think the old status is always QUEUED or GATE_WAITING too.  Please don't expose persistence methods that could break the state machine.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> +				myGatedExecution);
minor: it is clumsy to be passing around the JobInstance and JobDefinition by individual fields when we have the JobInstance and JobDefinition objects.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		if (workChunkStatuses.equals(Set.of(WorkChunkStatusEnum.GATE_WAITING)) && theWorkCursor.isFirstStep()) {
question: Why would a first step ever be in GATE_WAITING state?  Shouldn't we start in READY.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			if (!theIsGatedExecutionBool && (theJobDefinition.isGatedExecution() || jobWorkCursor.isReductionStep())) {
problem: what does this method even do if this is false?  It looks like a no-op.  Can you push the boolean evaluation out to the caller and decide when to call the method?

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> -		if (workChunkStatuses.equals(Set.of(WorkChunkStatusEnum.READY))) {
question: I doubt that set equality is the right test here.  Shouldn't this be something like `containsAll()`?

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		// all workchunks for gated jobs should be turned to QUEUED immediately after they are set to READY
problem:  This comment makes me doubt our transaction boundary.  We must _guarantee_ that this doesn't happen via transaction boundaries.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		if (workChunkStatusesForCurrentStep.equals(Set.of(WorkChunkStatusEnum.GATE_WAITING))
problem: these different cases should almost certainly be separate methods.  They have radically different behaviour.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			int numChanged = myWorkChunkRepository.updateAllChunksForStepWithStatus(
performance: these two calls should be a single db call.  Please change to take a set of allowed prior states and use an `in()` clause in the query.

2024-04-03 20:35 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			if (instance.getCurrentGatedStepId().equals(theNextStepId)) {
problem: I don't see a test for this branch.

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/batch2_states.md
> +   QUEUED          --> READY         : on gate release - gated (for compatibility with old "fake QUEUED" state)
added snapshot number

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/introduction.md
> +- Batch Work Chunk with status `READY`/`GATE_WAITING`: this describes the first "chunk" of work required for this job. The first Batch Work Chunk contains no data. The initial status of the work chun
used recommended text

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/introduction.md
> +1. Moves all `READY` work chunks into the `QUEUED` state and publishes a message to the Batch Notification Message Channel to inform worker threads that a work chunk is now ready for processing. For
moved to separate point and reordered the points

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			if (instance.getCurrentGatedStepId().equals(theNextStepId)) {
added new test case

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			// In the old code, gated jobs' workchunks are created in status QUEUED but not actually queued for the
added version number

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +						"Updated {} chunks of gated instance {} for step {} from fake QUEUED to READY.",
used "legacy" and added version number

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +			WorkChunkStatusEnum theOldStatus) {
restricted this method to only turn GATE_WAITING and QUEUED to READY, and removed the last two parameters.

2024-04-10 13:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		mySvc.advanceJobStepAndUpdateChunkStatus(instanceId, nextStepId);
moved to ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImplTest and verified the return value

2024-04-10 13:19 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +	}
added new test case

2024-04-10 13:19 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		mySvc.updateAllChunksForStepWithStatus(instanceId, nextStepId, expectedNewStatus, expectedOldStatus);
verified return value

2024-04-10 13:19 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/AbstractIJobPersistenceSpecificationTest.java
> +        if (jobDefinition.isGatedExecution()) {
yes... seems the IJ rendering issue happened again, reformatted

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * Update all chunks of the given step id for the given job from
restricted this method to only transition from QUEUED and GATE_WAITING to READY

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	int updateAllChunksForStepWithStatus(
restricted this method to only transition from QUEUED and GATE_WAITING to READY

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		if (workChunkStatuses.equals(Set.of(WorkChunkStatusEnum.GATE_WAITING)) && theWorkCursor.isFirstStep()) {
changed the first step to always be READY

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		// all workchunks for gated jobs should be turned to QUEUED immediately after they are set to READY
this if branch is removed to allow only 1 code path to enqueue ready chunks :)

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			if (!theIsGatedExecutionBool && (theJobDefinition.isGatedExecution() || jobWorkCursor.isReductionStep())) {
this if branch is removed to allow only 1 code path to enqueue ready chunks :)

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		if (workChunkStatusesForCurrentStep.equals(Set.of(WorkChunkStatusEnum.GATE_WAITING))
this if branch is removed to allow only 1 code path to enqueue ready chunks :)

2024-04-10 13:23 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			isEnqueue = true;
the majority of these branches are removed to allow only 1 code path to enqueue ready chunks :)

2024-04-10 13:52 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/coordinator/JobDataSink.java
> +				myGatedExecution);
The jobDataSink does not have a field for the job definition object and instead parsed all the info out from it in the constructor. I think this might be intended when the code is first written, this pattern also applies to when creating JobWorkNotification... Should I change it so that it stores a job definition directly? If you think it is ok to do, I am happy to make it

2024-04-10 14:13 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +			// ignore the last step
Previously, this would set the current step to the latest step that appeared in the initial states. However, that is not very useful since our tests that use gated jobs all need the current step to be the step before the last step, so I skipped the last step... I see that it is probably not a good solution. But I also find that automatically setting the current step by judging from the initial states might not be very useful. Should I introduce a new field in the initial states to allow the current step to be declared?

2024-04-10 14:17 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		runInTransaction(() -> assertEquals(WorkChunkStatusEnum.GATE_WAITING, myWorkChunkRepository.findById(chunkIdFirstStep).orElseThrow(IllegalArgumentException::new).getStatus()));
added suggested method

2024-04-10 14:18 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		runInTransaction(() -> assertEquals(WorkChunkStatusEnum.GATE_WAITING, myWorkChunkRepository.findById(firstChunkId).orElseThrow(IllegalArgumentException::new).getStatus()));
added suggested method

2024-04-10 15:41 UTC, TipzCM requested changes

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		String chunkIdSecondStep2 = storeWorkChunk(JOB_DEFINITION_ID, LAST_STEP_ID, instanceId, 0, null, true);
Did you consider using the `JobMaintenanceStateInformation` for these tests?

It uses raw strings to set up most of the stuff. Which makes reading and verifying a bit simplier.

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		assertFalse(myWorkChunkRepository.findById("FOO").isPresent());
This test is likely not needed.

`findById` is an auto-generated method we didn't write (and so we shouldn't test)

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +	}
I feel like this test should be broken up into multiple tests.

One test for each transition.

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/AbstractIJobPersistenceSpecificationTest.java
> +	public String storeWorkChunk(String theJobDefinitionId, String theTargetStepId, String theInstanceId, int theSequence, String theSerializedData, boolean theGatedExecution) {
Eh, i'll allow it. But this really is getting to the point where we have enough parameters we should instead be using a parameters object.

4 strings can be difficult to get correct (especially since 3 of them are called "*id"

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +		2|READY,2|QUEUED
Can you rename the test to make that clearer please?

You are probably right, but i imagine others will make my same mistake

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/ITestFixture.java
> +	String createFirstChunk(JobDefinition<TestJobParameters> theJobDefinition, String theJobInstanceId);
I question the need for all these methods.

We have a perfectly valid way of creating chunks via the JobMaintenanceStateInformation object and syntax.

---

Even if these methods are needed (and i'm not convinced that they are), it should be a) documented and b) one method with parameters object instead.

only reason other methods weren't documented was because it was a refactor, and not new interface values being added.

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +			// ignore the last step
please update the comment to explain why (briefly)

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * Atomically advance the given job to the given step and change the status of all chunks in the next step to READY
all chunks? Regardless of state?

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			return true;
You might need to merge in latest; this code has been updated to not do this.

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		return workChunkStatuses.equals(Set.of(WorkChunkStatusEnum.COMPLETED));
Q: is there any chance of a race condition where we have a COMPLETED previous chunk, but the GATE_WAITING new chunk is not yet created / ready to transition?

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			} else if (!jobWorkCursor.isFinalStep()) {
I imagine this is because final steps of gated jobs are never going to get here?

Can we comment that somwhere. Your comment here is just "all other gated job steps except for final steps". Which is a bit confusing, because the only final step being handled here is the reduction step.

And if i'm reading this code, i might be confused why you don't handle the non-reduction gated final steps.

----

Also, as a good practice, we should still have the `else` with a log - even if it's something we expect to *never* see (so in case we do see it, we know what it is).

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				counter.get(),
You might as well just remove the counter entirely - it's not being updated.

And if you decide to keep it, it doesn't need to be atomic (since now it's a standard iteration).

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> -					&& (theJobDefinition.isGatedExecution() || jobWorkCursor.isReductionStep())) {
I still think we have to block gated reduction steps, no?

Remember, this application is multi-threaded, multi-instance.

You have other code that transitions all these GATE_WAITING chunks to READY (for all steps).

You might be thinking that these will then get handled by the next pass through.

But if a different instance is running the maintenance job, it will get here and see a READY chunk that it wants to send to the QUEUE.

But this READY chunk is actually a Reduction Step READY chunk and should not be sent to the queue, ever!

---

You cannot rely on "order of code" for business logic to work as expected.

It must be explicitly defined. Even if this weren't multi-threaded multi-instance (refactors happen after all).

2024-04-10 15:41 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		enqueueReadyChunks(theInstance, jobDefinition);
Q: Why did you move this to the bottom?

I'm not saying it's wrong, i'm just curious.

Your changes should (in theory) mean the gate-waiting boolean isn't necessary at all (GATE_WAITING chunks are not enqueued until all are set to READY).

It doesn't matter if it's at the end (and maybe it makes better sense there), but i am just curious.

2024-04-10 20:35 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			} else if (!jobWorkCursor.isFinalStep()) {
yes, if the job is at the final step and has all chunks completed, then it will be marked as chunks purged. Added comments to explain and an `else` branch to log

2024-04-10 20:35 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		return workChunkStatuses.equals(Set.of(WorkChunkStatusEnum.COMPLETED));
There shouldn't be, since a chunk is only set to COMPLETED after successfully executing `run`, which includes creating the work chunk for the next step.

2024-04-10 20:35 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/IJobPersistence.java
> +	 * Atomically advance the given job to the given step and change the status of all chunks in the next step to READY
added state QUEUED and GATE_WAITING

2024-04-10 20:36 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +	// Up to 7.1.8-SNAPSHOT, gated jobs' work chunks are created in status QUEUED but not actually queued for the
used 7.1 instead

2024-04-10 20:36 UTC, TynerGjs commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImpl.java
> +		// set to GATE_WAITING if job is gated, to READY if not
used suggested text as comment

2024-04-10 20:36 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/introduction.md
> +1. When the current step is complete, moves any gated jobs onto their next step and update all chunks in `GATE_WAITING` to `READY`.
fixed gramma error

2024-04-10 20:36 UTC, TynerGjs commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa_batch/batch2_states.md
> +   [*]             --> GATE_WAITING  : on create - gated non-first chunk
used suggested text

2024-04-10 20:46 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +		enqueueReadyChunks(theInstance, jobDefinition);
Yes, the sequence doesn't affect the correctness, the chunks will still be picked up. But I moved it because I think it would be good to have only one path to the `enqueueReadyChunks` method. By putting this at the end, we don't have to call `enqueueReadyChunks` in `triggerGatedExecutions` and it can still catch all the chunks that were just turned to READY in `triggerGatedExecutions`. This saves the time waiting for the next job maintenance.

Also, another reason (and probably the major reason) is that Michael suggested to do so xD.

2024-04-10 21:00 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/support/JobMaintenanceStateInformation.java
> +			// ignore the last step
updated comment

2024-04-10 21:01 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +		2|READY,2|QUEUED
renamed

2024-04-10 21:02 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +			return true;
Do you mean the latest master? I merged in the ready state branch but this check still exists

2024-04-10 21:03 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/maintenance/JobInstanceProcessor.java
> +				counter.get(),
kept the counter for log and changed to int

2024-04-11 18:56 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/ITestFixture.java
> +	String createFirstChunk(JobDefinition<TestJobParameters> theJobDefinition, String theJobInstanceId);
Removed createChunkInStep and used the JobMaintenanceStateInformation instead. I think we still need the createFirstChunk to call the `WorkChunkCreateEvent.firstChunk` instead of creating the event directly for gated first chunk creation.

2024-04-11 18:59 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +	}
There are tests that verify the individual transitions in the `IJobMaintanenceAction` test. I wrote this test to simulate the job from creation to the last step. It makes me feel more confident with the correctness. Do you think it is necessary?

2024-04-11 19:01 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		String chunkIdSecondStep2 = storeWorkChunk(JOB_DEFINITION_ID, LAST_STEP_ID, instanceId, 0, null, true);
Moved to `IWorkChunkStateTransitions` and used `JobMaintenanceStateInformation ` instead

2024-04-12 13:15 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IBatch2WorkChunkRepository.java
> +	@Query("UPDATE Batch2WorkChunkEntity e SET e.myStatus = ca.uhn.fhir.batch2.model.WorkChunkStatusEnum.READY WHERE "
minor: agree. my complaint was the public api, but internal implementations can be more general.  This is fine for now.

2024-04-12 14:27 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
>  		assertNull(chunk.getData());
This test was specifically testing without data, there's a corresponding test with data. Added comments to explain.

2024-04-12 14:33 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
> +	default void testGatedStep2NotReady_stepNotAdvance(String theChunkState) throws InterruptedException {
The job starts in step 2. Renamed to suggested

2024-04-12 14:55 UTC, TynerGjs commented on hapi-fhir-storage-batch2-test-utilities/src/main/java/ca/uhn/hapi/fhir/batch2/test/IJobMaintenanceActions.java
>  		verifyWorkChunkFinalStates(result);
added check

2024-04-12 14:57 UTC, TynerGjs commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/model/WorkChunkStatusEnum.java
>  	// wipmb For 6.8 Add WAITING for gated, and READY for in db, but not yet sent to channel.
removed

2024-04-12 15:03 UTC, TynerGjs commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/batch2/JpaJobPersistenceImplTest.java
> +		JobInstance instance = createInstance(true, true);
I am a bit reluctant to change these methods to createGatedDefinitionAndInstance or createGatedChunks because a few parametrized tests uses the boolean... Introduced local variable `isGatedExecution` to make it clearer.

2024-06-12 20:31 UTC, closed without merging