bugfix to https://github.com/hapifhir/hapi-fhir-jpaserver-starter/iss…
hapifhir/hapi-fhir pull request #5859
Opened 2024-04-19 06:42 UTC by jkiddo

…ues/675

2024-04-29 19:14 UTC, dotasek requested changes
**Please merge from master to get HAPI pipelines passing.**

This appears to work for me. 

To test, I merged recent HAPI changes into this branch, built it locally, and used it in this release tracking branch of jpaserver-starter:

https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/660

In `src/main/resources/application.yaml`, I switched to using R5:

```yaml
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhir_version: R5
```



When jpaserver-starter is built with this branch of HAPI, it starts, and the capability statement indicates R5:

```json
{
  "resourceType": "CapabilityStatement",
  "id": "ed8f7471-2b5b-457e-a17c-52a3542efc11",
  "name": "RestServer",
  "status": "active",
  "date": "2024-04-29T15:02:52.689-04:00",
  "publisher": "Not provided",
  "kind": "instance",
  "software": {
    "name": "HAPI FHIR Server",
    "version": "7.3.0-SNAPSHOT/79214c04bd/2024-04-29"
  },
  "implementation": {
    "description": "HAPI FHIR R5 Server",
    "url": ["http://localhost:8080/fhir"](http://localhost:8080/fhir)
  },
  "fhirVersion": "5.0.0",
  ...
  }
```

When this branch is NOT used, the following error appears:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'subscriptionQueryValidator', defined in ca.uhn.fhir.jpa.subscription.submit.config.SubscriptionSubmitterConfig, could not be registered. A bean with that name has already been defined in class path resource [ca/uhn/fhir/jpa/topic/SubscriptionTopicConfig.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true


```

This is consistent with the error reported here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/675

2024-04-29 22:33 UTC, dotasek approved these changes

2024-04-30 12:20 UTC, epeartree approved these changes

2024-05-01 20:20 UTC, dotasek commented
@jkiddo for some reason, the setup of this PR was preventing the Compile against CDR check from completing.

We created and merged this PR with your cherry-picked changes, which seemed to enable the check: https://github.com/hapifhir/hapi-fhir/pull/5892

I'm closing this PR; please open another if anything is amiss.

2024-05-01 20:20 UTC, closed without merging