Fix error message for HAPI-0302 showing misleading names for known resource types
hapifhir/hapi-fhir pull request #5875
Opened 2024-04-24 19:10 UTC by holly-smile

2024-04-24 19:45 UTC, holly-smile commented
Sorry, still needs a unit test - incoming!

2024-04-25 14:04 UTC, jmarchionatto requested changes
I am not sure about this fix. 
There is a provider returning "ListResource" name, apparently to meet some DSTU2 version spec, and we let that happen to later change it, no matter the version. 
I would rather discriminate the name by version, if necessary at all, in the proviuder, and eliminate the introduced remapping.

2024-04-25 18:00 UTC, jamesagnew commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/RestfulServer.java
> +		String simpleName = theResourceProvider.getResourceType().getSimpleName();
We shouldn't need to maintain a hardcoded map for these. You can query the FhirContext for the resource name associated with a given class by calling something like:
```
theCtx.getResourceDefinition(resourceType).getName()
```

2024-04-25 19:11 UTC, holly-smile commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/RestfulServer.java
> +		String simpleName = theResourceProvider.getResourceType().getSimpleName();
Ah, that's so much cleaner (and less hacky)! Thank you!

2024-04-25 20:05 UTC, jmarchionatto approved these changes
Much better. Thanks! Approved.

2024-04-25 20:39 UTC, merged