Replace hamcrest with assertj
hapifhir/hapi-fhir pull request #5911
Opened 2024-05-07 20:58 UTC by fil512

2024-05-28 20:08 UTC, dotasek requested changes
This

2024-05-28 20:08 UTC, dotasek commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/CustomTypeR4Test.java
> -		assertThat(messageString, not(stringContainsInOrder(
There must be a better assertj assert available. Though the regex looks OK here, if it's just slightly wrong, we'll miss it in this test.

2024-05-28 20:08 UTC, dotasek commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/CustomTypeR4Test.java
> -		assertThat(messageString, not(stringContainsInOrder(
Same here, re: regex vs assert.

2024-05-28 20:14 UTC, dotasek commented
@fil512 I did a review of ~50 randomly chosen test files, including all contents of hapi-fhir-test-util.

Some of them, particularly those that suggest switching to `assertThatThrownBy()`, `isEqualTo()` or `contains()`, are probably nitpicky, and you can feel free to mark them as resolved.

There are a few regarding test asserts that are always true, and some that appear to test nothing except assertj itself that I'm more interested in.

**This looks like it was a long haul, @fil512 @tadgh, your patience with this is laudable!**

2024-05-30 18:26 UTC, fil512 commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/CommonCodeSystemsTerminologyServiceTest.java
> -			fail();
I chose not to convert these since there are many of them and I couldn't find a reliable programatic way to do it.

2024-05-30 18:27 UTC, fil512 commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupportTest.java
> -		assertEquals("Failed to expand ValueSet 'http://vs' (in-memory). Could not validate code http://cs#code99. Error was: "+ Msg.code(702) + "Unable to expand ValueSet because CodeSystem could not be f
I chose assertEquals over assertThat for these for 2 reasons:
1) smaller MR (therefore easier to backport over)
2) assertEquals(a,b) is less code than assertThat(a).isEqualTo(b) and in many cases more readable.

2024-05-30 18:30 UTC, fil512 commented on hapi-fhir-test-utilities/src/test/java/ca/uhn/fhir/test/utilities/RangeTestHelperTest.java
> -				RangeTestHelper.checkWithinBounds(.91001, .91002, .910013);
THANKS!  Great find!  Removing RangeTestHelper class now.

2024-05-30 18:42 UTC, fil512 commented on hapi-fhir-test-utilities/src/test/java/ca/uhn/fhir/test/utilities/CustomMatchersUtilTest.java
> -import static ca.uhn.fhir.test.utilities.CustomMatchersUtil.assertDoesNotContainAnyOf;
love deleting classes!

2024-05-30 18:43 UTC, fil512 commented on hapi-fhir-test-utilities/src/test/java/ca/uhn/test/concurrency/PointcutLatchTest.java
> -			assertThat(e.getMessage(), startsWith(TEST_LATCH_NAME + ": HAPI-1485: invoke() called outside of setExpectedCount() .. awaitExpected().  Probably got more invocations than expected or clear() was
see above

2024-05-30 18:43 UTC, fil512 commented on hapi-fhir-test-utilities/src/test/java/ca/uhn/test/concurrency/PointcutLatchTest.java
> -			assertThat(e.getMessage(), startsWith("HAPI-1484: test-latch-name PointcutLatch ERROR: invoke() called when countdown was zero."));
see above

2024-05-30 18:43 UTC, fil512 commented on hapi-fhir-test-utilities/src/test/java/ca/uhn/test/concurrency/PointcutLatchTest.java
> -			assertThat(e.getMessage(), startsWith("HAPI-2344: " + TEST_LATCH_NAME + " PointcutLatch had 1 exceptions.  Throwing first one."));
see above

2024-05-30 18:47 UTC, fil512 commented on hapi-fhir-structures-dstu2/src/test/java/ca/uhn/fhir/validation/ResourceValidatorDstu2Test.java
> -		assertThat(resultString, StringContains.containsString("cvc-pattern-valid"));
this is alarming
might have been a bad regexp. checking now

2024-05-30 18:56 UTC, fil512 commented on hapi-fhir-structures-dstu2/src/test/java/ca/uhn/fhir/validation/ResourceValidatorDstu2Test.java
> -		} catch (DataFormatException e) {
yep. found the bad MR. thankfully only 8 files corrupted
e6d91e8f22be667e4bf3b44b55657ab2be17dbd8

2024-05-30 20:03 UTC, fil512 commented on hapi-fhir-structures-dstu2/src/test/java/ca/uhn/fhir/validation/ResourceValidatorDstu2Test.java
> -		assertThat(encoded, StringContains.containsString("2000-15-31"));
Yikes!  You uncovered a bad regexp search and replace!
yep. found the bad commit. thankfully only 8 files corrupted
https://github.com/hapifhir/hapi-fhir/commit/e6d91e8f22be667e4bf3b44b55657ab2be17dbd8

2024-05-31 15:46 UTC, dotasek commented
I resolved the outstanding assertThatThrownBy() requested changes after your comments on the first few. If you find any left, they're clearly fine to resolve.

2024-06-04 23:12 UTC, fil512 commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/client/SearchClientR4Test.java
> -    assertEquals("http://localhost:8081/hapi-fhir/fhir/Location?_query=match&name=smith&_count=100", value.getURI().toString());
test passes. keeping stronger version

2024-06-04 23:12 UTC, fil512 commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/client/SearchClientR4Test.java
> -      assertEquals("http://localhost/fhir/Bundle?stringParam=STRING1&stringTypeParam=STRING2&dateParam=1970-10-04T10:23:55.986-04:00&calParam=1970-10-04T10:23:55.986-04:00",
test passes. keeping stronger assert.

2024-06-04 23:13 UTC, fil512 commented on hapi-fhir-structures-hl7org-dstu2/src/test/java/ca/uhn/fhir/model/PrimititeTest.java
> -    assertFalse(type.hasValue());
ha! good catch. fixed!

2024-06-04 23:15 UTC, fil512 commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/CustomTypeR4Test.java
> -		assertThat(messageString, not(stringContainsInOrder(
I spent quite a while looking and couldn't find it.

2024-06-04 23:20 UTC, fil512 commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/CustomTypeR4Test.java
> -		assertThat(messageString, not(stringContainsInOrder(
I agree with you it's ugly

2024-06-04 23:20 UTC, fil512 commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/CustomTypeR4Test.java
> -		assertThat(messageString, not(stringContainsInOrder(
ditto

2024-06-05 13:12 UTC, dotasek approved these changes
All conversations resolved, and the new commits address appear correct.

2024-06-05 18:52 UTC, AD1306 approved these changes

2024-06-05 20:02 UTC, merged