added workchunk to step execution details
hapifhir/hapi-fhir pull request #5932
Opened 2024-05-13 19:41 UTC by TipzCM

closes #5919

2024-05-17 19:04 UTC, longma1 approved these changes

2024-05-17 20:12 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/api/StepExecutionDetails.java
>  			@Nonnull PT theParameters,
added

2024-05-19 23:00 UTC, fil512 requested changes
I need to understand performance implications before approving

2024-05-19 23:00 UTC, fil512 commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStepTest.java
> +		StepExecutionDetails<BulkImportJobParameters, VoidModel> details = new StepExecutionDetails<>(parameters, null, ourTestInstance, new WorkChunk().setId(CHUNK_ID));
Does this change the size of kafka messages or db records?

2024-05-22 12:35 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/util/Batch2Utils.java
> +		return new StepExecutionDetails<>(theP, theIntermediateParams, theInstance, reductionChunk);
Updated and moved to StepExecutionDetails

2024-05-22 12:36 UTC, TipzCM commented on hapi-fhir-storage-batch2/src/main/java/ca/uhn/fhir/batch2/util/Batch2Utils.java
> +		return theChunk.getId() != null && theChunk.getId().equals(REDUCTION_STEP_CHUNK_ID_PLACEHOLDER);
moved to workchunk

2024-05-22 12:37 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/imprt/FetchFilesStepTest.java
> +		StepExecutionDetails<BulkImportJobParameters, VoidModel> details = new StepExecutionDetails<>(parameters, null, ourTestInstance, new WorkChunk().setId(CHUNK_ID));
Neither.

StepExecutionDetails are created during work step processing.

Nothing new is stored or sent.

2024-05-23 22:48 UTC, fil512 approved these changes

2024-05-27 01:59 UTC, merged