5914 clinical reasoning v3.6.0 bump
hapifhir/hapi-fhir pull request #5964
Opened 2024-05-24 20:30 UTC by Capt-Mac

Closes #5914

2024-05-30 13:13 UTC, barhodes approved these changes

2024-06-04 13:50 UTC, JPercival requested changes

2024-06-04 15:56 UTC, Capt-Mac commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/5914-clinical-reasoning-version-update.yaml
> +title: "Update Clinical Reasoning version to v3.6.0"
implementation is downstream of hapi

2024-06-04 16:04 UTC, JPercival approved these changes

2024-06-05 16:02 UTC, tadgh approved these changes

2024-06-07 16:43 UTC, merged