Improve search param extraction flexibility
hapifhir/hapi-fhir pull request #6030
Opened 2024-06-19 19:31 UTC by jmarchionatto

What was done: 

1. added `myExtractResourceLevelParams` property to allow extraction of Resource-level search param values 
2. extracted some code to be reused to an util class
3. Allowed test to specify a Patient provider to `RestServerR4Helper`

2024-06-25 20:43 UTC, jamesagnew commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/extractor/BaseSearchParamExtractor.java
> +	public void setExtractResourceLevelParams(boolean theExtractResourceLevelParams) {
I don't see any tests that exercise this behaviour. Should probably have a test with positive and negative values.

2024-06-25 22:39 UTC, jmarchionatto commented on hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/extractor/BaseSearchParamExtractor.java
> +	public void setExtractResourceLevelParams(boolean theExtractResourceLevelParams) {
Added

2024-06-26 14:08 UTC, dotasek requested changes
Test for the myExtractResourceLevelParams looks good. Is this change attached to a feature, or something else that needs to be put in the changelog, or are these just quality of life improvements.

2024-06-26 14:19 UTC, jmarchionatto commented on hapi-fhir-jpaserver-searchparam/src/test/java/ca/uhn/fhir/jpa/searchparam/extractor/BaseSearchParamExtractorTest.java
> +			doReturn(List.of(myRuntimeSearchParam)).when(myExtractor).getSearchParams(myResource);
Done. Thanks

2024-06-26 14:42 UTC, jamesagnew approved these changes

2024-06-26 15:22 UTC, dotasek approved these changes

2024-06-26 15:36 UTC, merged