Extend TRM_CONCEPT_DESIG.VAL column from 2,000 to 4,000 characters.
hapifhir/hapi-fhir pull request #6080
Opened 2024-07-04 19:55 UTC by lukedegruchy

Closes https://github.com/hapifhir/hapi-fhir/issues/6079

2024-07-04 20:19 UTC, tadgh approved these changes

2024-07-05 04:43 UTC, tadgh requested changes

2024-07-05 14:12 UTC, tadgh approved these changes

2024-07-05 14:12 UTC, tadgh approved these changes

2024-07-05 19:58 UTC, tadgh approved these changes

2024-07-05 19:58 UTC, tadgh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +			version.onTable("TRM_CONCEPT_DESIG")
recommend using `.10` and `.20` just to mimic others who have used the version skip style

2024-07-08 11:07 UTC, epeartree approved these changes

2024-07-08 18:19 UTC, merged