6083 clinical reasoning version bump v38
hapifhir/hapi-fhir pull request #6089
Opened 2024-07-09 18:38 UTC by Capt-Mac

closes #6083

2024-07-10 03:35 UTC, JPercival requested changes

2024-07-10 03:35 UTC, JPercival commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java
> +				.patch(theId, null, PatchTypeEnum.FHIR_PATCH_JSON, null, thePatchParameters, details);
issue: can we add a test to validate that either this is fixed or ensure that we don’t have a regression?

2024-07-10 03:35 UTC, JPercival commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml
> +of clinical reasoning 3.8.
question: I don’t see the patch operation changes here. That is potentially breaking, no?

2024-07-10 12:25 UTC, Capt-Mac commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java
> +				.patch(theId, null, PatchTypeEnum.FHIR_PATCH_JSON, null, thePatchParameters, details);
@JPercival  we can't successfully test patch because it has a current bug in FhirPatch, but this operation completely fails without PatchType being specified, which is not an available parameter otherwise.

2024-07-10 12:26 UTC, Capt-Mac commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml
> +of clinical reasoning 3.8.
Patch operation change is not a breaking change, the previous call of patch was incomplete

2024-07-10 19:56 UTC, JPercival approved these changes

2024-07-12 16:01 UTC, tadgh approved these changes

2024-07-12 16:01 UTC, tadgh commented on hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java
> +		// TODO update FHIR patchType once FHIRPATCH bug has been fixed
If this is a TODO for the future and not for now, i recommend you open an issue for it so it doesnt slip through the cracks.

2024-07-13 01:24 UTC, merged