use SearchParamater validator in package installer
hapifhir/hapi-fhir pull request #6112
Opened 2024-07-15 19:22 UTC by mrdnctrk

The PR fixes the issue that Package installer doesn't allow creating a composite SearchParameter (SP) resource if there is no `expression` element at the root level of the SearchParameter resource, whereas creating such a SP by other means (such as through FHIR endpoint) is allowed according to the spec. 

The cause was that there were some extra validation logic in the Package Installer that Dao level SearchParameter validation didn't have. This validation for SearchParameters in Package installer has now been refactored to use the same code as the SearchParameter validation used by the DAO layer, so that there is no difference between what can be created via PackageInstaller and other means. 

Also fixed another issue in DAO level SP validation. The validation of the SP types for the components of a composite SP weren't being applied if the SP didn't have an expression element.    

closes #6111

2024-07-15 19:24 UTC, mrdnctrk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +	/*
This comment I added to this method is unrelated to issue. I added it because I had some difficulty understanding why this method was doing what it is doing and thought I comment here would help.

2024-07-15 19:28 UTC, mrdnctrk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +		if (statusTypes.isEmpty()) {
No real code change here, I moved the bodies of the if statements to separate lines to clearly see the code coverage

2024-07-15 19:33 UTC, mrdnctrk commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/validation/SearchParameterDaoValidator.java
> -
`isCompositeWithoutExpression` was actually a wrong name for this function because it actually should have been named `isNonCompositeWithoutExpression` according to its implementation. I divided the function into 2, for better readability and added comment.

2024-07-15 19:40 UTC, mrdnctrk commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/validation/SearchParameterDaoValidator.java
> -		} else {
the structure of this part of the code was wrong and confusing.  Above there was an empty if body for the condition that checked `isCompositeWithoutExpression` (which should have been named `isNonCompositeWithoutExpression` as I mentioned earlier) and this part is the else of if. This means  for a composite parameter that doesn't have an expression then all the checks within this else are not applied, the particular importance is the checks maybeValidateCompositeWithComponent, maybeValidateCompositeSpForUniqueIndexing were doing. So removed this `if, else if, else` structure of this code to make sure composite SP validations are applied even when there is no expression at the root level.

2024-07-15 21:45 UTC, codeforgreen requested changes
The changes are carefully thought and thorough. I did notice one behaviour change in the DAO validator, please check and confirm if intentional.

2024-07-15 21:45 UTC, codeforgreen commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +	/*
Thank you for adding this explanation, Emre.

2024-07-15 21:45 UTC, codeforgreen commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +		if ("SearchParameter".equals(resourceType) && !isValidSearchParameter(theResource)) {
Very nice. This part of the code did bother me. I am glad you were able to reuse the DAO layer validator here.

2024-07-15 21:45 UTC, codeforgreen commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/validation/SearchParameterDaoValidator.java
> +		maybeValidateCompositeWithComponent(searchParameter);
I noticed this difference in behaviour - the component types are validated no matter if the composite SP has or does not have an expression, while before they were validated only when expression is absent. 
Please confirm if this change in behaviour is intentional. If so, the tests need to be updated according. There are some failing in the pipeline because of this.

2024-07-16 12:51 UTC, mrdnctrk commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/validation/SearchParameterDaoValidator.java
> +		maybeValidateCompositeWithComponent(searchParameter);
Thanks for bringing this up. I had made that change intentionally, but I hadn't realized the test failures. For now, I reverted the refactoring I did on the SearchParameterDaoValidator to clarify it further, and apply them back later. That refactoring isn't really related to the issue I am fixing, which can be handled later.

2024-07-16 18:50 UTC, codeforgreen approved these changes

2024-07-16 18:51 UTC, codeforgreen commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/validation/SearchParameterDaoValidator.java
> +		maybeValidateCompositeWithComponent(searchParameter);
It was a really good idea. You can bring it back with with a slight change later on.

2024-07-16 18:52 UTC, merged