Patient validate operation with remote terminology service enabled returns 400 bad request
hapifhir/hapi-fhir pull request #6124
Opened 2024-07-17 22:24 UTC by volodymyr-korzh

2024-07-22 19:21 UTC, dotasek requested changes
See comments regarding test cases and a removed null check. Otherwise, looks good to me.

2024-07-22 19:21 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtilsTest.java
> +			Arguments.of(Lists.newArrayList(new ValueSet.ConceptSetComponent().setSystem(SYSTEM_URL)),
In this, and in the corresponding r5 test, I think "ValueSet include with one system and code" and "ValueSet include with one system and no code" appear to be swapped. This line includes a code, and the next one doesn't.

2024-07-22 19:21 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtilsTest.java
> +			Arguments.of(Lists.newArrayList(new org.hl7.fhir.r5.model.ValueSet.ConceptSetComponent().setSystem(SYSTEM_URL)),
See comment in R4 test. Test names appear to be swapped.

2024-07-22 19:21 UTC, dotasek commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtils.java
> +		if (theValueSet == null || theValueSet.getCompose().getInclude().isEmpty()) {
There was a check for `theValueSet.getCompose().getInclude() == null` here before. Is this no longer necessary?

2024-07-22 19:21 UTC, dotasek commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtils.java
> +		if (theValueSet == null || theValueSet.getCompose().getInclude().isEmpty()) {
Same comment re:  `theValueSet.getCompose().getInclude() == null`

2024-07-22 19:40 UTC, codeforgreen reviewed
Overall changes look good. I see there are some additional validations added in the existing tests, but I am wondering about this specific use-case, how it behaves in the scenario described after your changes.
Please look at my comments and questions. Thanks.

2024-07-22 19:40 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java
> +		String system = ValidationSupportUtils.extractCodeSystemForCodeR5(theValueSet, code);
Nice to have: I see this class is all based on R5. Can you please fix some of the declarations so all resource classes use imports (e.g. `org.hl7.fhir.r5.model.ValueSet`)

2024-07-22 19:40 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceValidationSupportR4Test.java
> +	public void testValidateCode_withBlankCodeSystemAndValueSetUrl_returnsNull() {
Do you have any integration test which checks the output of the `$validate` operation? I wanted to see how the response is translated further.

2024-07-23 19:47 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
This if statement is intended to prevent all cases when we don't have a system or valueSetUrl to be executed on remote terminology server. 
This logic is mirroring behaviour that we already have in `RemoteTerminologyServiceValidationSupport#validateCodeInValueSet` 

Moreover, it is a requirement in $validate-code operation specification to provide "url" or "codeSystem". So we are just aligning with a specification. 

Specification:
`If the operation is not called at the instance level, one of the parameters "url" or "codeSystem" must be provided.`
https://hl7.org/fhir/R4/codesystem-operation-validate-code.html
(we are calling $validate-code not at instance level)

The field that caused an error for patient validation was actually a `gender` field.  But failure (400 bad request) could previously happen for different fields and different resources.

2024-07-23 21:16 UTC, volodymyr-korzh commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java
> +		assertEquals(10, myCaptureQueriesListener.getSelectQueriesForCurrentThread().size());
Sure

The fix that was introduced makes validation more "aggressive" by validating more fields/codes. 
As previously we tried to validateCodeInValueSet/validateCodeInCodeSystem with codeSystem as null, validation was not executed by validation chain, and returned null ValidationResult. 

As now validateCodeInValueSet/validateCodeInCodeSystem executed with extracted codySystem - number of queries increased, and it is expected.

2024-07-23 21:27 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtilsTest.java
> +			Arguments.of(Lists.newArrayList(new ValueSet.ConceptSetComponent().setSystem(SYSTEM_URL)),
Thanks for noticing. Fixed

2024-07-23 21:27 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtilsTest.java
> +			Arguments.of(Lists.newArrayList(new org.hl7.fhir.r5.model.ValueSet.ConceptSetComponent().setSystem(SYSTEM_URL)),
Fixed

2024-07-23 21:31 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtils.java
> +		if (theValueSet == null || theValueSet.getCompose().getInclude().isEmpty()) {
Under the hood `getInclude()` creates an empty arraylist if executed. It is safe to remove this check as it will never return true

```
        public List<ConceptSetComponent> getInclude() { 
          if (this.include == null)
            this.include = new ArrayList<ConceptSetComponent>();
          return this.include;
        }
```

2024-07-23 21:32 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationSupportUtils.java
> +		if (theValueSet == null || theValueSet.getCompose().getInclude().isEmpty()) {
Yes, it is safe to remove this (same reason as for R4 method)

2024-07-23 21:34 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java
> +		String system = ValidationSupportUtils.extractCodeSystemForCodeR5(theValueSet, code);
Nice catch. Removed  redundant `org.hl7.fhir.r5.model.` declarations.

2024-07-24 02:43 UTC, volodymyr-korzh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6122-validate-operation-with-remote-terminology-service-enabled-returned-bad-request.yaml
> +title: "Previously, executing the '$validate' operation on a patient instance would result in an HTTP 400 Bad Request
In this case, validating patient with gender field caused 400 Bad request. But this error could potentially impact other resources. I corrected title and remove mentioning of Patient resource. 

It is hard to describe one case to add it to the title as impact of this issue is broad and depend on where the validation methods are called from InstanceValidator.

Updated version:

```
Previously, executing the '$validate' operation on a resource instance could result in an HTTP 400 Bad Request 
instead of an HTTP 200 OK response with a list of validation issues. This has been fixed.
```

2024-07-24 14:23 UTC, dotasek commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java
> +		assertEquals(10, myCaptureQueriesListener.getSelectQueriesForCurrentThread().size());
I can concur. What Volodymyr describes above is consistent with what I saw when we were tracing the issue.

2024-07-24 14:29 UTC, dotasek commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
Can concur here after having traced this with Volodymyr. Thank you, @codeforgreen for bringing these up, they really do help document the changes well.

2024-07-24 14:35 UTC, dotasek approved these changes
Looks good to me.

2024-07-24 14:56 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceValidationSupportR4Test.java
> +	public void testValidateCode_withBlankCodeSystemAndValueSetUrl_returnsNull() {
Added `FhirInstanceValidatorR4Test#testValidate_patientWithGenderCode_resolvesCodeSystemFromValueSet` 
It is not a full integration test, as we have to mock Remote terminology service, but it covers the main fix implemented in `VersionSpecificWorkerContextWrapper#validateCode` and checks the output result of validation.

2024-07-24 21:40 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
@volodymyr-korzh thanks for explaining. I was following the call sequence for instance level $validate-code and I see it goes into the same method as resource type level $validate-code. Can you please check and see if there is a test for this? 
In particular for instance level ValueSet $validate-code, I have an actual use-case where the system may be absent. I've documented it here: https://github.com/hapifhir/hapi-fhir/issues/6150. The `validateCode` call that results from checking a profile binding with a `ValueSet` will not have the system populated.

2024-07-24 21:44 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
Another aspect is why would Remote Terminology have this restriction but other implementations of IValidationSupport would not have this? As you know we have several and there is a `ValidationSupportChain` which invokes them as part of the operation call. Remote Terminology is just one of them.

2024-07-24 22:49 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
I believe this issue and the issue I linked #6150 have the same root cause, which is about the fact that we simply throw 400 and 404 exceptions instead of converting them to a NotFound response.

2024-07-29 19:43 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (isBlank(theCodeSystem) && isBlank(theValueSetUrl)) {
Removed lines of code in question, introduced error handling for 400 and 404 responses for $validate-code operation

2024-07-29 20:46 UTC, dotasek requested changes
No changes requested, just clarification regarding the comments I left.

2024-07-29 20:46 UTC, dotasek commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +			codeSystem = ValidationSupportUtils.extractCodeSystemForCodeR4((ValueSet) theValueSet, theCode);
I realize the previous code was just moved and that it was previously using R4 and just not explicitly saying so, but I'm looking over this again, can we safely assume R4 here?

2024-07-29 20:46 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceValidationSupportR4Test.java
> +			public void systemNotPresent_returnsValidationResultWithError(Exception theException, String theServerMessage) {
I spent some time trying to differentiate this and the following test (`systemNotPresent_returnsValidationResultWithError` and `systemPresentCodeNotPresent_returnsValidationResultWithError`).

Am I correct when I say that neither test can infer the system? 

It looks to me like both expect the same errors, but for a different reason. In the first, there is a compose that has a ConceptSetComponent with no system, and in the second, there are two ConceptSetComponent's, each with a system, thus making inference impossible.

2024-07-29 22:20 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +			codeSystem = ValidationSupportUtils.extractCodeSystemForCodeR4((ValueSet) theValueSet, theCode);
It is not safe to assume that we will have R4 ValueSet here. We well have R5 ValueSet here for R5 context, etc. I refactored extractCodeSystemForCode method to extract codeSystem from DSTU3, R4 and R5 ValueSets.

2024-07-29 22:29 UTC, volodymyr-korzh commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceValidationSupportR4Test.java
> +			public void systemNotPresent_returnsValidationResultWithError(Exception theException, String theServerMessage) {
Yes, correct. 
In first case - `systemNotPresent` - we have ValueSet with no code system 
second case `systemPresentCodeNotPresent` - we have multiple code systems, but we cant decide which to use (as both of systems missing the code that we want to validate)

2024-07-30 14:30 UTC, dotasek approved these changes

2024-07-30 22:11 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		} catch (ResourceNotFoundException | InvalidRequestException ex) {
Can you please merge your branch to the release branch? This shows as new code in this PR and it already exists in the branch. Thanks.

2024-07-30 22:23 UTC, codeforgreen approved these changes

2024-07-30 22:30 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		} catch (ResourceNotFoundException | InvalidRequestException ex) {
Ah, it seems that this is for $validate-code. That seems legitimate as well, even though the spec allows response as 400, this will produce a more user-friendly response, consistent with other operations such as $lookup.

2024-07-31 17:38 UTC, merged