Delete Expunge More Detailed Log Message
hapifhir/hapi-fhir pull request #6211
Opened 2024-08-12 22:51 UTC by jdar8

Closes #6210

2024-08-16 17:28 UTC, TipzCM approved these changes

2024-08-16 17:28 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSvcImpl.java
> +			List<JpaPid> theJpaPids, boolean theCascade, Integer theCascadeMaxRounds, String theChunkId) {
Q: is it possible to pass the entire chunk up?

I ask because it could be conceivable that one day we need more than just chunkid (maybe other chunk metadata) and it would be nice if we can change that without rechanging the entire api every time.

2024-08-16 17:28 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSvcImpl.java
> +		String formattedChunkIdForLogMessage = theChunkId.isEmpty() ? "" : "Chunk[" + theChunkId + "] - ";
i recommend using `isNotBlank(chunkId)` so you'll never have to worry about this being a null passed in.

2024-09-03 17:11 UTC, jdar8 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSvcImpl.java
> +			List<JpaPid> theJpaPids, boolean theCascade, Integer theCascadeMaxRounds, String theChunkId) {
Yup, I've now changed it to bring the entire workchunk up

2024-09-04 13:27 UTC, michaelabuckley requested changes

2024-09-04 13:27 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSqlBuilder.java
> +import graphql.VisibleForTesting;
trivial: wrong annotation.  We use com.google.common.annotations.

2024-09-04 13:27 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSqlBuilder.java
> +	@VisibleForTesting
trivial: probably redundant annotation.  This is a normal method, no?

2024-09-04 13:27 UTC, michaelabuckley commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/svc/IDeleteExpungeSvc.java
> +			List<T> thePersistentIds, boolean theCascade, Integer theCascadeMaxRounds, PT theWorkChunk);
major problem:  This is a breaking change with Mongo.  You'll need a Smile change too.

suggestion: Just pass the String chunkId rather than the whole chunk.  That allows you to skip all the generic noise.

If you want to avoid a version bump, I can show you how to do that with a default method.  Something like this.
```suggestion
default int deleteExpunge(
			List<T> thePersistentIds, boolean theCascade, Integer theCascadeMaxRounds, String theWorkChunkId) {
			// delete body once Mongo is fixed.
			return deleteExpunge(thePersistentIds, theCascade, theCascadeMaxRounds);
			}
@Deprecated // to delete asap
default int deleteExpunge(
			List<T> thePersistentIds, boolean theCascade, Integer theCascadeMaxRounds) {
			return deleteExpunge(thePersistentIds, theCascade, theCascadeMaxRounds, "unknown");
			}
```

2024-09-04 13:27 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSvcImpl.java
> +			List<JpaPid> theJpaPids, boolean theCascade, Integer theCascadeMaxRounds, PT theWorkChunk) {
question: Why bring the whole WorkChunk type into this?  You only need the chunk id (String) and that would avoid this whole generic thing.

Suggestion: If you do want the object instead of just the id, why use the generic here?  WorkChunk is a public api type, and is shared with Mongo.  This will work if you delete the generics bit and change the type of theWorkChunk to WorkChunk
```suggestion
	public int deleteExpunge(
			List<JpaPid> theJpaPids, boolean theCascade, Integer theCascadeMaxRounds, WorkChunk theWorkChunk) {
```

2024-09-04 16:42 UTC, jdar8 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/expunge/DeleteExpungeStep.java
> -			String theChunkId,
It was suggested to bring the whole WorkChunk in this review comment: https://github.com/hapifhir/hapi-fhir/pull/6211#discussion_r1720117992.

I could revert the changes if this isn't a great idea.

2024-09-04 18:39 UTC, jdar8 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSvcImpl.java
> +			List<JpaPid> theJpaPids, boolean theCascade, Integer theCascadeMaxRounds, PT theWorkChunk) {
See comment above about bringing WorkChunk into this. 

I could bring WorkChunk into here by adding the generic type into `IDeleteExpungeSvc` interface.

2024-09-04 18:39 UTC, jdar8 commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/svc/IDeleteExpungeSvc.java
> +			List<T> thePersistentIds, boolean theCascade, Integer theCascadeMaxRounds, PT theWorkChunk);
Forgot to post the Smile change... that is my bad.

2024-09-04 18:42 UTC, jdar8 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/delete/batch2/DeleteExpungeSqlBuilder.java
> +import graphql.VisibleForTesting;
removed visibleForTesting

2024-10-10 20:52 UTC, closed without merging