Query with FullText searching (_text) does not return expected result
hapifhir/hapi-fhir pull request #6217
Opened 2024-08-14 17:55 UTC by epeartree

closes #6216

2024-08-14 19:36 UTC, michaelabuckley requested changes
A small bug.  Needs some more tests.

2024-08-14 19:36 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +		final int numberOfPatientsToCreate = SearchBuilder.getMaximumPageSize() + 10;
problem: this looks like you started to write a bulk test to force overflow, and then forgot.

2024-08-14 19:36 UTC, michaelabuckley commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +
suggestion: I'd feel safer seeing the combination of Lucene + JPA.  So create a bunch of patients, the same family name, but half active=false.  Enough that half is bigger than the page size.  Then search for `Patient?_text=family&active=true`.  That should test the integration of the stream, and the JPA side.

2024-08-14 19:36 UTC, michaelabuckley commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_6_0/6216-fulltext-searching-not-returning-expected-results.yml
> + fixed."
```suggestion
title: "Previously, searches combining the `_text` query parameter (using Lucene/Elasticsearch) with query parameters using the database (e.g. `identifier` or `date`) could miss matches when more than 500 results match the `_text` query parameter.  This has been fixed, but may be slow if many results match the `_text` query and must to check against the database parameters.
```

2024-08-14 19:36 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java
> +			retVal = padIdListWithPlaceholders(theLastnResourceIds, 800);
problem:  This is now different if the size > 800.  The old code returned the List unmodified.  This returns an empty list.
Clearly missing some tests.  Please extract a PlaceholderPadder class with tests for 0, 1, 49,50,51, 799, 800, 801, and 10000 entries and verify the prefix of the result always matches the input.

2024-08-14 19:36 UTC, michaelabuckley commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/util/TaskChunkerTest.java
> +	    assertEquals(List.of(List.of(1,2,3), List.of(4,5,6), List.of(7,8,9)), result);
suggestion: Can you test a few more sizes: empty, 1, 2, 3, and 4 to test partial fills?

2024-08-15 11:32 UTC, epeartree commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java
> +			retVal = padIdListWithPlaceholders(theLastnResourceIds, 800);
The implementation sill returns the list unmodified when the size >800.  see line 897.  it's just hard to see with gitHub diff.  

i'll still implement the recommended test

2024-08-15 11:33 UTC, epeartree commented on hapi-fhir-base/src/test/java/ca/uhn/fhir/util/TaskChunkerTest.java
> +	    assertEquals(List.of(List.of(1,2,3), List.of(4,5,6), List.of(7,8,9)), result);
will do

2024-08-15 11:34 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +		final int numberOfPatientsToCreate = SearchBuilder.getMaximumPageSize() + 10;
Indeed, looks like i got interrupted and lost the line of thought.

2024-08-15 11:34 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +
will do

2024-08-15 18:34 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java
> +
implemented at est with` _content=family&active=true `since `_text` checks the resource narrative.

2024-08-15 22:01 UTC, volodymyr-korzh approved these changes

2024-08-19 16:09 UTC, michaelabuckley approved these changes
Looks ok.

2024-08-19 16:09 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/util/InClauseNormalizerTest.java
> +			Arguments.of(801, 801)
cool

2024-08-19 18:53 UTC, merged