Refactor getOrCreateTag method to use PROPAGATION_REQUIRED for XA transaction compatibility
hapifhir/hapi-fhir pull request #6224
Opened 2024-08-20 12:01 UTC by iyt-trifork

### XA Transaction Issue with HAPI FHIR and PostgreSQL

We are experiencing issues in our HAPI FHIR application when using XA transactions, similar to those reported in [issue #3412](https://github.com/hapifhir/hapi-fhir/issues/3412).

#### Problem
The PostgreSQL JDBC driver's `PGXAConnection` does not support suspend/resume operations, as detailed in the [official documentation](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/xa/PGXAConnection.html). This limitation causes exceptions when the `PROPAGATION_REQUIRES_NEW` transaction propagation behavior is used in XA environments, since it requires suspending the current transaction and resuming it later.

#### Proposed Solution
Refactor the `getOrCreateTag` method in `BaseHapiFhirDao` to use `PROPAGATION_REQUIRED` instead of `PROPAGATION_REQUIRES_NEW`. This change will make the application compatible with XA transactions in PostgreSQL by avoiding the suspend/resume requirement.

#### References
- Related issue: [#3412](https://github.com/hapifhir/hapi-fhir/issues/3412)
- PostgreSQL `PGXAConnection` documentation: [PGXAConnection](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/xa/PGXAConnection.html)

2024-08-20 18:07 UTC, michaelabuckley requested changes
We can't create tags inline during the transaction.  This will cause conflicts at commit times during mass ingestion when the create tags.

2024-08-20 18:07 UTC, michaelabuckley commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		template.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);
This doesn't work here.  We deliberately start a new connection/transaction because tag creation is a serious performance hot-spot and conflicts will cause an entire transaction bundle to roll back.  If you need this, please extract this to background thread executor so the current transaction is not implicated.

2024-08-21 14:19 UTC, iyt-trifork commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java
> +		template.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);
I have made a separate TagDefinitionDao, which encapsulates the get or create logic in a separate background thread, using the thread executor. It was also necessary to create a new entity manager instance in each new thread, which i don't know the implications of. It looks similar to the 'entitymanager-per-operation' anti-pattern, mentioned in [Hibernate Transaction Basics](https://docs.jboss.org/hibernate/stable/entitymanager/reference/en/html_single/#transactions-basics)

2024-09-03 11:44 UTC, jkiddo commented
FYI @michaelabuckley all tests go green now

2024-09-12 15:01 UTC, michaelabuckley requested changes
Nice work.  I have requested a couple more changes.

2024-09-12 15:17 UTC, michaelabuckley requested changes
I'm sorry.  I've led you down an obsolete path.  I forgot that we relaxed the constraint on the hfj_tag_def table.  It used to be unique.  But that broke last year, and we now allow duplicate definitions in hfj_tag_def.  So all this complexity with the nested transaction is no longer needed.

I think your original path will work.  Just commit the tag definitions as part the main transaction, and add them to the shared cache once submitted.

See https://github.com/hapifhir/hapi-fhir/pull/4813

Again, I apologize for asking for this complexity.

2024-09-13 09:26 UTC, iyt-trifork commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TagDefinitionDao.java
> +	private PlatformTransactionManager myTransactionManager;
Does not work without RequestDetails, which i then have to propagata all the way down here.
But by your latest comment about the forgotten indexes, we simply use the ITagDefinitionDao directly, as shown in the latest changes on this PR.

2024-09-13 09:26 UTC, iyt-trifork commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TagDefinitionDao.java
> +public class TagDefinitionDao {
I renamed the class, and now also using ITagDefinitionDao to do persistence and retrieval.

2024-09-13 09:28 UTC, iyt-trifork commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TagDefinitionDao.java
> +		private final EntityManagerFactory myEntityManagerFactory;
Again, i refactored the entire flow again, so no longer relevant. I use ITagDefinitionDao directly.

2024-09-13 09:29 UTC, iyt-trifork commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/PartitioningSqlR4Test.java
> +		assertEquals(3, myCaptureQueriesListener.countCommits());
I reverted to the old values again, since i refactored the entire flow again.

2024-10-30 14:06 UTC, merged