6203 subscriptionvalidatinginterceptor allows invalid url for rest hook endpoint
hapifhir/hapi-fhir pull request #6225
Opened 2024-08-20 17:05 UTC by epeartree

closes #6203

2024-08-21 16:37 UTC, dotasek requested changes
Overall looks good. Would like the following resolved:

- Review regex for ReDoS and general DRY
- Some typos.
- A question regarding default settings.

2024-08-21 16:37 UTC, dotasek commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionValidatingInterceptorTest.java
> +		try {
This could use assertThrows instead of manually calling fail("") when an exception isn't thrown.

2024-08-21 16:37 UTC, dotasek commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionValidatingInterceptorTest.java
> +			return new SubscriptionChannelTypeValidatorFactory(theValidorList);
One more `validor` typo.

2024-08-21 16:37 UTC, dotasek commented on hapi-fhir-jpaserver-subscription/src/test/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionValidatingInterceptorTest.java
> +		public IChannelTypeValidator restHookChannelValidator() {
This sets the regex validation strategy for this test; should this not automatically be the default? (this could just be my misunderstanding of the bean setup for a default instance)

2024-08-21 18:34 UTC, dotasek commented on hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/config/BaseSubscriptionSettings.java
> +			"((((http?|https?)://))([-%()_.!~*';/?:@&=+$,A-Za-z0-9])+)";
Since this is a default for a client configurable setting, it makes sense to have a specific constant here. 

The regex, according to Regex101, has only greedy capturing groups, without alternative paths, which should keep it from being susceptible from ReDoS. 

However, this `http?|https?` looks suspect. It could be `http|https` or `http?` and still pass the same tests, and would be just a little clearer.

2024-08-21 18:48 UTC, dotasek commented on hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/config/BaseSubscriptionSettings.java
> +			"((((http?|https?)://))([-%()_.!~*';/?:@&=+$,A-Za-z0-9])+)";
If we really, truly want to remove doubt, we can always wholesale copy from the OWASP Regex Repository:

https://owasp.org/www-community/OWASP_Validation_Regex_Repository

2024-08-27 14:46 UTC, jamesagnew commented on hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/config/BaseSubscriptionSettings.java
> +	 * @since 7.6.0
Thanks for including the `@since` - this is perfect javadocs for this new feature.

2024-08-27 14:46 UTC, jamesagnew approved these changes

2024-08-28 11:20 UTC, merged