add batch and chunk ids to logging context
hapifhir/hapi-fhir pull request #6268
Opened 2024-09-06 00:10 UTC by jdar8

Closes #6210

2024-09-24 22:26 UTC, dotasek requested changes
Minor change to the test.

Is there existing documentation on the promised logging output that needs updating, or is logging in this case, 'you get what you get' and we've just enhanced it?

2024-09-24 22:26 UTC, dotasek commented on hapi-fhir-storage-batch2/src/test/java/ca/uhn/fhir/batch2/coordinator/WorkChannelMessageHandlerTest.java
> +				assertThat(mdcPropertySetValues).containsExactlyInAnyOrder(INSTANCE_ID, CHUNK_ID);
This would be better if it checked that the values corresponded to the appropriate keys.

2024-09-25 23:24 UTC, jdar8 commented on hapi-fhir-storage-batch2/src/test/java/ca/uhn/fhir/batch2/coordinator/WorkChannelMessageHandlerTest.java
> +				assertThat(mdcPropertySetValues).containsExactlyInAnyOrder(INSTANCE_ID, CHUNK_ID);
Thanks for the review!

I've changed the test to assert that the keys correspond to the appropriate values.

There are not any existing docs that I could find on the promised logging output. To address this, I've added a small blurb to the batch docs that the job instance ID and work chunk ID are now available through the logback context, and can be accessed using `logback.xml`.

2024-09-26 14:44 UTC, dotasek approved these changes
Looks good to me. Still requires someone with permissions for final review.

2024-10-07 17:32 UTC, tadgh approved these changes

2024-10-07 17:32 UTC, tadgh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_6_0/6210-add-chunk-id-to-delete-expunge-log-msg.yaml
> +title: "The batch instance and chunk IDs have been added to the logging MDC so that the IDs can be automatically added to
```suggestion
title: "Batch instance ID and chunk ID have been added to the logging context so that they can be automatically added to
```

2024-10-11 16:47 UTC, merged