value set expansion
hapifhir/hapi-fhir pull request #6286
Opened 2024-09-13 15:16 UTC by TipzCM

closes #6285

2024-09-27 19:04 UTC, michaelabuckley requested changes
Please don't share.  We want to delete this, and be confident nobody is gonna break v2 when they are forward porting v1 fix.

2024-09-27 19:04 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexStepV1.java
> +public class ReindexStepV1 extends BaseReindexStep
Please mark deprecated with a for-deletion date.  We _need_ to delete these once our zero-downtime window is over.

2024-09-27 20:06 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/BaseReindexStep.java
> +public abstract class BaseReindexStep {
Will duplicate some of the steps and refactor package structure

2024-09-27 20:07 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexStepV1.java
> +public class ReindexStepV1 extends BaseReindexStep
duplicated most of the unique steps and deprecated all the V1 ones.

2024-09-30 15:36 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/v1/ReindexStepV1.java
> +		ReindexTask reindexJob = new ReindexTask(jp, myDaoRegistry, mySystemDao, myIdHelperService);
problem: I'm confused here.  I thought we were going to avoid sharing code between v1 and v2.  Can we please just keep the old class as is?

2024-09-30 18:07 UTC, TipzCM commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/v1/ReindexStepV1.java
> +		ReindexTask reindexJob = new ReindexTask(jp, myDaoRegistry, mySystemDao, myIdHelperService);
split out the ReindexTask into V1V2

2024-09-30 21:04 UTC, michaelabuckley commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/reindex/v1/ReindexStepV1.java
> +
I'd be much more confident if git just told me "ReindexStepV1 renamed from ReindexStep".  But the parameters object and the rest of the rewrite sill makes the diff too large for me to compare except by manually copying files around.

I guess this is fine.  I have low confidence there are no changes since you rewired it, but the test coverage should help.

2024-09-30 21:04 UTC, michaelabuckley approved these changes

2024-10-01 17:52 UTC, merged