Backport response parameter issues for `validate-code` operation
hapifhir/hapi-fhir pull request #6360
Opened 2024-10-08 20:00 UTC by codeforgreen

2024-10-11 02:49 UTC, nathandoef approved these changes
Approved pending a couple comments / questions

2024-10-11 02:49 UTC, nathandoef commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java
> +			if (next.getSeverity() == ResultSeverityEnum.ERROR) {
Should this chane also be made to the DSTU3 test?

2024-10-11 02:49 UTC, nathandoef commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyLookupCodeR4Test.java
> +		myCodeSystemProvider2 = new MyCodeSystemProviderR4();
Please use a more descriptive name

2024-10-15 17:41 UTC, nathandoef commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java
> +			if (next.getSeverity() == ResultSeverityEnum.ERROR) {
Typo

2024-10-15 18:18 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/ParametersUtil.java
> +	public static Optional<IBaseResource> getNamedParameterResource(
Actually, all the other methods return `value` but `resource` is another element sibling to `value`, which is less used. That is why I had to fork and return the child element named `resource` instead of `value`.  In this case `OperationOutcome` is a resource and value is usually just a primitive FHIR type. I would keep this name.
I looked at code reuse but there are other differences vs. method `extractNamedParameterValues`, not just the element name - the fact that it is a single resource not a list returned, plus the filter and mapper for the returned value differs as well.

2024-10-15 18:25 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +		createValueSetReturnParameters(true, DISPLAY, SAMPLE_MESSAGE, null);
This is the success scenario with a message populated. At first I wanted to support it but then I read the spec that `message` should technically only be populated when `result=false`, and probably intuitively same thing for `issues`, although it's not specified.
see.: https://hl7.org/fhir/R4/codesystem-operation-validate-code.html

2024-10-15 18:31 UTC, codeforgreen commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java
> +		if (!resultValue.isPresent()) {
The difference I introduced is populating code in the returned CodeValidationResult using the output of the remote terminology call. Other changes are basically translating more fields into the output (`code`, `system`, `version` plus of course `issues`). I don't expect these changes to not raise any issues.

2024-10-15 18:43 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +		createValueSetReturnParameters(true, DISPLAY, SAMPLE_MESSAGE, null);
I updated the test to remove populating the message it as it's not a real use-case.

2024-10-15 18:48 UTC, nathandoef commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +		createValueSetReturnParameters(true, DISPLAY, SAMPLE_MESSAGE, null);
Thanks

2024-10-15 20:33 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +
Nitpick: could have 'assertTrue(outcome.getCodeValidationIssues().isEmpty());' here.

2024-10-15 20:34 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +
Nitpick: could have 'assertTrue(outcome.getCodeValidationIssues().isEmpty());' here.

2024-10-15 21:12 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +		createValueSetReturnParameters(true, DISPLAY, SAMPLE_MESSAGE, null);
Are we sure that the message should not be populated? From the spec @codeforgreen linked to, it seems as though it's possible to show "hints and warnings", which is totally a valid use case.

> If this is provided when result = true, the message carries hints and warnings

2024-10-15 21:21 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/dstu3/hapi/validation/RemoteTerminologyServiceResourceProviderDstu3Test.java
> -	public void testValidateCodeInValueSet_ProvidingMinimalInputs_ReturnsSuccess() {
What happened to this test? There seems to be a `validateCode_withCodeSystemProvidingMinimalInputs_ReturnsSuccess` in IValidateCodeTest, but nothing equivalent for valueset?

2024-10-15 21:37 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorWithTerminologyR4Test.java
This class shows up as never used in my IDE. A leftover from refactoring?

2024-10-15 21:42 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceResourceProviderR4Test.java
Same comments re: missing methods as DSTU3.

2024-10-15 21:53 UTC, dotasek requested changes
See individual file comments.

2024-10-15 22:33 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/dstu3/hapi/validation/RemoteTerminologyServiceResourceProviderDstu3Test.java
> -	public void testValidateCodeInValueSet_ProvidingMinimalInputs_ReturnsSuccess() {
Yes, there is one `validateCode_withValueSetProvidingMinimalInputsSuccess_returnsCorrectly`. Both were renamed.

2024-10-15 22:35 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorWithTerminologyR4Test.java
Good catch. This is where I wanted to write some new integration tests from scratch but in the end I was happy with the coverage I was able to achieve through the unit tests. I will remove this.

2024-10-15 22:36 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java
> +			if (next.getSeverity() == ResultSeverityEnum.ERROR) {
This change was removed as it was made only locally for debug purposes. Sorry about that.

2024-10-15 22:45 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceResourceProviderR4Test.java
Indeed, there are tests in R4 which are not in DSTU3, e.g. those added for https://github.com/hapifhir/hapi-fhir/issues/3072. I did some refactoring in the tests and enabled some to reuse across versions but these I didn't get a chance to port to version independent, they are version dependent at the moment.

2024-10-16 13:14 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/RemoteTerminologyServiceResourceProviderR4Test.java
Yes, I meant validateCodeInValueSet, and your previous comments have pointed out that it now exists in IValidateCodeTest.

2024-10-16 13:15 UTC, dotasek approved these changes

2024-10-16 14:16 UTC, merged

2024-10-16 18:25 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +		createValueSetReturnParameters(true, DISPLAY, SAMPLE_MESSAGE, null);
@dotasek you're right I misread, I guess I didn't fully read the description. I decided to leave this change alongside other to follow the spec for another time, because of time constraints. Another important one I wanted to address is the CodeValidationResult#isOk() which relies on presence of code to determine the success. That has to change as well.