bumping fhir core version
hapifhir/hapi-fhir pull request #6364
Opened 2024-10-10 20:29 UTC by TipzCM

closes #6363

2024-10-10 20:59 UTC, jmarchionatto approved these changes

2024-10-11 20:28 UTC, volodymyr-korzh requested changes

2024-10-11 20:28 UTC, volodymyr-korzh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_6_0/6317-fix-resource-duplication-for-composite-unique-sp-with-date-time-component.yaml
> +backport: 7.4.4
This `backport: 7.4.3` should remain for this changelog. Looks like it was changed by mistake.

2024-10-11 20:28 UTC, volodymyr-korzh commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_3/6363-updating-fhir-core-dependency.yaml
> +title: "Updating fhir_core dependency to fix vulnerability."
Suggestion - add version of core library to changelog

```
---
type: fix
issue: 6363
backport: 7.4.4
This release bumps the org.hl7.fhir core dependency up to 6.3.23, which includes vulnerability fixes.
```

As I undrestand it is a backport from master ? If yes, it should be put in the same folder as in master (`7_6_0`)
but with added backport property:

`backport: 7.4.4`

2024-10-11 20:28 UTC, volodymyr-korzh commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +						|| !statusTypes.get(0).getValueAsString().equals("?"));
Question: are these changes is a result of core library update ?

2024-10-11 20:33 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_6_0/6317-fix-resource-duplication-for-composite-unique-sp-with-date-time-component.yaml
> +backport: 7.4.4
oops. updated

2024-10-11 20:39 UTC, TipzCM commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java
> +						|| !statusTypes.get(0).getValueAsString().equals("?"));
yeah

2024-10-11 20:39 UTC, volodymyr-korzh approved these changes
Looks good, approved

2024-10-11 20:39 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_3/6363-updating-fhir-core-dependency.yaml
> +title: "Updating fhir_core dependency to fix vulnerability."
updated; but not a backport

2024-10-11 20:40 UTC, TipzCM commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_6_0/6317-fix-resource-duplication-for-composite-unique-sp-with-date-time-component.yaml
> +backport: 7.4.4
fixed

2024-10-11 21:51 UTC, merged