Feat/support head metadata
hapifhir/hapi-fhir pull request #6406
Opened 2024-10-26 18:05 UTC by jkiddo

2024-10-29 07:28 UTC, jkiddo commented
@jamesagnew this is the corrected version of https://github.com/hapifhir/hapi-fhir/pull/6152
I've moved the changelog entry to 7.8.0

2025-03-06 22:00 UTC, dotasek requested changes
Implementation looks good, but I'd like to see two explicit HEAD tests added, as mentioned in the the file comments.

2025-03-07 08:03 UTC, jkiddo commented on hapi-fhir-structures-dstu3/src/test/java/ca/uhn/fhir/rest/server/MetadataConformanceDstu3Test.java
> +			assertEquals("<OperationOutcome xmlns=\"http://hl7.org/fhir\"><issue><severity value=\"error\"/><code value=\"processing\"/><diagnostics value=\"" + Msg.code(388) + "/metadata request must use HTT
I cant believe I forgot that 🤦

2025-03-07 14:31 UTC, jkiddo commented on hapi-fhir-structures-dstu3/src/test/java/ca/uhn/fhir/rest/server/MetadataCapabilityStatementDstu3Test.java
> +			assertEquals("<OperationOutcome xmlns=\"http://hl7.org/fhir\"><issue><severity value=\"error\"/><code value=\"processing\"/><diagnostics value=\"" + Msg.code(388) + "/metadata request must use HTT
See https://github.com/trifork/hapi-fhir/commit/a609b5fccc0c2a92550443bb85b0a5956d2d68c3

2025-03-07 14:32 UTC, jkiddo commented on hapi-fhir-structures-dstu3/src/test/java/ca/uhn/fhir/rest/server/MetadataConformanceDstu3Test.java
> +			assertEquals("<OperationOutcome xmlns=\"http://hl7.org/fhir\"><issue><severity value=\"error\"/><code value=\"processing\"/><diagnostics value=\"" + Msg.code(388) + "/metadata request must use HTT
See https://github.com/trifork/hapi-fhir/commit/cd219be3e2dc5d8afa354a31f4fe9c872476e8e6

2025-03-07 14:32 UTC, jkiddo commented
@dotasek both comments should be adressed by now

2025-03-07 15:04 UTC, jkiddo commented
@dotasek - also - running spotless showed no changes.

2025-03-07 23:07 UTC, dotasek approved these changes

2025-03-07 23:13 UTC, dotasek commented
@jkiddo I've approved of this PR, but for some reason, two checks are consistently failing.

What's weird is, they do indeed pass locally when I run them, but report a HAPI version of 8.1.0-SNAPSHOT instead of the 8.1.1-SNAPSHOT that the test results are showing. 

Could you try another merge from master and see if you can get this to 8.1.1-SNAPSHOT?

2025-03-08 11:12 UTC, jkiddo commented
@dotasek - as requested - master is now merged in

2025-03-11 14:17 UTC, epeartree approved these changes

2025-03-11 14:17 UTC, epeartree commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/ConformanceMethodBinding.java
> -					Msg.code(388) + "/metadata request must use HTTP GET", RequestTypeEnum.GET);
is passing in the requestTypeEnum as parameter is not required here.  please remove it.

2025-03-11 15:41 UTC, jkiddo commented on hapi-fhir-server/src/test/java/ca/uhn/fhir/rest/server/method/ConformanceMethodBindingTest.java
> +	@Test
Fixed in https://github.com/hapifhir/hapi-fhir/pull/6406/commits/9adfa328260cf1df28972d538b16452a8d95581d

2025-03-11 15:41 UTC, jkiddo commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/ConformanceMethodBinding.java
> -					Msg.code(388) + "/metadata request must use HTTP GET", RequestTypeEnum.GET);
Fixed in https://github.com/hapifhir/hapi-fhir/pull/6406/commits/9adfa328260cf1df28972d538b16452a8d95581d

2025-03-14 19:28 UTC, dotasek approved these changes

2025-03-27 13:20 UTC, dotasek approved these changes

2025-05-01 18:48 UTC, robogary commented
<!-- add-pr-comment:add-pr-comment -->

Formatting check succeeded!

2025-05-02 00:24 UTC, merged