Fixes for the translation of parameter issues as part of the output for $validate-code operation.
hapifhir/hapi-fhir pull request #6423
Opened 2024-10-30 19:57 UTC by codeforgreen

Fixes #6422

2024-10-31 15:52 UTC, dotasek requested changes
I encountered a NullPointer when executing RemoteTerminologyValidateCodeDstu3Test and RemoteTerminologyValidateCodeR4Test. I believe this code is missing:

```java
class CodeValidationIssueCodeableConcept {
		//...
		
		// intentionally not exposed
		void addCoding(CodeValidationIssueCoding theCoding) {
			if (myCodings == null) {
				myCodings = new ArrayList<>();
			}
			getCodings().add(theCoding);
		}
```

Changes look good otherwise.

2024-10-31 15:52 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +			assertEquals(expectedIssue.getDiagnostics(), actualIssue.getDiagnostics());
I put a breakpoint here with the condition `expectedIssue.getDiagnostics() != null` to verify that we're checking that diagnostics are set in some test. My point wasn't hit.

2024-10-31 17:53 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +	class CodeValidationIssueTypeCode {
I left the ones that are related to validation which were there in the code before as well. I can add a comment with that. I guess these are also the only codes we internally use to build issues for internal validators. If it's remote terminology any code will work because it will be using the generic constructor. 

We are currently permissive when it comes to issue type (required binding) and details codes (example binding), not severity code (required binding) because that is small enough. The part I am not sure about is checking nulls for severity and issue code, which have cardinality of 1 according to the profile.

When the validateCode call returns the response  to the `InstanceValidator` we can find this in method  `InstanceValidator#txIssue`:

```
ValidationMessage.IssueType code = IssueType.fromCode(issue.getCode().toCode());
ValidationMessage.IssueSeverity severity = IssueSeverity.fromCode(issue.getSeverity().toCode());
```

This will throw exceptions if the codes are not in those enums which seem to have all the elements.

2024-10-31 17:55 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +			assertEquals(expectedIssue.getDiagnostics(), actualIssue.getDiagnostics());
Agree. We currently have it in our internal validators but we should not be replying on tests for those. I will add more for that here (diagnostics populated but not issue detail text).

2024-11-04 16:17 UTC, dotasek approved these changes
See comment in file.

2024-11-04 16:17 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
While reviewing other parts of this, I noticed that there are a few places where validation ignores the outcome code:

```java
// assertEquals(CODE, outcome.getCode());
```

This isn't part of this review, but is related. Is this a byproduct of the testing utilities, or something that will show up in validation everywhere?

2024-11-04 16:25 UTC, dotasek commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +			assertEquals(expectedIssue.getDiagnostics(), actualIssue.getDiagnostics());
On second review, I can see a few places we actually check the diagnostics field:

https://github.com/hapifhir/hapi-fhir/blob/a35383442cd93853b83657aff46099086ec01b53/hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java#L217
https://github.com/hapifhir/hapi-fhir/blob/a35383442cd93853b83657aff46099086ec01b53/hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java#L269

2024-11-04 18:12 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
It is because the boolean result outcome for validateCode (succes or not) in object `IValidationSupport.CodeValidationResult` is dictated by `isOk` method which has condition that code != null to determine success. I mentioned that in the previous PR as well. https://github.com/hapifhir/hapi-fhir/pull/6360/files#diff-003fe663a54000163c7b18239f3c2be278ed03548006676e595ab5d1d932c80dR652
That would require some more refactoring changes to update.
I also mentioned it in this defect (which I also found) so it's not forgotten: https://gitlab.com/simpatico.ai/cdr/-/issues/6708#solution-design

2024-11-04 18:47 UTC, codeforgreen commented on hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/IValidateCodeTest.java
> +			assertEquals(expectedIssue.getDiagnostics(), actualIssue.getDiagnostics());
Yes these checks were there but after I introduced the renamed getter (`getDiagnostics` in addition to `getMessage`) it became more obvious, because getMessage existed in the parent `CodeValidationResult` object as well. I kept all old methods and marked them as deprecated after introducing the alternative to avoid any breakage.

2024-11-04 19:35 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +			return Arrays.stream(values())
This seems kinda inefficient for something that is potentially called quite a bit... I doubt we'll ever add any more values to this enum, could we just put a simple switch statement here instead of looping through the enum values??

2024-11-04 19:36 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +		 * Deprecated. Please use {@link #getDetails()} instead. That has support for multiple codings.
```suggestion
		 * @deprecated Please use {@link #getDetails()} instead. That has support for multiple codings.
```

2024-11-04 19:37 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +		 * Deprecated. Please use method {@link #getIssues()} instead.
```suggestion
		 * @deprecated Please use method {@link #getIssues()} instead.
```

2024-11-04 19:37 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +		 * Deprecated. Please use method {@link #setIssues(List)} instead.
```suggestion
		 * @deprecated Please use method {@link #setIssues(List)} instead.
```

2024-11-04 19:38 UTC, jamesagnew commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +		 * Deprecated. Please use method {@link #addIssue(CodeValidationIssue)} instead.
```suggestion
		 * @deprecated Please use method {@link #addIssue(CodeValidationIssue)} instead.
```

2024-11-04 19:41 UTC, jamesagnew approved these changes

2024-11-04 19:53 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +			return Arrays.stream(values())
Oh, I think this is unused, I'll get rid of it.

2024-11-04 19:55 UTC, codeforgreen commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/IValidationSupport.java
> +	class CodeValidationIssueCoding {
Because the binding strength is example in the spec and `http://hl7.org/fhir/tools/CodeSystem/tx-issue-type` is not required or even preferred at the moment. Even a custom system can be used which I have seen happening in case of a hapi-fhir client.

2024-11-05 17:13 UTC, merged