Add support for disabling prefixChannelName to message broker ChannelSettings
hapifhir/hapi-fhir pull request #6497
Opened 2024-11-22 06:07 UTC by volodymyr-korzh

…Settings

2024-12-02 17:55 UTC, fil512 requested changes

2024-12-02 17:55 UTC, fil512 commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/subscription/channel/api/BaseChannelSettings.java
> +	public boolean isUsePrefixChannelName() {
This change should not be in hapi-fhir, since it is not used in hapi-fhir.

2024-12-06 17:10 UTC, volodymyr-korzh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/subscription/channel/api/BaseChannelSettings.java
> +	public boolean isUsePrefixChannelName() {
`IChannelNamer` interface has `getChannelName` method with definition:
`String getChannelName(String theNameComponent, IChannelSettings theChannelSettings);`

Having `isUsePrefixChannelName` outside of hapi-fhir will force IChannelNamer implementors to cast IChannelSettings to specific IChannelSettings implementation, the may be not optimal

2024-12-10 16:41 UTC, volodymyr-korzh commented on hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/subscription/channel/api/BaseChannelSettings.java
> +	public boolean isUsePrefixChannelName() {
Removed `isUsePrefixChannelName` from `BaseChannelSettings`

2024-12-12 19:41 UTC, tadgh approved these changes

2024-12-12 20:24 UTC, fil512 approved these changes

2024-12-12 20:42 UTC, merged