6463 resource validation multiple version
hapifhir/hapi-fhir pull request #6507
Opened 2024-11-23 16:13 UTC by MangalaEkanayake

- version in canonical url is used to search StructureDefinition
- remain the version of a Resource to identify it properly

2024-11-23 17:41 UTC, jamesagnew requested changes
Hi @MangalaEkanayake - Thanks for the contribution! This seems like a useful change.

I've made some suggestions inline. This change will affect several other modules that you haven't modified, so these would need to be updated and tested, and unit tests written for the existing change as well.

With those changes, we can definitely get this merged.

2024-11-23 17:41 UTC, jamesagnew commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java
>  			String[] parts = theUri.split("\\|");
Since we don't actually need the split values anymore, just to count them it might make sense to replace this with something like `StringUtils.countMatches`

2024-11-23 17:41 UTC, jamesagnew commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java
> +		ResourceKey key = new ResourceKey(class_.getSimpleName(), theUri);
This change means that we'll be passing canonical URLs containing versions to a number of other implementations of `fetchResource`, `fetchStructureDefinition`, `fetchCodeSystem`, and `fetchValueSet` in the various other implementations of `IValidationSupport`. 

In cases like `CachingValidationSupport` and `ValidationSupportChain` it doesn't matter since they just pass the URL through, and others like `InMemoryTerminologyServerValidationSupport` just don't implement these methods so they'll be fine too.

But others like `NpmJpaValidationSupport`, `PrePopulatedValidationSupport` and `DefaultProfileValidationSupport` all implement these methods. These will all need to be checked to ensure that they support both versionless and versioned URLs correctly. Ideally using unit tests.

2024-11-23 17:41 UTC, jamesagnew commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaPersistedResourceValidationSupport.java
> +				if (versionSeparator != -1) {
This change should be unit tested.

2024-11-25 05:18 UTC, MangalaEkanayake commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java
> +		ResourceKey key = new ResourceKey(class_.getSimpleName(), theUri);
Those are old implementations. this change has done recently by https://github.com/hapifhir/hapi-fhir/issues/6040.
So I guess those should works as expected.
meantime no any existing unit tests are failing. 
we have an IValidationSupport implementation based on version and it works fine. I don't expect to write any unit tests to these existing modules.

2024-12-02 12:31 UTC, MangalaEkanayake commented
> Hi @MangalaEkanayake - Thanks for the contribution! This seems like a useful change.
> 
> I've made some suggestions inline. This change will affect several other modules that you haven't modified, so these would need to be updated and tested, and unit tests written for the existing change as well.
> 
> With those changes, we can definitely get this merged.

Hi @jamesagnew - can we merge this?

2024-12-05 03:36 UTC, closed without merging