Add replace-references operation
hapifhir/hapi-fhir pull request #6526
Opened 2024-11-28 20:44 UTC by jmarchionatto

2024-12-03 18:07 UTC, fil512 requested changes

2024-12-03 18:07 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +		List<? extends IBaseResource> referencingResources = findReferencingResourceIds(theCurrentTargetId, theRequest);
this needs to be a Stream. If there are a trillion resources, it would blow the RAM on the server.

2024-12-03 18:07 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +		return dao.search(parameterMap, theRequest).getAllResources();
instead of search, I suggest returning 	dao.searchForIdStream

2024-12-03 19:24 UTC, jmarchionatto commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/api/Constants.java
> +	public static final String PARAM_NEW_REFERENCE_TARGET_ID = "newReferenceTargetId";
Moved

2024-12-04 18:29 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +		List<? extends IBaseResource> referencingResources = findReferencingResourceIds(theCurrentTargetId, theRequest);
Added todo indicating batch job implementation is coming to address mentioned case

2024-12-04 18:37 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +		return dao.search(parameterMap, theRequest).getAllResources();
Suggestion can't be implemented at the current state of dao.searchForIdStream because:
1. returns a stream of IResourcePersistentId, which doesn’t carry the resource type, which is needed because reverse references can be of any resource type
2. searches for resources don’t consider revinclude parameter, as dao.search does

In any case, main reason for the comment will be soon be addresses by adding a batch job implementation for large volume cases

2024-12-04 19:15 UTC, fil512 approved these changes

2024-12-04 19:15 UTC, fil512 commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +	private IBaseParameters replaceReferencesInTransaction(
the method name says InTransaction but I don't see a transaction...?

2024-12-04 19:15 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/provider/ProviderConstants.java
> +	public static final String PARAM_SOURCE_REFERENCE_ID = "sourceReferenceId";
I believe the convention for Parameters requests is kebab-case. I.e. source-reference-id.
See https://build.fhir.org/patient-operation-merge.html

2024-12-04 19:24 UTC, jmarchionatto commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/provider/ProviderConstants.java
> +	public static final String PARAM_SOURCE_REFERENCE_ID = "sourceReferenceId";
Actually, all parameters defined in the class use camel case, also as per your suggestion: 

```json
{
  "resourceType": "Parameters",
  "parameter": [ {
    "name": "sourceReferenceId",
    "valueString": "Patient/123"
  },
{
    "name": "targetReferenceId",
    "valueString": "Patient/REP"
  } ]
}
```

2024-12-04 19:27 UTC, jmarchionatto commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ReplaceReferencesSvcImpl.java
> +	private IBaseParameters replaceReferencesInTransaction(
That was to differentiate this implementation of the removed but coming `replaceReferencesInBatch` implementation

2024-12-04 19:27 UTC, merged

2024-12-04 19:35 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/provider/ProviderConstants.java
> +	public static final String PARAM_SOURCE_REFERENCE_ID = "sourceReferenceId";
I have since learned that my suggestion was incorrect

2024-12-04 19:38 UTC, jmarchionatto commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/provider/ProviderConstants.java
> +	public static final String PARAM_SOURCE_REFERENCE_ID = "sourceReferenceId";
But it wasn't! All the other parameters in the class are camel case