Expose ConsentInterceptor#getConsentService for integration test purposes
hapifhir/hapi-fhir pull request #6527
Opened 2024-11-28 21:42 UTC by codeforgreen

2024-12-13 19:00 UTC, nathandoef approved these changes

2024-12-13 21:53 UTC, dotasek requested changes
A little nit-pick:

There are explicit methods to add and remove consent services; exposing the whole list via this new method offers a way to bypass those.

Could this be wrapped in a unmodifiableList, or return just an Iterable, or does all the list functionality really need to be exposed?

2024-12-18 19:35 UTC, codeforgreen commented
> A little nit-pick:
> 
> There are explicit methods to add and remove consent services; exposing the whole list via this new method offers a way to bypass those.
> 
> Could this be wrapped in a unmodifiableList, or return just an Iterable, or does all the list functionality really need to be exposed?

Makes sense. Resolved.

2024-12-19 18:24 UTC, jamesagnew approved these changes

2024-12-19 18:24 UTC, merged