6530 refactor export operation
hapifhir/hapi-fhir pull request #6531
Opened 2024-12-02 21:01 UTC by AD1306

2024-12-11 19:18 UTC, tadgh approved these changes
Approved pending relatively large changes

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportJobService.java
> +public class BulkDataExportJobService {
```suggestion
public class BulkExportJobService {
```

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportJobService.java
> +	public void startJob(
issue(blocking): This entire class requires javadocs.

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportJobService.java
> +		}
issue: expandParameters should not be invoking hooks as part of its workflow. Recommend reworking the overall  logic to these new methods: 
1. do internal pre-operations
2. Invoke STORAGE_PRE_INITIATE_BULK_EXPORT
3. Invoke STORAGE_INITIATE_BULK_EXPORT
4. Start Job.

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportSupport.java
> +public class BulkDataExportSupport {
suggestion: class-level javadocs, or maybe package-level, defining the differences between BulkDataExportSupport, BulkDataExportSvc, BulkDataExportUtil, as those are all smelling very similar

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportSupport.java
> +	}
question: Is this new, or refactored? I ask because this assumes the same partition for every single resource, which may or may not be the case in megascale.

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportSupport.java
> +	public void validateOrModifyResourceTypes(@Nonnull BulkExportJobParameters theBulkExportJobParameters) {
issue: This method clearly applies to patient style export, but i see no docs indicating this, and the name doesnt indicate it either. maybe `validateOrDefaultResourceTypesForPatientBulkExport`

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportUtil.java
> +			FhirVersionEnum.R4B);
Issue: When did you last merge master in, this code you've refactored has since been deleted. https://github.com/hapifhir/hapi-fhir/pull/6537/files#diff-7765258d356e64f1feba0a3ee75b705c93b0f4b79d95897b525995e771fc1aabL826

2024-12-11 19:18 UTC, tadgh commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportUtil.java
> +	}
yeah, delete all this device magic

2024-12-11 19:20 UTC, tadgh requested changes
changing my mind on the approval flag, as i did request large enough changes to be worth a re-review

2024-12-12 15:12 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportJobService.java
> +public class BulkDataExportJobService {
done.

2024-12-12 15:12 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportJobService.java
> +	public void startJob(
added.

2024-12-12 15:13 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportSupport.java
> +	}
it is refactored. no changes to the original codebase. https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java#L323

2024-12-12 15:13 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportSupport.java
> +	public void validateOrModifyResourceTypes(@Nonnull BulkExportJobParameters theBulkExportJobParameters) {
this is actually only invoked for group type export. I've changed it to appropriate name.

2024-12-12 15:15 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportUtil.java
> +			FhirVersionEnum.R4B);
ah I probably split the class before that merge went in so, it caused duplication. I've removed that.

2024-12-12 15:15 UTC, AD1306 commented on hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportUtil.java
> +	}
done.

2024-12-12 18:58 UTC, merged