Issue with combo index search parameter when using date
hapifhir/hapi-fhir pull request #6566
Opened 2024-12-18 18:34 UTC by epeartree

2025-01-10 14:21 UTC, jmarchionatto submitted a review, later dismissed
Fix looks good, but there is no test for the specific point of the fix, which is that the combo search is now considered. Please add test for that case.

2025-01-10 15:09 UTC, jamesagnew commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6603-combo-index-sp-not-invoked-with-dateparam.yaml
> +optimised indexes when the query string included date parameters. This issue is fixed."
I'm assuming based on what was fixed that the issue is actually when the query string contained a date range (i.e. multiple repetitions of the same date parameter). Might be helpful to note that.

```suggestion
optimised indexes when the query string included a date range (i.e. multiple instances of the same date parameter). This issue is fixed."
```

2025-01-10 15:11 UTC, jamesagnew commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/param/DateRangeParamR4Test.java
> +		assertNull(ourLastDateRange.getUpperBound().getPrefix());
I'd recommend adding a comment here indicating why it's important that this be null - Also should probably include a test in `FhirResourceDaoR4ComboUniqueParamTest` that verifies the actual overall functionality being fixed here.

2025-01-13 16:42 UTC, epeartree commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6603-combo-index-sp-not-invoked-with-dateparam.yaml
> +optimised indexes when the query string included date parameters. This issue is fixed."
updated the changelog to include the recommended syntax.

2025-01-13 16:47 UTC, epeartree commented on hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/param/DateRangeParamR4Test.java
> +		assertNull(ourLastDateRange.getUpperBound().getPrefix());
Added a comment to the test;
Added a new test to class FhirResourceDaoR4ComboNonUniqueParamTest since 'birthdate' is of type DATE  which will make the search no valid for unique combo searching.

2025-01-13 17:00 UTC, jamesagnew requested changes

2025-01-13 17:00 UTC, jamesagnew commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6603-combo-index-sp-not-invoked-with-dateparam.yaml
> +optimised indexes when the query string included a date ragne (i.e. multiple instances of the same date parameter). This
```suggestion
optimised indexes when the query string included a date range (i.e. multiple instances of the same date parameter). This
```

2025-01-13 17:00 UTC, jamesagnew commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ComboNonUniqueParamTest.java
> +			"eq2025-01-01, false"
I'm not sure I follow the test. If those two query strings are considered equivalent, why are we treating them differently? I guess it's because we turn this into a date range, but that logic is kinda confusing. Recommend at least adding comments here to explain what's going on with this test and why we should expect a different result for these two values.

2025-01-13 17:43 UTC, epeartree commented on hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ComboNonUniqueParamTest.java
> +			"eq2025-01-01, false"
NP at all.  to avoid a regression, this test and its purpose needs be crystal clear on the first read.

2025-01-15 17:02 UTC, jamesagnew approved these changes

2025-01-16 13:22 UTC, merged